### ISSUE TITLE
[Feature request] move buffer number just before the file name

### ISSUE THREAD

**Issue by shaeinst** [akinsho/bufferline.nvim#152]
![image](https://user-images.githubusercontent.com/41078534/126156826-790cea23-e9f1-4a8a-9732-a85ca5cfe610.png)

**Comment by akinsho** [comment]
@shaeinst this isn't possible as the numbers are added before the buffer spacing is applied, I'd rather only do things one way or the other i.e. have them side by side or not rather than try and support both ways as that's more complexity I wouldn't want.

**Comment by akinsho** [comment]
This was closed by #199
