### ISSUE TITLE
[Feature request] Stop updating lsp diagnostics count when auto completing.

### ISSUE THREAD

**Issue by moshiur-raj** [akinsho/bufferline.nvim#160]
Bufferline updates the lsp diagnostics count when selecting a suggestion from the auto completion menu. I think this is unnecessary and distracting.
It would be much better if bufferline updated the count only when editing in normal mode or when entering the normal mode from insert mode. This is also the default behavior in `nvim-lspconfig`.

I have a question....
Does turning this option on cause neovim to check the file for errors twice? once for bufferline and then for the lsp diagnostic messages? or does neovim only do it once and reuse the diagnostic message?

**Comment by akinsho** [comment]
@moshiur-raj the plugin uses the exposed diagnostics information, similar to how you would use it in your statusline. It doesn't trigger new requests or cause a whole bunch of logic to run. The diagnostics module just saves this information for things like plugins/users to read.

Regarding not showing updates under certain conditions, it might or might not be easy to add it could just be a question of wrapping the function in a mode check or it could involve needing to add autocommand to specifically redraw the tabline, in either case happy to review a PR for it.

**Comment by moshiur-raj** [comment]
I see.
Neovim 0.5 is really awesome and has made me very interested in learning lua. It's waaay better than vimscript.
I'll have to give it a go then...

**Comment by akinsho** [comment]
I believe this can be closed by #209 which added an option to not update diagnostics in insert mode, you can have a look at that PR for more details.

**Comment by moshiur-raj** [comment]
the problem still persists though. is there an option i need to enable?

**Comment by akinsho** [comment]
@moshiur-raj yes there is please check the linked PR for details

**Comment by moshiur-raj** [comment]
thanks,  using `	diagnostics_update_in_insert = false` fixed the issue.
