### ISSUE TITLE
[Feature request] allow custom mappings using bufferline numbers

### ISSUE THREAD

**Issue by ExpandingMan** [akinsho/bufferline.nvim#164]
At first I was going to use buffer ID's instead of the numbers provided by bufferline, but I realized that the great virtue of the bufferline numbering is that they are labeled 1-9 allowing for easy keyboard shortcuts.  Then I have a different problem: I am not sure how to e.g. open a new vertical split with a specific buffer (according to the bufferline numbering scheme), because the standard vim buffer management commands use the internal ID.  Could someone help me figure out how to reconcile these?  Thanks!

**Comment by akinsho** [comment]
Hi @ExpandingMan,

Not a 100% sure I understand, but you can use `number_style = ordinal` to see the buffer number that bufferline is using, i.e. the position of the buffer in the internal list. I think down the line to allow executing a custom action against a visible buffer in the line base on a position it would be good to expose a sort of `buf_execute(<number>, user_func)` that a user can create a mapping for and maybe the number is based on a count so something like
```vim
nnoremap <leader>b lua require('bufferline').buf_exec(vim.v.count, user_func)
```
That way, a user can do something like `4<leader>b` to run a function for that buffer. Anyway, that currently doesn't exist, so ordinal numbers are your best chance.

**Comment by ExpandingMan** [comment]
Ok, good to know, thanks!

Yes, this is essentially what I was trying to do.  Basically, the `nvim-bufferline` numbers are more useful than the native vim numbers (because they allow for consistent key bindings), but you can't execute other buffer commands in terms of them.  It would be great to have some sort of ability to do this at some point.

**Comment by akinsho** [comment]
This has now been added in the latest commit to master
