### ISSUE TITLE
[Question] Is there a way to update buffer number after sort buffer?

### ISSUE THREAD

**Issue by cstsunfu** [akinsho/bufferline.nvim#167]
Thanks for your awesome work.

I have used the function sort_by to sort the buffers, it's really useful when opening many buffers. But the buffer number is not updated, the number is disorganized. I have to check the buffer number carefully when I change the buffer using shortcut "leader+buffer_num".  So I want to know, is there any way to update buffer number by the real position after buffer sort.

**Comment by akinsho** [comment]
@cstsunfu I'm not entirely sure if I follow tbh. The buffer number that the mappings relate to are the *absolute positions* of the buffers in the list, not the visible position of the buffers. In either case I'm working on #169 which will change the mappings to work based on the visible position at any given point. Not sure if that relates to this or not really though.

**Comment by cstsunfu** [comment]
Thanks for your reply, change the mappings sounds reasonable.
If there is any update, please let me know.

**Comment by akinsho** [comment]
No, there is no update yet as I'm working on quite a few things atm. It'll be merged when I have time to continue working on it.

**Comment by akinsho** [comment]
This should now be resolved by #169 with the new `BufferLineGotoBuffer` command

**Comment by cstsunfu** [comment]
@akinsho  Hi, thanks for your job. And there are two small questions. 
The first one is when I sort the buffers manually, it works well, but when I want the buffer auto sorted, the configure in "require('bufferline').setup(sort_by = custom_function())" don't work as expected. 

The second one is a feature request, besides the :bnext and :bprev, the :blast and :bfirst is also very useful when I open many buffers, could you please provide this two mapping functions?

**Comment by akinsho** [comment]
@cstsunfu 
> The first one is when I sort the buffers manually, it works well, but when I want the buffer auto sorted, the configure in "require('bufferline').setup(sort_by = custom_function())" don't work as expected.

Not sure if I understand fully, but the example you are showing looks incorrect since you are immediately invoking your `custom_function` rather than *passing* a custom function to the sort by field. It should look like

```lua
local function sort_function(blah, blah)
  -- logic here
end
-- in config
sort_by = sort_function -- Do not call this function here, instead pass it as an option
```

One other thing to look out for if you are using vim sessions is that manually sorted buffers are persisted across sessions so check if the `g:BufferLinePositions` variable exists, if so make sure to delete it using `unlet!` check `:h unlet` for details

Regarding the feature request tbh I don't have the bandwidth to add features atm, I think the feature set of this plugin is growing too much, and it is becoming a bit huge. You can raise the issue and maybe someone else will help, but I need to start restricting the amount of new things that get added.

**Comment by cstsunfu** [comment]
@akinsho  I'm sorry for I do not clearly describe the first question.
The sort_function is not called immediately, I just use your method to sort buffers.
![func](https://user-images.githubusercontent.com/24812659/130410835-acb65e3a-1f54-4dcc-9d67-eaa04a794e5c.png)

Use this method to sort buffers, the buffer will be auto sorted when I change some buffer, but the number is not updated as expected which the first buffer on their visual position labeled "1", the second labeled "2"...
![display](https://user-images.githubusercontent.com/24812659/130410976-076cece2-4324-467a-81f9-478656cfe0b0.png)

But the number is not updated automatically.

When I call ":lua require'bufferline'.sort_buffers_by(sort_by_function))" everything works well.

**Comment by akinsho** [comment]
Ah right I forgot about that aspect of things. I'll leave this open till it's sorted

**Comment by akinsho** [comment]
This should be resolved now @cstsunfu 🤞🏿 👍🏿

**Comment by cstsunfu** [comment]
@akinsho Thank you for responding so quickly. But there is a small issue. 
The behavior of manually executing the sorting command and automatically executing the sorting command in the configuration file is still inconsistent. The serial number of the buffer is fixed after the sort command is executed manually, and the serial number will not change even after the file is saved, this is reasonable. But after the automatic execution of the sort command by setup sort_by in configure, when I save the currently edited file, the buffer serial number is restored to the original order，and the visual order has also changed.

The buffer that has just been edited is ranked first regardless of whether it is saved or not, which is more in line with my expectations.

BTW， my sort_by function is:
```
    _G.buffer_sort_by_whether_modified = function(buffer_a, buffer_b)
        -- add custom logic
        local function bool_to_number(value, id)
            if value then
                return 100000 - id
            else
                return 0 - id
            end
        end

        return bool_to_number(buffer_a.modified, buffer_a.ordinal) > bool_to_number(buffer_b.modified, buffer_b.ordinal)
    end
```

If my description confuses you. Then I will add some pictures.

**Comment by akinsho** [comment]
@cstsunfu sorry I don't understand, I use a custom sort function to order functions by their last modified time and this seems to sort things correctly. I'm not sure which cases aren't covered, pictures might be helpful. Tbh I've more or less reached the limit of time I think I'm willing to spend fixing this issue since it's a feature I personally don't use. Please add some photos and if it's simple I will fix it otherwise I won't since I don't want to spend more time on this if I can avoid it.

**Comment by cstsunfu** [comment]
@akinsho  I'm really sorry to have delayed you so long here.

This is my configuration about sorting.
![sort](https://user-images.githubusercontent.com/24812659/130666615-de62d87a-e8a5-4538-8f1f-56cd7b903ddc.png)

The following screen recording is what happened when I was editing the file.
![record](https://user-images.githubusercontent.com/24812659/130666913-991b38ca-431c-44c2-9b0c-bae81373bc11.gif)

1. First I open two files, the first file is "bufferline.lua", and the second file is "a.lua".

2. Then I edit "a.lua".

3. The location of "a.lua" and "bufferline.lua" has been swapped, which is in line with expectations.

4. Then I use ":w" to save the changes to a.lua.

5. "a.lua" and "bufferline.lua" are swapped back to the original order.

What I expect in step 5 is that when I save "a.lua", no swap happens

.

When I manually perform the sorting using the configuration method below, everything works fine.
![right](https://user-images.githubusercontent.com/24812659/130668348-7df90a43-c373-4c6a-ac6c-b2b703c0f50f.png)
