### ISSUE TITLE
[Question] Disable default behavior of new tab on new buffer

### ISSUE THREAD

**Issue by jeanlucthumm** [akinsho/bufferline.nvim#186]
Is it possible to match the functionality of default nvim tabs but keep the aesthetics of `nvim-bufferline`? Specifically, is there an option to not have bufferline open a new tab when a new buffer is created?

**Comment by akinsho** [comment]
@jeanlucthumm this is essentially completely different functionality to what this plugin provides. I've got this request a surprising amount of times, but given that the plugin is called `bufferline`.

I'm going to add in a section to the README to explain this, but basically I use a buffer based workflow and only sometimes want to see tabs and even then I only need to know how many are open and which one I'm using.

I don't really understand the need for a tabline really but if a user can explain their reasoning well, and *they* are happy to create a PR for that functionality then I will help guide it, but I *personally* will not implement a tabline mode.

**Comment by akinsho** [comment]
closing as a duplicate/in favour of #195 and since the note has been added to the README. If you are interested in contributing please comment in #195
