### ISSUE TITLE
[Feature Request]: Option for padding between buffer icon and buffer name

### ISSUE THREAD

**Issue by HumblePresent** [akinsho/bufferline.nvim#192]
### What happened?

I recently started using [nonicons](https://github.com/yamatsum/nvim-nonicons) which are slightly larger than the typical icons from nerd fonts. For that reason, I include an extra space after each icon in my config for [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) so that there is sufficient gap between the icon and any text after it. With this config, bufferline displays the icon followed by 2 spaces and then the buffer name, exactly as I would like. The issue comes from buffer pick mode where the unique letter generated for each buffer is displayed in place of the buffer icon with only one space between it and the buffer name. Going from two spaces to one space for each buffer causes the whole bufferline to visually shrink when entering buffer pick mode and then expand after selecting a buffer. I'm wondering if it's possible to add an option for a number of padding spaces between the buffer icon and buffer name that would be respected by buffer pick mode. 
### What did you expect to happen?

In my case this would result in the buffer pick letter displayed with two spaces between it and the buffer name to keep the width of each buffer the same.

### Additional Information

...

**Comment by akinsho** [comment]
@HumblePresent I think this plugin is getting very weighed down with innumerable configurations and options making the codebase increasingly hard to work with. This particular option is one I'd rather not expose.

Tbh I'm not sure why nonicons would need more than one space since it should just take as many cells as needed for example multibyte characters so not require extra padding. Could it be how your terminal is handling rendering them

**Comment by HumblePresent** [comment]
@akinsho The icons themselves are still rendered in two cells like glyphs from other icon or patched fonts. I have added an extra third cell of space because the glyphs from nonicons render a bit larger within those two cells than other fonts. It just keeps the icon from appearing too close to the adjacent text. That said I totally understand your desire to keep the number of configuration parameters down and not expose so many small details. This is more of a wish list feature anyway. It's not gonna keep me from using the plugin or anything. Thanks for your consideration though.
