### ISSUE TITLE
[ Question ] Sorting buffers 

### ISSUE THREAD

**Issue by Chaitanyabsprip** [akinsho/bufferline.nvim#193]
How can I sort the buffers in the order in which they were opened? 

Also, with mappings being deprecated, is there a way I can have the same functionality?

**Comment by akinsho** [comment]
@Chaitanyabsprip the warning if mappings is setup points to the correct part of the README to replicate this functionality, i.e. `BufferLineGotoBuffer <number>`, please read that section in the README for mapping information.

Regarding sorting buffers by when they were opened this was addressed in https://github.com/akinsho/bufferline.nvim/issues/135, essentially the best solution is the default which sorts by buffer id.

**Comment by Chaitanyabsprip** [comment]
Thank you for answering!
