### ISSUE TITLE
[Feature request] add tab only mode

### ISSUE THREAD

**Issue by VVKot** [akinsho/bufferline.nvim#195]
Is there any way to just get fancy formatting, LSP indicators, etc for tabs? I often have a lot of buffers opened, which works great with `hidden` (compared to how other editors do it) - so displaying all of those buffers as tabs is not something I want to do.

**Comment by VVKot** [comment]
@akinsho ?

**Comment by akinsho** [comment]
@VVKot I get this question a surprising amount, weekly at least. My personal workflow that inspired this plugin is entirely based around what files (buffers) I have open, I have always used tabs the way that the help docs describe them

> A tab page holds one or more windows.  You can easily switch between tab
pages, so that you have several collections of windows to work on different
things

Given the description above i.e. a tab being a set of windows I don't really know how a lot of this plugin's functionality would map to a tab, for example if a tab has 3 windows open inside it what lsp indicators should show, which window's buffer's name is shown in the tab, how do actions like click command work for tabs.

I'm really not clear on why or how people want this to work with tabs, since tabs are just window collections.

Anyway that's a longer answer than I usually give, basically it isn't a workflow I understand or use personally, so I don't really have any personal incentive to implement this. If someone else could explain how it would work and most importantly wanted to work on it themselves I would help guide the PR but am not likely to add this myself.

**Comment by VVKot** [comment]
@akinsho sure, completely understand your motivation and thought process here. I can consider contributing this when/if I am sufficiently inclined. Answering your specific questions:

1. Name/LSP indicator value - for last active window in the tab, as it currently works.
2. Actions on tabs - same, "close tab" icon/middle click closes the tab itself, left click selects the tab.

**Comment by MaiLunJiye** [comment]
> @akinsho sure, completely understand your motivation and thought process here. I can consider contributing this when/if I am sufficiently inclined. Answering your specific questions:
> 
> 1. Name/LSP indicator value - for last active window in the tab, as it currently works.
> 2. Actions on tabs - same, "close tab" icon/middle click closes the tab itself, left click selects the tab.

It can work like airline, display all buffers if there are only one tab. 
When it comes to more tab, display the last buffer of each tab, and click it to switch to the tab rather than the buffer.

**Comment by LandonSchropp** [comment]
@akinsho Would it be possible for you to post a summary of the high-level steps you'd see as being necessary to support tabs? Being new to Lua, I'm not sure I'm up to the challenge of adding this feature, but I'd like to check it out and see if it's feasible.

Is there an abstraction between the bufferline TUI and the results of the actions?

**Comment by akinsho** [comment]
@LandonSchropp so quite a bit of the how it should work will need to be determined by the person who picks this up, as I don't use a tab based workflow a lot of the questions about how the existing functionality of this plugin would map to tabs is unclear to me, does deduplication work, what is the underlying data for a tab, how do the various actions map to tabs etc.

Ignoring all of those more "philosophical" questions, I recently refactored this plugin to add in the idea of a higher level abstraction called a `TabView` which is a class that has to implement some basic methods. A `Buffer` in this plugin is now just a type of `TabView` so eventually there can be a TabPageView that also implements the necessary mechanisms to be rendered, there are quite a few helpers, but it isn't entirely abstracted away but looking at how buffers are rendered would get anyone a bunch of the way there.

In terms of how to potentially approach, I would suggest factoring out the Buffer specific logic in the main render function into a separate function that can be called based on an option.
https://github.com/akinsho/bufferline.nvim/blob/58aeda605af5b107a25ee89d3fc7b8ba333d0767/lua/bufferline.lua#L1038-L1063 
This way an option can be created that calls the buffer list creating logic or some new tab based list logic. In the first instance, I wouldn't worry about replicating the exact functionality of buffers and just focus on getting tabs into some sane structure and showing those. I think if a list of tabs can be shown in place of buffers, that's a good enough first step.

To be honest, one thing I'm still missing is a clear sense of what the workflow and desired behaviour for a tab based mode would be, so I'm not entirely clear on what to recommend. What are people who have tab based workflows doing? What sort of behaviour should the tabline have if it's based on tabs 🤷🏿‍♂️

**Comment by LandonSchropp** [comment]
@akinsho Thanks for the reply! I'll give this a shot. No promises though. 🙂

In terms of behavior, I think defaulting to the exact same behavior as tabline makes sense. That component has been in use for years and seems pretty solid. I agree with all of @VVKot's suggestions on how this should work. The feature @MaiLunJiye sounds interesting, but I'd hold off on adding it and just get things working like tabline for now.

The `TabView` abstraction you created sounds exactly like what I was thinking of. I'm imagining this functionality would be broken into two files:

* `bufferline/buffers.lua`
* `bufferline/tabpages.lua`

These files could contain all of the specific logic for each type of tab, and the resulting logic could be plugged into `TabView`. Then `bufferline.lua` is just feeding the correct config based on the settings. Does that sound right to you? Also, would it make sense to you to drop the current tabpage behavior and focus exclusively on rendering buffers _or_ tabpages?

I'll get starting on extracting the portion of the code you pointed out. I think that's a good place to give this a shot, and it makes sense to me that this would be broken up over multiple PRs with refactors coming first.
