### ISSUE TITLE
Set tab width purely relatively to the file name

### ISSUE THREAD

**Issue by antaxiom** [akinsho/bufferline.nvim#196]
Hello, this may be a dumb issue, but I don't know any way to define tab with purely by padding around the tab name and adding a max limit, all tabs are the same width. Barbar.nvim adjusted the length depending the file name. Short file names end up with wasted space like so:
![image](https://user-images.githubusercontent.com/40070530/130503048-3ca6b4d5-48e2-4b8e-b954-3b8b6b8d4f0d.png)

I may be missing a config option, please advise!

**Comment by akinsho** [comment]
@antaxiom there are 2 options that can control the size of a tab
```lua
tab_size = 18, <--- The size that a tab should be
max_name_length = 18, <--- the max size of a tab after which they will be truncated.
enforce_regular_tabs = false, <--- will prevent tabs from growing beyond the max
```

The padding in this plugin is different to barbar.nvim by conscious choice we very briefly discussed this a very long time ago myself and the barbar author who suggested I adopt the same style, but I *strongly* dislike inconsistency of tab sizes. The aesthetic this plugin aspires to is similar to gui editors or centaur tabs, all of which have consistently sized tabs.

**Comment by antaxiom** [comment]
I see, no problem, I didn't fully realize the difference between tab_suze and max_name_length. 
Thanks!

**Comment by piersolenski** [comment]
<img width="391" alt="CleanShot 2023-10-25 at 19 42 10@2x" src="https://github.com/akinsho/bufferline.nvim/assets/1285419/7f90adfa-6022-4f0e-82a3-22b2a18455ff">

Why is there more padding on the right side of the tab than on the left when using these options?

**Comment by slekup** [comment]
I'd also like to know why, setting the `tab_size` to 0 only seems to affect the left side.

![image](https://github.com/akinsho/bufferline.nvim/assets/74949101/3fa98b7b-9ad3-479d-88b9-6105356626f4)
