### ISSUE TITLE
[Feature Request]: Hidden depends on filetype

### ISSUE THREAD

**Issue by Augists** [akinsho/bufferline.nvim#204]
### What happened?

I use nvim-dashboard and telescope
and I set `always_show_bufferline` to false
If I open telescope and it will show the bufferline in black
which does not match my color scheme used in neovim

### What did you expect to happen?

auto hide bufferline in the filetype `TelescopePrompt`

### Additional Information

...

**Comment by akinsho** [comment]
Going to close this out since I’m not a fan of hiding or showing the tabline based on filetype and this can be done using an appropriate autocommand in the users config
