### ISSUE TITLE
Change command for close_icon

### ISSUE THREAD

**Issue by siduck76** [akinsho/bufferline.nvim#208]
Hi @akinsho , how do I change the command for close_icon? I mean this icon on the top right 
![image](https://user-images.githubusercontent.com/59060246/131286817-f42cb550-9a7f-40b4-9f5c-e348b8634cbb.png)

**Comment by siduck76** [comment]
I have tried setting close_command but that works for the buffer's close icon

**Comment by akinsho** [comment]
@siduck76 that button is there *specifically* for interacting with an most importantly closing *tabs* it isn't for anything else and doesn't do anything else. It is currently the only way to close tabs so I won't can't change it's functionality. If you don't use the tab indicators you might as well disable it and forget about it.

**Comment by siduck76** [comment]
> @siduck76 that button is there _specifically_ for closing _tabs_ it isn't for anything else and doesn't do anything else. It is currently the only way to close tabs so I won't can't change it's functionality. If you don't use the tab indicators you might as well disable it and forget about it.

oh shoot I didnt know about that , sorry! I thought that button was for closing buffers lul , dumb me xD

**Comment by siduck76** [comment]
I have tried using 
```
close_icon = "%@MyFunc@%X",
``` 
But it takes more space idk how

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/131476052-861d4cd2-3f6e-401c-87c3-d73c01e8f01a.png)
(5 buffers)

where as just using the default close_icon 

![image](https://user-images.githubusercontent.com/59060246/131476124-0b44f763-95f6-4ddd-b18a-25b438563e14.png)

(5 buffers)

**Comment by akinsho** [comment]
Yeah I'm not sure how the handling of the icon is done off the top of my head but it already has click syntax so you adding another will actually not work/break it e.g. it already has somthing like
`%@close@<Icon>` so you adding another `@func@` will just duplicate them

**Comment by siduck76** [comment]
> %@close@<Icon>

thanks this worked :'
