### ISSUE TITLE
[Feature request]: a simple command to close current buffer

### ISSUE THREAD

**Issue by aspeddro** [akinsho/bufferline.nvim#215]
### What happened?

I tested the following commands:

`:BufferLinePickClose`
`:BufferLinePick`

Both not close the buffer. The plugin [barbar.nvim](https://github.com/romgrk/barbar.nvim#lua) provide some simple intuitive functions to handler the buffers.

How i can close the current buffer?

running `:BufferLinePickClose` the icon only change color
![image](https://user-images.githubusercontent.com/16160544/132112731-98e7638d-2bc2-448f-a73b-45800412d78e.png)

### What did you expect to happen?

the buffer close, like a tab

### Additional Information

NVIM v0.6.0-dev+43-g02bf251bb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by akinsho** [comment]
Hi @aspeddro,

so `BufferLinePickClose` works by showing you the a character you can press to trigger a closing the specified buffer with `bdelete` in the example you show above as you can see in the image the letter b appears. If you *then* press b the buffer in question will be deleted.

Alternatively you can press the close icon. 

Regarding commands to close a buffer, vim by default provides many commands for interacting with buffers such as `bdelete` or `bwipeout` as such I don't believe this plugins needs to provide it's own additional functionality.

Barbar as far as I recall more or less includes a big chunk of *another plugin* called vim-bbye inside it's own code base to provide some extra commands to handle edge cases a lot of vim users don't like such as that the `bdelete` command will mess with a user's window layout.

As far as I'm concerned buffer management should be done by a separate plugin and this plugin should only deal with UI and commands and functionality that relate *directly* to what it does i.e. showing a user their buffers.

You can easily find a bunch of plugins that add this type of functionality/alternatives to bd such as https://github.com/famiu/bufdelete.nvim

**Comment by aspeddro** [comment]
Thank you @akinsho
