### ISSUE TITLE
[Bug]: Bufferline colors don't reload

### ISSUE THREAD

**Issue by Shatur** [akinsho/bufferline.nvim#218]
### What happened?

After efb9a699d2132a1ace759dbb1405cf6f369c4adc, the colors do not change when the theme or background is changed.

### What did you expect to happen?

I would expect the colors to update when changing the colorscheme or background.

### commit

efb9a699d2132a1ace759dbb1405cf6f369c4adc

**Comment by Shatur** [comment]
Thank you! It fixed the issue, but now after theme change values from `highlights` table that passed to `setup` doesn't respected.

**Comment by akinsho** [comment]
Ok I'll have a look when next I'm able.

**Comment by akinsho** [comment]
This should be fixed now, can you confirm if it is? if so I'll close this out

**Comment by Shatur** [comment]
Yes, works perfectly now, thank you!
