### ISSUE TITLE
[Bug]: NeoVim-qt on Windows Styling

### ISSUE THREAD

**Issue by atomiccity** [akinsho/bufferline.nvim#219]
### What happened?

The tabs appear to be unstyled on NeoVim-qt on Windows 10.  I have vim.opt.termguicolors set to true.  Is this plugin compatible with NeoVim-qt?  I'm still pretty new to NeoVim and appreciate the help.

### What did you expect to happen?

Expected behaviour is that the tabs appear styled like in the screenshots.

### Additional Information

...

**Comment by atomiccity** [comment]
Here is a screenshot.

![image](https://user-images.githubusercontent.com/28820002/132937835-31969468-7575-4c4b-841d-0a781de149c1.png)

**Comment by akinsho** [comment]
Hi @atomiccity, so QT is a neovim GUI whereas this plugin is aimed at neovim in the terminal so it's styling doesn't apply to the tabs in QT. there might be a way to disable it's and use the terminal ones but I'm not familiar with QT so can't help

**Comment by atomiccity** [comment]
Ahh, I understand. Thank you for the help, @akinsho.  This is a wonderful looking plugin!
