### ISSUE TITLE
[Bug]: offset not setting correcltly for nvim-tree.lua

### ISSUE THREAD

**Issue by iRealistiX** [akinsho/bufferline.nvim#224]
### What happened?

The bufferline is not offset correctly

### What did you expect to happen?

It should offset properly, without a missing space

### Additional Information

Here's the screenshot describing the offset issue
![21-09-13_16h:58](https://user-images.githubusercontent.com/67875888/133107882-04b3e5fc-44bb-4d94-96c5-05d1514a89c2.png)

It misses 1 space of offset

**Comment by akinsho** [comment]
@iRealistiX I believe this isn't a bug but an issue with your setting for `VertSplit` you have likely got `fillchars` for `vertsplit` set to an empty character and highlights set to something, so it appears like that. That's more an issue with user configuration than this plugin since it cannot and doesn't change a user's fillchars or vertsplit which is well outside the scope of this plugin

**Comment by iRealistiX** [comment]
I got a "hacky" way to fix this is that the color of the vertsplit of the filetree matches the color of the vertsplit of the `Normal` hi group, but then the statuslines at the bottom breaks
![21-09-13_17h:08](https://user-images.githubusercontent.com/67875888/133109137-e2138c99-2608-4693-b2bf-0683a933fae5.png)

**Comment by iRealistiX** [comment]
Update: the vertsplit causing this issue is the filetree vertsplit, named `NvimTreeVertSplit`, going a bit in the Normal window by clearing the highlight on it
![21-09-13_17h:10](https://user-images.githubusercontent.com/67875888/133109481-ade844de-3749-403e-ba38-ec6dc973ef3e.png)

**Comment by akinsho** [comment]
Gonna close this out since you've found a way around the issue. In either case this plugin can't solve this particular problem automatically for the user since it's entirely dependent on a user's settings

**Comment by iRealistiX** [comment]
**UPDATE**: The real error in the story was the `indicator_selected` highlight issue in the config.
