### ISSUE TITLE
[Bug]: Color highlight not render correctly when unique buffer name

### ISSUE THREAD

**Issue by eeeXun** [akinsho/bufferline.nvim#227]
### What happened?

When unique buffer name triggered, the color doesn't consist with my setting of buffer_select.
![](https://i.imgur.com/0pG3lMK.png)

### What did you expect to happen?

I set background color of buffer_select to be gray, and foreground color to be black.
And this is normal case that without triggering unique buffer name
![](https://i.imgur.com/a0hw1un.png)

### Additional Information

Here is my bufferline setting.

```lua
require'bufferline'.setup{
    options = {
        numbers = function(opts)
            return string.format('%s·', opts.raise(opts.id))
        end,
        buffer_close_icon = "",
        show_buffer_icons = false,
        show_close_icon = false,
        indicator_icon = "",
        separator_style = {"", ""},
    },
    highlights = {
        buffer_selected = {
            guifg = "#282828",
            guibg = "#a89984",
            gui = "bold"
        },
        close_button = {
            guifg = "#cc241d",
        },
        close_button_selected = {
            guifg = "#cc241d",
            guibg = "#a89984",
        },
        close_button_visible = {
            guifg = "#cc241d",
        },
        modified_selected = {
            guibg = "#a89984",
        },
    }
}
```

**Comment by akinsho** [comment]
@eeeXun sorry I'm on mobile atm so can't answer in detail. In short this isn't a bug there is a separate highlight setting for duplicate buffers. Please check the help docs you need to use the `duplicate_*` highlight fields to change those colours

**Comment by eeeXun** [comment]
Yes, I didn't notice that option. Thanks a lot.
