### ISSUE TITLE
[documentation] how to make another status line like bufferline

### ISSUE THREAD

**Issue by alexzanderr** [akinsho/bufferline.nvim#228]
this is not an issue.
im just curious about how to create another status line just like bufferline and print it in neovim, but keep the bufferline just in its place.

i dont know if the bufferline.nvim is another vim default status line just enhanced with colors.

can you guys provide me with some docs, advices on how to create another buffer line ?

what i trully want:
- to make another buffer line; 
- to keep the vim default status line and bufferline.nvim
- to print my new bufferline just below the bufferline.nvim (if its possible)

the idea of this request is to create a very useful plugin that is using `treesitter.`
i have this snippet
```lua
	print(require("nvim-treesitter").statusline({
		indicator_size = 200,
		separator = " ❱ ",
		transform_fn = function(line) return line:gsub('%s*[%[%(%{]*%s*$', '') end,
		-- type_patterns = {'module', 'class', 'function', 'method', 'variable', 'comment', 'number', 'import'}
		-- module is wrong, it prints the file comment in the script
		type_patterns = {'class', 'function', 'method', 'import', 'for', 'if', 'while', 'variable', 'comment'}
	}))
```
it prints the current location in current file, based on tree sitter.
output
![image](https://user-images.githubusercontent.com/54772464/134703987-8ab06201-fa4b-4dd9-bd0c-09bd56178276.png)
but this is too long to fit in the vim statusline, so i want to make a new one and keep everything.

i would by very grateful is you guys can help me.

**Comment by akinsho** [comment]
Hi @alexzanderr, tbh I don't think I follow that this issue is about. Bufferline is *not* a statusline plugin. The statusline is what appears on the bottom of your nvim, bufferline instead hijacks the tabline. I also really don't understand the request or how I can help bufferline's code is open in this repo so you can easily see how it works. If you are interested in the more basic statusline creation you can use vim's help by typing `:help status-line`

**Comment by akinsho** [comment]
Bufferline is not related to any default status line and is mostly separate/unlike anything nvim provides by default

**Comment by akinsho** [comment]
I think what you probably want is to look into creating a floating window and positioning it just under the bufferline/tabline rather than re-using the tabline or status line as there can only be 1 single line one of those

**Comment by alexzanderr** [comment]
`:help status-line` is useless.

> Bufferline is not related to any default status line and is mostly separate/unlike anything nvim provides by default

yea its not, because its not a status-line, is a `tabline` and im guessing that its relying the default vim tabline. bufferline is just the vim tabline with enhanced colors and unicode. is that correct?

> I think what you probably want is to look into creating a floating window and positioning it just under the bufferline/tabline rather than re-using the tabline or status line as there can only be 1 single line one of those

that is exactly what i want to do. since vim has only status-line and tab-line, which are already used.

**Comment by alexzanderr** [comment]
yes, i've done it.
![image](https://user-images.githubusercontent.com/54772464/134786921-f087535b-c85a-4e1c-a8d4-b24637596918.png)

thanks for the idea.

**Comment by akinsho** [comment]
Looks cool 👍🏿

**Comment by alexzanderr** [comment]
yes, but the cursor overlays it.

**Comment by alexzanderr** [comment]
when its pass the end of file its fine
![image](https://user-images.githubusercontent.com/54772464/134787029-c1e39ea7-2b5d-466d-b651-6fd9afa36f4c.png)

but when in not at the end of file, the last line in the visible vim buffer is not visible and the cursor can go over it. so the cursor can get over the floating window. and thats my problem.
![image](https://user-images.githubusercontent.com/54772464/134787046-ef5a2cf4-d51a-4d4f-a1b2-cd6cc3e879f4.png)

do you have any ideas?

**Comment by akinsho** [comment]
I don't think there's anyway to prevent that because the cursor is underneath the floating window, and it doesn't know about the floating window that is a layer above it, you could try some complex hacks to manipulate the cursor, but I think that's a bad idea. You might want to add a `scrolloff` see `:help scrolloff` as mandatory config options, since it can prevent the cursor from ever being at the bottom of the file.

**Comment by alexzanderr** [comment]
yes, `set scrolloff=1` will fix the issue. except the last line. when you are on the last line of the file, this will not work anymore. but in the rest is very good.

thank you so much for help!

**Comment by alexzanderr** [comment]
you just made someone happy.
