### ISSUE TITLE
[question] how to change the background color of offset space

### ISSUE THREAD

**Issue by alexzanderr** [akinsho/bufferline.nvim#233]
hello, i have bufferline configured and its working very well.
i just want to change the background color of offset space

![image](https://user-images.githubusercontent.com/54772464/134961008-66394169-ea9a-4323-86bb-432a95631b04.png)
(where it says NvimTree)

i want to make the background color `black` to match the bufferline blackground color which is black.

my offset options in bufferline setup:
```lua
        offsets = {
            {
                filetype = "NvimTree",
                -- here the photo is outdated, rn its says cwd folder name
                text = function ()
                	return vim.fn.substitute(vim.fn.getcwd(), '^.*/', '', '')
                end,
                text_align = "center",
                highlight = "Directory",
            },
        },
```

**Comment by akinsho** [comment]
@alexzanderr you need to pass a highlight group to the offset that has a black background. In your case, you passed `Directory` but that doesn't have a black background. You needed to create a highlight group and pass the name in here. Please see `:help :highlight` for details on creating a highlight group

**Comment by alexzanderr** [comment]
wow. thanks. it worked.
![image](https://user-images.githubusercontent.com/54772464/134966780-004a710b-38e7-4cc6-b566-382dcc3ab9b2.png)
with this
`vim.cmd("hi OffsetLine ctermbg=black guibg=#ffcb3d")`

**Comment by alexzanderr** [comment]
ups. wait. where can i find the hex color of bufferline background ? (i now its black, but its not pure black)

**Comment by akinsho** [comment]
you are probably looking for `BufferlineFill` or something

**Comment by alexzanderr** [comment]
![image](https://user-images.githubusercontent.com/54772464/134983417-c3bf7c6f-c0da-4bdc-b74a-cdc9de7a10a3.png)

that is correct. thank you so much

hey, can you add me on discord? (`alexzander#5442`) in order to spam less here with issues if i have more questions, please.

**Comment by akinsho** [comment]
I don't use discord sorry
