### ISSUE TITLE
[Bug]: function(buf) .... buf.path isn't consistent (as of the groups feature)

### ISSUE THREAD

**Issue by joehannes** [akinsho/bufferline.nvim#235]
### What happened?

The issue is that...
I'd like to group files based on their directory that's part of the path (buf.path ... in example buf.filename used)

### What did you expect to happen?

Expected behaviour grouping works based on files dir

### Additional Information

... instead initially (on nvim startup) it seems filepaths are full / not abbreviated, but once i switch buffers the filepaths in buf.path seem to get abbrev until they are the same as buf.filename ... only when two files are named the same (e.g. index.js) the shortpath thingy gets added to the buf.path again ....
I don't really understand what's happening, anyway, can't use buf.path to write my grouping behavior-function, but don't want to group on filename but on path ... help??

**Comment by akinsho** [comment]
@joehannes it's likely nvim is changing the path of the buffer based on how they are opened and the current cwd, the plugin just gets the full buffer name and runs `fnamemodify(filename, ':t')` to get the path so we shouldn't be truncating it.

In any case you can just format the path yourself doing `vim.fn.fnamemodify(buf.path, ':p:h')` which should give the full path.

Just to be clear return a directory name from function *will not* cause all he buffers in that directory to be grouped. Grouping works by specifying the name of the group and the `fn` is a function that check is a buffer in the list matches it.

So if you wanted to group by a specific directory you could do `vim.fn.fnamemodify(buf.path, ':p:h'):match(directory_name) ~= nil` and that would put the matching buffers into this directory whose name you have specified ahead of time

**Comment by akinsho** [comment]
@joehannes if you check the help for `fnamemodify` you'll see a very similar expansion
```
 fnamemodify({fname}, {mods})				*fnamemodify()*
		Modify file name {fname} according to {mods}.  {mods} is a
		string of characters like it is used for file names on the
		command line.  See |filename-modifiers|.
		Example: >
			:echo fnamemodify("main.c", ":p:h")
<		results in: >
			/home/mool/vim/vim/src
<		If {mods} is empty then {fname} is returned.
		Note: Environment variables don't work in {fname}, use
		|expand()| first then.
```
I don't know how the internals work but I guess it uses the partial name to match against a buffer and then resolve the name from there. There is no function to pass buffer objects to since are objects I created they can't go into anything. This plugin uses fnamemodify extensively and it largely works.

**Comment by joehannes** [comment]
wow, I find that superstrange... must be based on some workding_directory-thingy, because how would it distinguish index.js from index.js??? well ... I'll give it  a shot!!! awesome!!!

**Comment by akinsho** [comment]
Gonna close this out now, let me know if there's still something that needs doing here
