### ISSUE TITLE
(QUESTION) Is there a control option for `BufferLinePick` sigil's color?

### ISSUE THREAD

**Issue by ofk-enterprise-account** [akinsho/bufferline.nvim#245]
For a while, when issuing `BufferLinePick` the sigils denoting the buffers were in red. After a recent update, they're in white.
I'm guessing an option was added/triggered/removed to set the color of the sigils?

If so, I can't find it in the docs.

Thanks.

**Comment by akinsho** [comment]
This should now be fixed @ofk-enterprise-account

**Comment by ofk-enterprise-account** [comment]
Yes, it worked!
Thank you very much!
