### ISSUE TITLE
'number_style' will be deprecated problem

### ISSUE THREAD

**Issue by CrazyGriferman** [akinsho/bufferline.nvim#247]
I set the number to "numbers = "none" | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string," as described in README.md (there is a "function" ), but it constantly shows these warnings when I open vim:

> 'number_style' will be deprecated:
> 'number _style' will be deprecated: please specify 'numbers' as a function > instead. See :h bufferline-numbers.

I also add the function which is listed in help guide:
```
numbers = function(opts)
	return string.format('%s·%s', opts.rasie(opts.id),
	opts.lower(opts.ordinal))
end
```

But it still didn't work.
**How can I fix that?**

this is my configuration file:
```
require "bufferline".setup {
	options = {
		numbers = function(opts)
			return string.format('%s·%s', opts.rasie(opts.id),
			opts.lower(opts.ordinal))
		end,
		number_style = "superscript",
		offsets = {{filetype = "NvimTree", text = "File Explorer", text_align = "center", padding = 1}},
		buffer_close_icon = "",
		modified_icon = "",
		close_icon = "",
		left_trunc_marker = "",
		right_trunc_marker = "",
		max_name_length = 14,
		max_prefix_length = 13,
		tab_size = 20,
		show_tab_indicators = true,
		diagnostics = "nvim_lsp",
		enforce_regular_tabs = false,
		view = "multiwindow",
		show_buffer_close_icons = true,
		always_show_bufferline = false,
		separator_style = "thin",
		mappings = "true",
		custom_filter = function(buf_number)
			if vim.fn.bufname(buf_number) ~= "dashboard" then
				return true
			end
		end,
	}
}
```

**Comment by CrazyGriferman** [comment]
I just deleted 'numbers' and 'number_style' and suddenly the warning disappeared. I didn't know what happened but it fixed my issue.

**Comment by akinsho** [comment]
@CrazyGriferman the `numbers_style` option is deprecated please don't use it, or you will see that error, instead you should use `numbers`.

**Comment by CrazyGriferman** [comment]
Thanks! I solved the problem.
