### ISSUE TITLE
[Feature request] Temporary buffer and previous buffer on close

### ISSUE THREAD

**Issue by MikaelElkiaer** [akinsho/bufferline.nvim#254]
I was wondering whether these two features were feasible? First off is probably whether they fit in here, or outside of this plugin.

**Temporary buffer** A buffer that closes when it loses focus. Useful for buffers which display some output that becomes obsolete after viewing it.

**Previous buffer on close** Currently, when closing a buffer focus is switched to the first buffer. This is a bit weird default if you ask me, I would've thought that you would go to the previously active buffer.
E.g. if you have 3 buffers A, B, C and have focus on B. If you then go to C and close it, focus shifts to A instead of B.

**Comment by akinsho** [comment]
Hi @MikaelElkiaer,

so the first concept you describe is a "scratch buffer" which is a concept that exists in vim that predates this plugin, there are quite a few existing plugins that do this and vim has some settings to help a user do this. As far as it relates to this plugin I think this is out of scope.

Regarding returning to the previous buffer similar to previous suggestion essentially this plugin's main mission/focus/raison d'etre is to provide *UI* for open buffers, it draw a hard line on buffer management i.e. dealing with opening and closing buffers etc. You can manage going back to the previous buffer by using one of the many buffer close like `nvim-bufdel` or `vim-bbye` or `vim-sayonara` all of which tend to deal with things like returning to the buffer you came from.

**Comment by MikaelElkiaer** [comment]
That was an awesome rundown, thank you very much. I will look into it. :)
