### ISSUE TITLE
[Bug]: Error Default config

### ISSUE THREAD

**Issue by 1m-N00b** [akinsho/bufferline.nvim#255]
### What happened?

The [config of deault](https://github.com/akinsho/bufferline.nvim#configuration) gives me the following [error](https://imgur.com/sA3oxvK). I'm not familiar with lua, so I can't see the syntax error.

### What did you expect to happen?

I'm guessing that the error is occurring within the option, 
because the
```
lua << EOF
require("bufferline").setup{}
EOF
```
without the option does not show the error.

**Comment by akinsho** [comment]
@1m-N00b the default config is not for copy pasting please do not copy past it. Please read through the configuration options and only add or change what you need. By default, all the options in the default config are already set up, so you do not need to add them there anyway

**Comment by 1m-N00b** [comment]
thx i solved and i asked 1 more question.
sidebar offset didnt support coc-explorer!?

**Comment by akinsho** [comment]
@1m-N00b if `coc-explorer` has a filetype then it should work. I don't use this plugin so I don't know what it is you will have to find it's filetype yourself. It should work unless that plugins dynamically changes the filetype or messes with the tabline which it shouldn't

**Comment by 1m-N00b** [comment]
I have one more question: If I write coc-explorer and vista, it doesn't work.

```
lua << EOF
require('bufferline').setup {
  options = {
    diagnostics = "coc",
    offsets = {{filetype = "coc-explorer", text = "File Explorer", text_align = "left"}},
    offsets = {{filetype = "vista", text = "Tags", text_align = "right"}},
  }
}
EOF
```

**Comment by akinsho** [comment]
@1m-N00b this configuration is not correct, `offsets` should be a list not 2 duplicate keys as you have there e.g.
```lua
offsets = {
 {filetype = "type-1", ...},
 {filetype = "type-2", ...},
}
```
If you are new to lua's syntax, I highly recommend reading https://github.com/nanotee/nvim-lua-guide and then re-reading the README in detail. Unfortunately, I can't really help debug every single user's configuration for them since this is quite time-consuming and there are other issues I have to respond to in different projects

**Comment by 1m-N00b** [comment]
I've solved it.
I'll try to touch on the basic lua syntax.
