### ISSUE TITLE
[Feature request]: Open last closed buffers

### ISSUE THREAD

**Issue by JavierPoduje** [akinsho/bufferline.nvim#256]
Hi :mage_man:,

It would be great that after a buffer is closed, we could reopen this buffer with a Bufferline command. If more than one file has been closed during a session, this functionality would reopen the closed buffers starting from the most recent one.

I imagine the implementation with a stack that keeps track of the files that have been closed, kind of like a _ctrl-z_ | _ctrl-y_ behavior.

Thanks! :man_cartwheeling:

**Comment by akinsho** [comment]
Hi @JavierPoduje, so I probably need to make this clearer somewhere near the top of the README, but this plugin is designed to provide UI features *not buffer management* it's not intended to manage what buffers used to be open or trying to open the most recent or keeping track of things. That should be the responsibility of some other plugin. This plugin is *just about seeing* what is open potentially in different/interesting ways.

FWIW vim already has the notion of an `alternate` buffer which is the last buffer a user was in, you can open the alternate buffer using `:b#` the `#` represents the alternate buffer. There are other aliases for other buffer types as well as opening by name and number.

**Comment by JavierPoduje** [comment]
Hi @akinsho. No problem and thanks for your answer! I'll close the issue :v:.
