### ISSUE TITLE
[Feature request]: Align offsets with more than 1 sidebar

### ISSUE THREAD

**Issue by lcrockett** [akinsho/bufferline.nvim#259]
### What happened?

I'm using `offets` so ensure the bufferline doesn't appear above any sidebars I might pop out. This works as intended. However, i've noticed that when having more then 1 sidebar opened the bufferline only offets itself off of the first sidebar. It still appears above the second sidebar. See screenshots and configuration here below. It seems that this behaviour is consistent on both left as well as right sidebars.

![image](https://user-images.githubusercontent.com/58056722/141874628-2bc0cb4b-03ab-4a2b-bfd5-0bd7a6c1125a.jpeg)
![image](https://user-images.githubusercontent.com/58056722/141874635-3fd79903-aa2a-4d72-93d8-23dfd4c6084c.jpeg)

```lua
require('bufferline').setup({
  options = {
    diagnostics = 'nvim_lsp',
    diagnostics_indicator = function(_, _, _, ctx)
      if ctx.buffer:current() then
        return ''
      end

      return ' '
    end,
    indicator_icon = '▎',
    max_name_length = 40,
    numbers = function(opts)
      return string.format('%s. ', opts.ordinal)
    end,
    offsets = {
      { filetype = 'DiffviewFiles', text = 'Diffview Files' },
      { filetype = 'Mundo', text = 'Mundo History' },
      { filetype = 'NeogitStatus', text = 'Neogit Status' },
      { filetype = 'NvimTree', text = 'Nvim Tree' },
      { filetype = 'Outline', text = 'Symbols Outline' },
      { filetype = 'SidebarNvim', text = 'Sidebar' },
      { filetype = 'fugitiveblame', text = 'Fugitive Blame' },
      { filetype = 'minimap', text = 'Minimap' },
      { filetype = 'spectre_panel', text = 'Spectre' },
      { filetype = 'tabman', text = 'Tab Manager' },
      { filetype = 'tagbar', text = 'Tagbar' },
    },
    show_buffer_close_icons = false,
    show_close_icon = false,
    separator_style = { '', '' }
  }
})
```

### What did you expect to happen?

I would expect the bufferline to offset itself from any sidebars, instead of only the first one.

### Additional Information

NVIM v0.6.0-dev+579-g2f37ffb71 @ Ubuntu 20.04 LTS
NVIM v0.6.0-dev+579-g2f37ffb71 @ macOS Big Sur

Sidenote: It looks like the bufferline line creeps up a bit over the window border between the sidebar and the opened buffer, it shows on the screenshots. This is of course a different issue but not stringent enough to open up an issue for at the moment.

**Comment by akinsho** [comment]
Hi @lcrockett, this is intentional, the way `offsets` work requires reading out neovim's layout as a nested list of windows and so only a few permutations work. The offset specifically only works for one panel on the left or right, rather than off setting as many panels on either side. I was very reluctant to add this functionality when first requested since I envisioned a lot of scope creep and growing complexity, so generally don't/won't accommodate all use cases.

Tbh it doesn't seem like a common usecase to have two panels open side by side/ the main use case of this functionality is more or less opening a file explorer on one side rather than trying to handle as many cases as possible which doesn't really do.

**Comment by lcrockett** [comment]
Ah, I wasn't aware that this was intentional. I agree it's not a common use case. I myself usually have 1 sidebar on each end opened and occasionally an additional sidebar on the left, making three in total. So the lack of offsetting a 3rd (or more) sidebar doesn't hurt that much. I'll leave it up to you to keep this feature request open for a rainy afternoon or so.

**Comment by akinsho** [comment]
👍🏿 I think I'll close this out and see if more demand for this ever crops up. I'd rather keep the complexity of the offsets to a minimum and constrain the number of use cases, but maybe I'll change my mind at some other point in the future but would rather not have issues open for prolong periods of time.
