### ISSUE TITLE
[Feature Request] Multi-line bufferline

### ISSUE THREAD

**Issue by rickyelopez** [akinsho/bufferline.nvim#261]
Not sure how much interest there would be in this, but for my part, I often have enough buffers open that this plugin has to move some of them offscreen to be able to show the current buffer (which makes perfect sense). I have a big monitor and it would be nice to be able to have it wrap to multiple lines (ideally, number of lines would be configurable) rather than hiding buffers off screen.

**Comment by akinsho** [comment]
Hi @rickyelopez,

This isn't possible in neovim, the tabline can only occupy one row of the screen. There isn't really anything a plugin can about that.

**Comment by rickyelopez** [comment]
Hey @akinsho,

Well that's unfortunate, thanks anyway!
