### ISSUE TITLE
[Bug]: Tab page is closing when deleting a buffer

### ISSUE THREAD

**Issue by henriquehbr** [akinsho/bufferline.nvim#263]
### What happened?

I have 2 tab pages, whenever i delete a buffer with `bd`, all the buffers on that tab page are deleted, alongisde the tag page itself

### What did you expect to happen?

When deleting a specific buffer, only this buffer should be deleted and the tab page should remain opened alongside the other buffers that were already present on that given tag page

### Additional Information

**neovim:**

```
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
```

**OS:** GNU/Linux (Arch Linux) 5.15.2-arch1-1 x86_64

**dotfiles:** https://github.com/henriquehbr/dots/tree/main/.config/nvim

**Comment by akinsho** [comment]
Hi @henriquehbr I don't think this relates to this plugin as it doesn't add or remove buffers it simply reads them out of vim's state. Can you provide a minimal vimrc that reproduces this problem?

I could be an autocommand or some other plugin causing some interaction

**Comment by akinsho** [comment]
Sorry I also just realised based on how the comment was phrased that there might be a misunderstanding on the behaviour of tabs. A tab will only be open if the **windows** for that tab are still open, not the buffers.

A tab is not aware of buffers so you need to keep the windows open. If you want to keep a tab open. That isn't new or related to this plug in, that's just standard vim behaviour

**Comment by henriquehbr** [comment]
Thanks @akinsho! keeping the window opened prevented the tab page from closing
