### ISSUE TITLE
[Bug]: Error trying to install bufferline 

### ISSUE THREAD

**Issue by kyp0717** [akinsho/bufferline.nvim#264]
### What happened?

E5113: Error while calling lua chunk: ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:1215: attempt to call field 'is_test' (a nil value)         
stack traceback: 

### What did you expect to happen?

Expected behaviour

### Additional Information

...

**Comment by akinsho** [comment]
Hi @kyp0717 I think I saw a similar issue once where a user had barbar also installed which caused a conflict or they had another lua module in their config called bufferline

**Comment by akinsho** [comment]
Any news? Otherwise, I'll close out this issue shortly

**Comment by akinsho** [comment]
Closing this out as there's been no response and this isn't something I believe is an issue with this plugin but in all likelihood some lua module naming conflict
