### ISSUE TITLE
Doesn't change buffer background when info_diagnostic is set

### ISSUE THREAD

**Issue by ErickTucto** [akinsho/bufferline.nvim#265]
I configured so that the buffer has a red background color, but it is not paying attention to the values

![imagen](https://user-images.githubusercontent.com/22831024/142914500-2ec8f6fa-58ee-44b6-953d-bdf46a26b096.png)

**Comment by akinsho** [comment]
@ErickTucto sorry for the late response been very busy for a while, are you still seeing this issue, can you also confirm that if you're using packer you made sure it had compiled everything first

**Comment by ErickTucto** [comment]
It keeps happening, I dont using packer. I cloned your repo. I didn't know I should compile your project

**Comment by akinsho** [comment]
@ErickTucto it doesn't require compilation you should be able to run lua via neovim directly what are you trying to do exactly?

**Comment by akinsho** [comment]
Is this bug specific to diagnostic info or does it reproduce for other types of diagnostics, also is it only visible when the buffer is inactive?

**Comment by ErickTucto** [comment]
yes, only **info** and **inactived buffer**

**Comment by akinsho** [comment]
@ErickTucto so I think I've misunderstood your issue this whole time, below is a screenshot of me setting info backgrounds. 

<img width="829" alt="Screen Shot 2022-04-03 at 15 36 37" src="https://user-images.githubusercontent.com/22454918/161433208-9adf421d-cb9d-4ea7-b0ea-7fc653ab0ab6.png">

This works how I expect it, too, personally. I think the main misunderstanding is with how highlighting works here. Diagnostic highlighting only affects certain parts of a buffer/tab it doesn't and can't highlight the whole tab, you can't make a whole buffer go red if there is an error. If that is what you're trying to do. The way highlighting for tab/statuslines in nvim works means that setting highlights across particular ranges is kind of unwieldy I can't support every approach, unfortunately. If for example we wanted to only highlight the word as red or something then this means highlighting the whole tab isn't possible and vice versa

**Comment by ErickTucto** [comment]
thanks, I update the plugin and I havent error.
