### ISSUE TITLE
How can I close tabs by number ?

### ISSUE THREAD

**Issue by rzksobhy78** [akinsho/bufferline.nvim#266]
In my configuration
I setted numbers 1,2,3...
to go to the tab
I'd like to close tabs the same way
for example i want
<leader>1 to close tab 1
<leader>2 to close tab 2

and I want <C-w> to close current tab
Ty for the great plugin

**Comment by akinsho** [comment]
@rzksobhy78 there is no built in function to do that but you can create your own command for it by copying the example in https://github.com/akinsho/bufferline.nvim#custom-functions. Otherwise you can use `BufferLinePickClose`

**Comment by akinsho** [comment]
Closing since the response covers this
