### ISSUE TITLE
[Bug]: Doesn't work on Gentoo.

### ISSUE THREAD

**Issue by efe3535** [akinsho/bufferline.nvim#273]
### What happened?

Like #260 I get the same error: 
```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...vim/bundle/bufferline.nvim/lua/bufferline/colors.lua:71: attempt to index global 'bit' (a nil value)
stack traceback:
        ...vim/bundle/bufferline.nvim/lua/bufferline/colors.lua:71: in function 'hex'
        ...vim/bundle/bufferline.nvim/lua/bufferline/config.lua:213: in function 'derive_colors'
        ...vim/bundle/bufferline.nvim/lua/bufferline/config.lua:585: in function 'get_defaults'
        ...vim/bundle/bufferline.nvim/lua/bufferline/config.lua:602: in function 'apply'
        ...onfig/nvim/bundle/bufferline.nvim/lua/bufferline.lua:1191: in function '__load'
        [string ":lua"]:1: in main chunk
```

I'm using Gentoo, too. 

### What did you expect to happen?

Work normally.

### Additional Information

These are what I tried:
I tried the solution in #260.
`emerge luajit`

Then, recompiling Neovim.
`emerge neovim`

That didn't work, so I found a USE flag named "luajit". Then, I compiled with it:
`USE="luajit" emerge neovim`

That didn't work too.
### NVim Version
`$ nvim --version`
```
NVIM v0.6.0
Build type: Gentoo
Lua 5.1
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.6.0/work/neovim-0.6.0_build/config -I/var/tmp/portage/app-editors/neovim-0.6.0/work/neovim-0.6.0/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.6.0/work/neovim-0.6.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.6.0/work/neovim-0.6.0_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by akinsho** [comment]
@efe3535 much like the other issue you mentioned the problem here is that your version of luajit does not contain the bit module which is required and should be available if running the correct version  of luajit.

As I mentioned in that issue, this isn't something the plugin can fix since it depends on this module and requires that it is available. I don't know how other Gentoo users have fixed this, but I have heard of other issues with    Gentoo and the correct lua versions.

**Comment by efe3535** [comment]
Oh, I'll look for it then. Thanks.

**Comment by MarmaladeSky** [comment]
@efe3535 
`luajit` isn't a USE fag but a lua target.
```
LUA_SINGLE_TARGET="luajit" emerge -av neovim
``` 
I had the same issue and ^^ works for me.

**Comment by akinsho** [comment]
Thanks for posting @MarmaladeSky 🙌🏿

**Comment by efe3535** [comment]
@MarmaladeSky
![Screenshot_2021-12-13_16-05-45](https://user-images.githubusercontent.com/46342237/145817879-0f01efc5-3c5f-4486-84b7-2c8c55e5e8b3.png)
Works flawlessly, thx so much!
