### ISSUE TITLE
Weird chars randomly appear in bufferline

### ISSUE THREAD

**Issue by rodhash** [akinsho/bufferline.nvim#274]
Hello!

First of all, congrats for this awesome plugin! Really enjoyed it!

I see a weird "issue" happening and couldn't find much reference, not sure whether this happened to someone else and couldn't find other issue reported so I'm raising this one.

My issue:
- Random chars appears in the bufferline sometimes. It doesn't happen very often so it's kind hard to track, but sometimes it happens.

How to reproduce?
- I'm not sure, it's happens very randomly. Sometimes it doesn't happen at all but sometimes it do

Workaround:
- All I need to do is, resizing the terminal or just move/tile it to the right or to the left usually do the trick. It works like a refresh IMO

My setup:
> NVIM v0.6.0
> kitty 0.23.1
> tmux 3.2a

My config:
```vim
require("bufferline").setup{
options = {
        numbers = "none",
        indicator_icon = '',
        buffer_close_icon = '',
        modified_icon = '﫝',
        close_icon = '',
        left_trunc_marker = '',
        right_trunc_marker = '',
        diagnostics = false,
        show_buffer_close_icons = false,
        show_close_icon = false,
        show_tab_indicators = false,
        always_show_bufferline = true,
        diagnostics_update_in_insert = false,
        show_buffer_icons = true,
        show_tab_indicators = true,
        separator_style = "slant", -- works on kitty
        enforce_regular_tabs = false,
        },

          highlights = {
          …
          }
    }


```

Some print screen:

#1 - In the top right we can see some chars that are not supposed to be there
![bufferline_random_chars_1](https://user-images.githubusercontent.com/29671981/145894205-b365358c-73e4-4d17-acd7-4d526dc9f6c7.png)

#2 - In this 2nd screenshot I opened couple extra buffers, and we still have those chars
![bufferline_random_chars_2](https://user-images.githubusercontent.com/29671981/145894329-7e680de2-757a-4e7b-88eb-e8c1c46ec4f6.png)

#3 - After resizing or moving the window (kitty itself), the chars go away and things get back to normal
![bufferline_random_chars_3](https://user-images.githubusercontent.com/29671981/145894759-d454283f-595f-4492-86de-8c0a131685ef.png)

It's a bit annoying sometimes but doesn't affet the plugin itself, everything still works fine.

And a second question if I might:

Is it possible to trim down the "padding" in the buffer / file name? For instance "init.vim", we have quite some whitespace in the left and right side. I disabled the "buffer close icon" but still have quite some space.

Thanks

**Comment by rodhash** [comment]
Oh regarding the buffer name size I think it might be related to #268.

**Comment by akinsho** [comment]
Hi @rodhash,

I'm not really sure what might be causing the issue in the image you've shared. It looks like some characters aren't being rendered correctly for the tab indicators. I can't reproduce on my end and have never seen it before, so I don't have a clue what it might be. There should be a thin `|` character (not that one exactly but a thinner, taller unicode separator character). It could be that your font does not have that character. Can you try with another font and see if it still happens?

Re. the buffer padding as I've mentioned in the issue you linked, I prefer that buffers are consistently sized. If someone wants to contribute a PR for an option that will make each buffer dynamic to the size of content, i.e. inconsistently sized, I'd look over the PR but will personally not implement it myself.

**Comment by rodhash** [comment]
Few days have passed without any issues, it seems stable somehow and I didn't change a thing!

Well I'll keep monitoring and try to find what might be causing this.

Thanks
