### ISSUE TITLE
[Bug]: Bufferline won't close for split after closing it with :q

### ISSUE THREAD

**Issue by fernandofleury** [akinsho/bufferline.nvim#275]
### What happened?

When closing a split (opened via the `lsp_definition()` function), the bufferline will remain open for it (I only have the active bufferline open):

![image](https://user-images.githubusercontent.com/2780941/146014290-79047b3c-9471-4bc6-b8c3-66fcfedf0d64.png)

### What did you expect to happen?

The bufferline should close after I close a split

### Additional Information

...

**Comment by akinsho** [comment]
I'm going to close this out since I think this is a misunderstanding of splits vs buffers rather than a bug in this plugin
