### ISSUE TITLE
Buffer numbers and highlights

### ISSUE THREAD

**Issue by horseinthesky** [akinsho/bufferline.nvim#280]
Hello. Thank you for a great fast and customizable plugin!

I wonder if it is possible to have a separate highlight group for buffer numbers as it is in `barbar`?
![image](https://user-images.githubusercontent.com/19948672/147389002-573210ef-ed07-4646-8ad2-201b564f8bde.png)

I would also like to have `ordinal` number on every buffer but an active one (I use these for fast buffer switching with `gt<bufferN>`). Thus I don't actually need the number of the buffer I'm currently working with.

I've set up a function to print `ordinal` numbers for all buffers but don't know how to skip an active one.
![image](https://user-images.githubusercontent.com/19948672/147389073-88448be6-8321-457f-8c4d-42b81ca54e52.png)

Here is my config
```
require("bufferline").setup {
  options = {
    always_show_bufferline = false,
    show_buffer_icons = false,
    show_buffer_close_icons = false,
    show_close_icon = false,
    modified_icon = "",
    show_tab_indicators = false,
    tab_size = 5,
    -- separator_style = "thin",
    numbers = function(opts)
      return opts.ordinal
    end,
  },
  highlights = {
    indicator_selected = {
      guifg = {
          attribute = "fg",
          highlight = "Type"
      },
      guibg = {
          attribute = "bg",
          highlight = "Type"
      },
    },
    buffer_selected = {
      gui = "NONE",
    },
    pick_selected = {
      gui = "NONE",
    },
  },
}
```

**Comment by akinsho** [comment]
@horseinthesky I'd be happy to help guide a PR for this functionality, except maybe the ordinal behaviour generally I dislike functionality that introduces complexity for very specific use cases/preferences. I think the ordinal behaviour should be consistent rather than adding yet another if statement to accommodate a specific user preference, since this makes things more complex and harder to maintain. You might be able to achieve this yourself by specifying the number option as a function and using the buffer number to check if it is active and if so return an empty string.

If you are willing to make a PR to add the numbers highlight, I can point you to the areas in the code where this can be added

**Comment by horseinthesky** [comment]
> You might be able to achieve this yourself by specifying the number option as a function and using the buffer number to check if it is active and if so return an empty string.

This was the first thing I tried to do. I've spent some time finding the appropriate function in `:help vim.api` but couldn't find anything useful.
The only options I have from bufferline are `function({ ordinal, id, lower, raise })` are not helpful either.
Would be great to have something like `nvim_buf_get_state` or something =)

> If you are willing to make a PR to add the numbers highlight, I can point you to the areas in the code where this can be added

Please do. I can try =)

**Comment by akinsho** [comment]
@horseinthesky regarding determining the buffer's modified state, it's actually fairly straight forward. You can check this by doing `vim.bo[buffer_id].modified` see `:h vim.bo` and `:h modified`

Re. the numbers highlight, this is a straightforward but involves a few steps. I'm still on holiday, so will have to be brief.
1. Add the highlight group to `config.lua` there are already a long list of highlights
2. In `numbers.lua` wrap the number string with the highlight group, each module is passed the context which contains all the required rendering data including the highlights. You should be able to find a field for the numbers highlight which you added in `config.lua` when you inspect the context using `vim.inspect`
3. Wrap the number component, e.g. `context.highlights.number .. component .. '%*'` the last string terminates a highlight group
Sorry this is a little brief, if you look at how other highlights are applied this might give you a clue for anything you are missing. Anyway, won't be free to go into any more detail till I'm back and have free time on my hands

**Comment by horseinthesky** [comment]
> regarding determining the buffer's modified state, it's actually fairly straight forwar

Yeah, but we were talking about the buffer being active, not modified.

> Re. the numbers highlight, this is a straightforward but involves a few steps. I'm still on holiday, so will have to be brief.

Thanks. Will look through it on holiday.

**Comment by akinsho** [comment]
@horseinthesky sorry getting a deluge of issues since everyone has free time now so hard to keep track, you can still do something similar by check the `vim.api.nvim_get_current_buf() == buffer_id` to see if the buffer is active. Basically, there is a way using the API and it's functions, so I suggest looking into those. The above might work, if not if you do a bit of digging there is definitely a way.

**Comment by horseinthesky** [comment]
@akinsho 
`vim.api.nvim_get_current_buf() == opts.id` is exacly what I was looking for. Thanks!

Pushed a small merge request that removes extra padding in case of `numbers` func returns an empty string.

Regarding a highlight group - I've added a new group in `config.lua` but I didn't quite get what I need warp and with what in 2. and 3.

**Comment by akinsho** [comment]
@horseinthesky finally got time to add in a highlight group for numbers, can you check out the PR

**Comment by horseinthesky** [comment]
> @horseinthesky finally got time to add in a highlight group for numbers, can you check out the PR

Hey. Thaks a lot. But it actually don't do what it is supposed to

Here is my config (without numbers group):
```
require("bufferline").setup {
  options = {
    always_show_bufferline = false,
    show_buffer_icons = false,
    show_buffer_close_icons = false,
    show_close_icon = false,
    modified_icon = "",
    show_tab_indicators = false,
    tab_size = 5,
    numbers = function(opts)
      if vim.api.nvim_get_current_buf() == opts.id then return "" end
      return opts.ordinal
    end,
  },
  highlights = {
    indicator_selected = {
      guifg = {
          attribute = "fg",
          highlight = "Type"
      },
      guibg = {
          attribute = "bg",
          highlight = "Type"
      },
    },
    buffer_selected = {
      gui = "NONE",
    },
    pick_selected = {
      gui = "NONE",
    },
  },
}
```

The result:
![image](https://user-images.githubusercontent.com/19948672/162559038-85aac918-be16-40cc-ab1d-cd9e24163571.png)

When on `numbers-highlight` branch it ignores buffer selected group and shows selected buffer name in italic:
![image](https://user-images.githubusercontent.com/19948672/162559080-2f34e5e7-1323-46f6-9f1f-c13badb37408.png)

When I add `numbers_visible` it changes nothing:
```
numbers_visible = {     
  guifg = {             
      attribute = "fg", 
      highlight = "Type"
  },                    
  guibg = {             
      attribute = "bg", 
      highlight = "Type"
  },                    
},                      
```
![image](https://user-images.githubusercontent.com/19948672/162559154-fa2b8589-3f3c-4e12-9c40-bba17d209983.png)

When I add numbers it also highlights buffer name:
```
 numbers = {             
   guifg = {             
       attribute = "fg", 
       highlight = "Type"
   },                    
   guibg = {             
       attribute = "bg", 
       highlight = "Type"
   },                    
 },                      
 ```
![image](https://user-images.githubusercontent.com/19948672/162559126-866597bc-15f6-4403-a609-60cebe8bd97f.png)
 
 My goal is to highlight numbers of visible buffers only.

**Comment by akinsho** [comment]
@horseinthesky I'm kind of confused by the results you are seeing, when I set `numbers_selected` I see

Using direct colors:

<img width="902" alt="Screen Shot 2022-04-09 at 10 12 40" src="https://user-images.githubusercontent.com/22454918/162565929-6ff68d07-399f-495a-a994-5884fda9ae95.png">

Using group links:
<img width="946" alt="Screen Shot 2022-04-09 at 10 28 54" src="https://user-images.githubusercontent.com/22454918/162566037-ce1545d3-ca29-48f2-b60a-0436f907a0e6.png">

To be clear, by default the numbers just copy the exact same highlight as before there is no default highlight

**Comment by horseinthesky** [comment]
@akinsho I have a guess if it can happen due to I have `numbers` as function in `options. Could you pls try out my full config?

**Comment by akinsho** [comment]
Ah, found the issue, should be fixed now. Can you try again?

**Comment by horseinthesky** [comment]
@akinsho Yeap. Works perfectly now. Thank you.

**Comment by akinsho** [comment]
Great, just merged this into dev, will close this out now 👍🏿 . Will look to merge the changes into main after a short delay to make sure nothing else broke.
