### ISSUE TITLE
how to display absolute  path + filename?

### ISSUE THREAD

**Issue by jingkai1** [akinsho/bufferline.nvim#282]

**Comment by akinsho** [comment]
That isn't supported @jingkai1 and tbh isn't going to be added because it would result in a large amount of complexity since the plugin is already designed around having a manageable file name length

**Comment by akinsho** [comment]
Don't want to be rude, but this is kind of a firm no unless someone who has read through the code can suggest a comprehensive solution that would allow this option without breaking everything else. I definitely will not be adding this personally, though, as it was a decision I made when initially implementing this plugin and one I won't personally go back on.
