### ISSUE TITLE
[Feature request] Add toggle_pin and close_pinned and close_all_but_pinned

### ISSUE THREAD

**Issue by tibimunteanu** [akinsho/bufferline.nvim#289]
### What happened?

Could you add pin buffer functionality like in barbar?

I managed to have something like 'toggle_pin' by keeping a table of booleans indexed by buffer ids.. and passing bufferline a custom sorting function which always places pinned buffers first. To replace the close icon with a pin icon, I had to alter the bufferline source.

I got the 'close_pinned' and 'close_all_but_pinned' functionality by iterating the open buffers and closing the ones which have the correct boolean in the pinned table.

But I think pinned buffers should be a core feature, and it should also handle 'always show pinned buffers', 'unpin on close', 'save pin flags on quit' and nth 'separate highlights for pinned buffers'
![pinned_buffers](https://user-images.githubusercontent.com/1462924/147878160-ca2c8317-8961-48dd-aca3-f2d3e4bb670a.jpg)

### What did you expect to happen?

<cmd>BufferLineTogglePin
<cmd>BufferLineClosePinned
<cmd>BufferLineCloseAllButPinned

separate pinned buffer highlights
pin icon config

**Comment by akinsho** [comment]
Hi @tibimunteanu for the most part I'm trying to spend my free time working on other side projects and am trying to divert the historically huge amount of time I've spent on nvim projects on other things. The feature sounds useful though so I'd be open to a PR to implement this but as I've mentioned my time is limited across multiple plugins so if you'd like to implement this feature I can help guide a PR but won't be looking to do this myself in the short term as I simply don't have time.

**Comment by akinsho** [comment]
This has now been merged into the `dev` branch and will eventually go into the `main` branch, it is implemented using the `groups` feature under the hood, so buffers can be toggled using `BufferLineTogglePin` and closing all pinned via `BufferLineGroupClose pinned`. To be clear exact feature parity with other tablines is not the goal so I'm not looking to emulate their APIs

fixed by #351
