### ISSUE TITLE
Does it support the CtrlSpace plugin?

### ISSUE THREAD

**Issue by tristone13th** [akinsho/bufferline.nvim#290]

**Comment by akinsho** [comment]
I'm not aware of this plugin really @tristone13th so essentially no, I also don't really integrate specific plugins into this one since that means I'd have to keep up to date with their APIs which is definitely not something I'm keen on

**Comment by tristone13th** [comment]
> I'm not aware of this plugin really @tristone13th so essentially no, I also don't really integrate specific plugins into this one since that means I'd have to keep up to date with their APIs which is definitely not something I'm keen on

Many thanks to you.

**Comment by akinsho** [comment]
Going to close this out as the question has been answered
