### ISSUE TITLE
[feature request] customize group buble

### ISSUE THREAD

**Issue by quantum-booty** [akinsho/bufferline.nvim#295]
On Windows, I get weird lines joining the semi circle and the square gray backgrounds on the group bubble, would be nice if I could customize it to just use the squares.
![image](https://user-images.githubusercontent.com/28958399/148688026-50b5dfbc-17e0-483e-aec6-e019e54548a9.png)

**Comment by akinsho** [comment]
Hi @quantum-booty,

This looks like a terminal font sizing issue, which is definitely out of scope for this plugin. The grouping feature is kind of beta, but I have *zero* time to work on this plugin in depth atm other than just triaging issues as I'm very busy atm. You can try to change the separator style for the groups. This is documented in the README 
```
 {
      name = "Docs"
      highlight = {gui = "undercurl", guisp = "green"},
      auto_close = false,  -- whether or not close this group if it doesn't contain the current buffer
      matcher = function(buf)
        return buf.filename:match('%.md') or buf.filename:match('%.txt')
      end,
      separator = { -- Optional
        style = require('bufferline.groups').separator.tab <-------------- This Line Here
      },
    }
```
