### ISSUE TITLE
How to set the numbers properly?

### ISSUE THREAD

**Issue by tranvnhan** [akinsho/bufferline.nvim#296]
First of all, thanks for putting your effort into this plugin. I have been enjoying it.

My question is, how can I properly set the buffer numbers?
As you can see in the screenshot below, the numbers are displayed as ```table: 0x...```. How do fix this issue?
Thanks.

![image](https://user-images.githubusercontent.com/18115563/148691017-dcaa7983-15e1-4648-b4a0-fc3bd2298784.png)

**Comment by akinsho** [comment]
@tranvnhan it appears that rather than returning a string from the numbers function you are returning a table hence the bug. Please read [this part](https://github.com/akinsho/bufferline.nvim#numbers) of the readme carefully. I describe several ways to render the numbers correctly

**Comment by tranvnhan** [comment]
I initially thought that I need to define ```opts``` somewhere so that I can use it. Following the instructions on README file I can now display the numbers  as I want.
Thanks.
