### ISSUE TITLE
[Bug]: Filtering as covered in README shouldn't exists

### ISSUE THREAD

**Issue by lpawlak1** [akinsho/bufferline.nvim#297]
### What happened?

The issue is that based on code parameters mismatch

```lua
---@param callback fun(buf: integer, bufs: integer[]): boolean
```
https://github.com/akinsho/bufferline.nvim/blob/master/lua/bufferline.lua#L135

Even though this takes bufs as parameter in README function provided doesn't take second argument.

### What did you expect to happen?

Filter buffers

### Additional Information

I would suggest changing README adding information about filtering function and/or changing code to match function from README

**Comment by akinsho** [comment]
Closing this as the associated PR is merged
