### ISSUE TITLE
Custom area rendering nothing

### ISSUE THREAD

**Issue by SyedAhkam** [akinsho/bufferline.nvim#300]
Hey! I was trying out the `custom_area` feature.

I first tried the example existing on the `README` but when it displayed nothing, I thought of just rendering plain text by setting the `text` field to my desired text and returning the object. Regardless, It is still the same. 

![image](https://user-images.githubusercontent.com/52673095/148704418-e6e41810-d362-4382-a039-0bc868765897.png)

### My setup function
```lua
require("bufferline").setup{
    options = {
        numbers = "ordinal",
        diagnostics = "nvim_lsp",
        separator_style = "slant",
        show_close_icon = false,
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
            local icon = level:match("error") and " " or " "
            return " " .. icon .. count
        end,
        custom_areas = {
            right = function() return {text = "hi" , guifg = "#f7768e"} end
        }
    }
}
```

I am sure this is not a bug but some misconfiguration on my end. Could anyone provide me a pointer?

**Comment by akinsho** [comment]
Hi @SyedAhkam,

If you look closely at the example in the README you'll notice that the custom areas should not return an object but a *list* of objects so in your case you are returning just one singular object instead of a list

```lua
return {
 { text = 'Example', guifg = '<color-here>'}
}
```

**Comment by SyedAhkam** [comment]
Oh! I did such a dumb mistake haha.

It works perfectly now. Thank you!
