### ISSUE TITLE
[Bug]: loop or previous error loading module 'bufferline' "~/.config/nvim/lua/bufferline.lua" 50L,  on NixOS

### ISSUE THREAD

**Issue by Deep-Six** [akinsho/bufferline.nvim#304]
### What happened?

I'm getting the infamous 
loop or previous error loading module 'bufferline'
"~/.config/nvim/lua/bufferline.lua" 50L, 2280C

I've reviewed the 2 other bugs related to this and unfortunately haven't found any joy, it is worthy to note that I'm using NixOS which is doing some traditionally peculiar things that may be at issue.

Things I've tried:
- reducing my init.vim to a minimal
- looking for things identifying bufferline in my existing lua files
- removing all options and using a basic require('bufferline').setup{}
- intentionally mispelling bufferline in the require('bufferline').setup {} (to test the nix linkage)...nvim complains module bufferlineZ isn't working

Version:
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/n9ksj8vc6nh6qjgfnlr1528y1db0bggv-neovim-unwrapped-0.5.1/share/nvim
"

### What did you expect to happen?

sexy bufferlines!

### Additional Information

Thanks for a great plugin, I hope to use it soon!

**Comment by akinsho** [comment]
@Deep-Six this is a bit of a guess but it looks a bit like your setup contains a file also called `bufferline.lua` inside of the lua directory which is not namespaced which would definitely cause an error loading this plugin. Can you clarify how your configuration is setup. Please don't link to a bunch of files which I'll have to read through just confirm 
* where you have put your bufferline config
* whether or not you have created a file called `bufferline.lua` in your config directory just under the `lua` directory
If so this is incorrect and is likely why you are encountering an error.
If not it still seems to be an issue with how the module is being loaded which is likely happening on your end. I recommend using a minimal vim config that is just one lua file with only this plugin loaded and see if that works

**Comment by Deep-Six** [comment]
@akinsho  thanks, I'll try my luck in the NixOS community, 
If you fancy digging in I'll note my config, in the event you can spot something:

init.vim

pkgs:
{
  enable = true;
  vimAlias = true;
  viAlias = true;

  extraConfig = ''
  	luafile $HOME/.config/nvim/lua/bufferline.lua
  	luafile $HOME/.config/nvim/lua/lsp.lua
  	luafile $HOME/.config/nvim/lua/nvim-tree-lua.lua
  	luafile $HOME/.config/nvim/lua/settings.lua
  	luafile $HOME/.config/nvim/lua/treesitter.lua
	'';

  plugins = with pkgs.vimPlugins; [

  bufferline-nvim
  galaxyline-nvim
  indentLine
  nvim-compe
  nvim-lspconfig
  nvim-tree-lua
  nvim-treesitter
  nvim-web-devicons
  surround
  vim-nix

  ];
}


# bufferline.lua

require('bufferline').setup {
  options = {
    numbers = "none",
    number_style =  "", -- buffer_id at index 1, ordinal at index 2
    mappings = true;
    close_command = "bdelete! %d",       -- can be a string | function, see "Mouse actions"
    right_mouse_command = "bdelete! %d", -- can be a string | function, see "Mouse actions"
    left_mouse_command = "buffer %d",    -- can be a string | function, see "Mouse actions"
    middle_mouse_command = nil,          -- can be a string | function, see "Mouse actions"
    -- NOTE: this plugin is designed with this icon in mind,
    -- and so changing this is NOT recommended, this is intended
    -- as an escape hatch for people who cannot bear it for whatever reason
    indicator_icon = '▎',
    buffer_close_icon = '',
    modified_icon = '●',
    close_icon = '',
    left_trunc_marker = '',
    right_trunc_marker = '',
    --- name_formatter can be used to change the buffer's label in the bufferline.
    --- Please note some names can/will break the
    --- bufferline so use this at your discretion knowing that it has
    --- some limitations that will *NOT* be fixed.
    name_formatter = function(buf)  -- buf contains a "name", "path" and "bufnr"
      -- remove extension from markdown files for example
      if buf.name:match('%.md') then
        return vim.fn.fnamemodify(buf.name, ':t:r')
      end
    end,
    max_name_length = 18,
    max_prefix_length = 15, -- prefix used when a buffer is de-duplicated
    tab_size = 18,
    diagnostics =  "nvim_lsp",
    diagnostics_update_in_insert = false,
    diagnostics_indicator = function(count, level, diagnostics_dict, context)
      return "("..count..")"
    end,
   offsets = {{filetype = "NvimTree", text = "File Explorer" , text_align = "center" }},
    show_buffer_icons = true, -- disable filetype icons for buffers
    show_buffer_close_icons = true,
    show_close_icon = true,
    show_tab_indicators = true,
    persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
    -- can also be a table containing 2 custom separators
    -- [focused and unfocused]. eg: { '|', '|' }
    separator_style = "thick",
    enforce_regular_tabs =  true,
    always_show_bufferline = true,
    sort_by = 'id',
  }
}


let me know if that gives you any insight, and again thanks for your time!

**Comment by akinsho** [comment]
```shell
luafile $HOME/.config/nvim/lua/bufferline.lua
luafile $HOME/.config/nvim/lua/lsp.lua
luafile $HOME/.config/nvim/lua/nvim-tree-lua.lua
luafile $HOME/.config/nvim/lua/settings.lua
luafile $HOME/.config/nvim/lua/treesitter.lua
```
@Deep-Six the above layout for your config is incorrect and is likely what is causing this but, you have a top level lua config file called the *exact same thing* as this plugins main file so your bufferline clashes with this plugins. When configuring nvim with lua you should namespace your config files rather than putting them in the top level lua folder e.g.
```
```shell
luafile $HOME/.config/nvim/lua/deepsix/bufferline.lua
luafile $HOME/.config/nvim/lua/deepsix/lsp.lua
luafile $HOME/.config/nvim/lua/deepsix/nvim-tree-lua.lua
luafile $HOME/.config/nvim/lua/deepsix/settings.lua
luafile $HOME/.config/nvim/lua/deepsix/treesitter.lua
```
If this isn't clear have a look at https://github.com/nanotee/nvim-lua-guide which I think explains this. Basically the files are clashing because of how they are laid out in your config. If you rename the `bufferline.lua` file to something else it should work but this is generally a bug waiting to happen and I suggest namespacing your config files

**Comment by Deep-Six** [comment]
@akinsho  your skill is only eclipsed by your grace and patience!! This was precisely the problem thank you for the lesson. I'll definitely dig into the lua guide as this has sparked my interest in getting better with it!

Thanks for being so awesome!
