### ISSUE TITLE
question: how to disable `right_mouse_command` from closing a tab?

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#305]
As title. I have tried changing the command to `<nop>`, nothing changes.

**Comment by akinsho** [comment]
You could try setting the value to an empty string or `nil` but tbh I'm not sure why you can't just *not press* the middle mouse button when you click on a buffer?

**Comment by nyngwang** [comment]
Yes, I once accidentally clicked the with _right_ mouse button. So I want to disable this option.

**Comment by nyngwang** [comment]
Tried `nil`. Got the same result: buffer got closed with right mouse click.

**Comment by akinsho** [comment]
@nyngwang can you try with an empty string to see if that works

**Comment by nyngwang** [comment]
No. I did that much earlier before I tried `nil`.

**Comment by jan-xyz** [comment]
What package manager are you using? You might need to run `PackerCompile` if you setup your config inside of packer. I just tried the suggestion with an empty string and it works like a charm.

**Comment by nyngwang** [comment]
@jan-xyz packer.nvim. I almost forgot this issue...

**Comment by akinsho** [comment]
Since using an empty string solves this issue, I'm going to close this out for now. Let me know if there's some other issue relating to this
