### ISSUE TITLE
[Bug]: Something weird is happening with theme after splitting

### ISSUE THREAD

**Issue by wintermonth2298** [akinsho/bufferline.nvim#306]
### What happened?

When I open a file and then open another file in split, something weird happens to the theme. Without bufferline, this behavior is not observed. 

1st image - before split
2nd image - after split

![image](https://user-images.githubusercontent.com/68856432/149349093-d2564191-480e-43ed-afbf-d67d7342ee94.png)

![image](https://user-images.githubusercontent.com/68856432/149349341-1a6e21ce-00ef-4ac9-b579-da8fbe8f5cf2.png)

**Comment by wintermonth2298** [comment]
@akinsho 
1. works same with only bufferline and theme enabled
2. works same with different theme 
3. termguicolors=false fixes the problem, but i get wrong colors

**Comment by akinsho** [comment]
@wintermonth2298 is this still an issue? As far as I can tell, it sounds like something relating to your terminal and not specific to bufferline

**Comment by akinsho** [comment]
Closing this out since it seems like a terminal emulator issue and not a plugin issue.
