### ISSUE TITLE
[Bug]: Graphical artefacts with custom separator colors

### ISSUE THREAD

**Issue by MIvanchev** [akinsho/bufferline.nvim#312]
### What happened?

Hey, awesome plugin! When I set custom colors for the separators and the fill I get weird artefacts between and around the tabs. What am I doing wrong? This is neovim-qt v0.2.16.1, neovim v0.6.1

![Something's wrong](https://raw.githubusercontent.com/MIvanchev/images/981fd9c6-440c-42d0-8006-0bea528b2958/bufferline-artefacts.png)

```
" Set Editor Font
if exists(':GuiFont')
    " Use GuiFont! to ignore font errors
    GuiFont! LiterationMono Nerd Font Mono:h12
endif

" Disable GUI Tabline
if exists(':GuiTabline')
    GuiTabline 0
endif
```

### What did you expect to happen?

No artefacts

### Additional Information

...

**Comment by MIvanchev** [comment]
Hm, this appears to be due to antialiasing. It might be better to use U+E0B8 and U+E0BA as separator chars.

**Comment by MIvanchev** [comment]
Nope, that doesn't help either :/

**Comment by akinsho** [comment]
@MIvanchev this isn't something I can control on my side, how a terminal emulator handles rendering of characters is outside my control. Most of the appearance (especially the fancier) stuff is a best effort that almost certainly won't work universally

**Comment by MIvanchev** [comment]
Yep, this is exactly how I see it as well! Let's close this :)
