### ISSUE TITLE
[Question]: How to close other buffers ?

### ISSUE THREAD

**Issue by holicc** [akinsho/bufferline.nvim#317]
want to close other buffers except current buffer

**Comment by akinsho** [comment]
@holicc please have a look at `:help :only` in vim as there is already an existing vim command for this. Gonna close this out now since that's the answer and isn't something specific to this plugin

**Comment by pirey** [comment]
`:only` only close other windows, and it does not close other buffers.

we can take advantage of close left and close right command for workaround

```lua
      vim.keymap.set(
        "n",
        "<leader>bo",
        "<cmd>BufferLineCloseLeft<cr><cmd>BufferLineCloseRight<cr>",
        { desc = "Close other buffers" }
      )

```
