### ISSUE TITLE
How can i remove this dark space, and is there a way to change the theme?

### ISSUE THREAD

**Issue by charbel-dot** [akinsho/bufferline.nvim#319]
![Screenshot 2022-01-31 141759](https://user-images.githubusercontent.com/72027836/151792635-66806c1f-ec08-4aca-97d9-48d221b82df6.png)

**Comment by akinsho** [comment]
@charbel-dot if you read through the help documentation `:help bufferline` it explains how to change the different highlights for the plugin. I don't remember all the highlight names off the top of my head but they are in the documentation.
