### ISSUE TITLE
[Bug]: Exception when using vim-fugitive, not always

### ISSUE THREAD

**Issue by JavaHello** [akinsho/bufferline.nvim#324]
### What happened?

Exception when using vim-fugitive, not alway

<img width="585" alt="截屏2022-02-14 上午11 13 03" src="https://user-images.githubusercontent.com/24937965/153794539-d552eaa7-87de-4b01-ba67-d2533e4ee0b9.png">

### What did you expect to happen?

Expected behaviou
<img width="577" alt="截屏2022-02-14 上午11 13 36" src="https://user-images.githubusercontent.com/24937965/153794583-6440b1d8-9a91-4f70-a276-8f69061bee03.png">

### Additional Information

E5108: Error executing lua .../packer/start/bufferline.nvim/lua/bufferline/sorters.lua:46: attempt to index local 'buf_b' (a nil value)
stack traceback:
        .../packer/start/bufferline.nvim/lua/bufferline/sorters.lua:46: in function <.../packer/start/bufferline.nvim/lua/bufferline/sorters.lua:45>
        [C]: in function 'sort'
        .../packer/start/bufferline.nvim/lua/bufferline/sorters.lua:97: in function 'sort_buffers'
        ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:897: in function 'sorter'
        ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:948: in function <...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:905>

**Comment by akinsho** [comment]
@JavaHello I just pushed a fix that checks that buffers are nil whilst sorting. Let me know if you still encounter this issue after updatign and I'll re-open it
