### ISSUE TITLE
[Bug]: No write since last change.

### ISSUE THREAD

**Issue by uunnxx** [akinsho/bufferline.nvim#327]
### What happened?

When I edit the current file, I cannot switch between next/prev buffers until I save the current file with the changes I made.

```
E5108: Error executing lua .../bufferline.nvmi/lua/bufferline.lua:324
Vim(buffer):
E37: No write since last change (add ! to override)
```

### What did you expect to happen?

I have to move between files freely because I know in which buffer changes are made due to the icon

![image](https://user-images.githubusercontent.com/6236057/155364901-cf00bac2-e8d8-4dc8-9053-5c54331d4e47.png)

### Additional Information

```
$ > nvim --version
NVIM v0.6.0-dev+107-g3d1835967
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-236

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

```

**Comment by akinsho** [comment]
@uunnxx this error doesn't actually come from this plugin. This is likely an underlying neovim issue that is only surfacing because you are clicking bufferline tabs or using it's next or prev command. You either need to `set hidden` in your config or otherwise dig into what is causing this but the issue won't actually be within this plugin I believe

**Comment by uunnxx** [comment]
Much appreciated for the quick response!
I tried to rewrite my `vimrc` to `init.lua`

I must have forgotten to add `set hidden`
Everything is working as expected, thank you <3
