### ISSUE TITLE
lelft_mouse_command seems not working in windows terminal.

### ISSUE THREAD

**Issue by LeoGitHuber** [akinsho/bufferline.nvim#328]
I'm new to neovim. I follow instruction of bufferline, but left_mouse_command seems not working in windows terminal, the same as right_mouse_command and close_command.

**Comment by akinsho** [comment]
@LeoGitHuber there isn't much information here that I can use to help you. By default, this works for me and I believe most other people. I don't use windows, so I can't test it out there myself. Can you let me know what exactly works or doesn't? Have you tried other terminals? How have you configured bufferline?

**Comment by LeoGitHuber** [comment]
Thanks for replying. I just installed it by packer and set it up by default. The bufferline didn't response mouse click to switch buffer or close buffer. Any other functions work well. I haven't tried other terminals yet. Below is my configuration.

![image](https://user-images.githubusercontent.com/50997355/155667068-5703a606-1d15-411f-b0b1-a4b5ecdc9dec.png)

**Comment by LeoGitHuber** [comment]
@akinsho I have solve my problem. I didn't know there is mouse support option in neovim. I set 'vim.opt.mouse="a"' in init.lua. Then every function works well. Thank you for your help.
