### ISSUE TITLE
[Bug]: mappings has been depreceated

### ISSUE THREAD

**Issue by siduck** [akinsho/bufferline.nvim#330]
I updated nvim today and been getting this issue 
![image](https://user-images.githubusercontent.com/59060246/155912195-78160aff-ca25-4b53-a912-15c8468732c1.png)

![image](https://user-images.githubusercontent.com/59060246/155912179-e5259226-b0f9-40d2-9c41-eaa563c8e2e7.png)

i dont even have numbers var defined in my config!

**Comment by akinsho** [comment]
Hi @siduck ,

So those changes are really old now, you will get the errors if you specify those keys. Do you have mappings in your config at all, also regarding numbers have you done the whole packer compile dance?

Can you paste the config you are using?

**Comment by siduck** [comment]
> Hi @siduck ,
> 
> So those changes are really old now, you will get the errors if you specify those keys. Do you have mappings in your config at all, also regarding numbers have you done the whole packer compile dance?
> 
> Can you paste the config you are using?

I no longer get that issue, after a reboot. WEIRD. I do know that was an old change and i update nvim daily but this gets fixed today :laughing:
