### ISSUE TITLE
[Question] How do you change the background colour of the bufferline

### ISSUE THREAD

**Issue by Gako358** [akinsho/bufferline.nvim#336]
I have manged to setup the bar quiet fine, but the background color on the bar itself, does not belong to any of my colors. It is black, pure black, is it someway to set the color on that?

**Comment by akinsho** [comment]
@Gako358 it could be because you are missing some default highlight group that is expected in your theme. Can you read through the available highlights in the docs and find the background one and set that value yourself

**Comment by Gako358** [comment]
I tried setting both background and fill guibg to any other color, but nothing changed...

`highlight = {
    fill = {
        guibg = 'fg',
    },
},`

The same for background..

**Comment by akinsho** [comment]
@Gako358 I can't tell what highlight isn't working since I don't have a picture of your bufferline to tell which highlight you're trying to change. All the highlights that can be changed are available in the help documentation and it's likely one of those but I don't know which one

**Comment by akinsho** [comment]
@Gako358 you have typo in your config. `highlight` should be `highlights` the final `s` is missing. I have verified on my end that fill works.

**Comment by Gako358** [comment]
Ive now tried with highlights and used '#ffffff', 'fg', 'blue'.. but nothing changes.

**Comment by akinsho** [comment]
@Gako358 I'm testing this on my machine, and it works fine on my end. The config I'm using looks like
```lua
  require('bufferline').setup {
    highlights = {
      fill = {
        guibg = '#FFFFFF',
      },
    },
  }
```
I can see from other users setups as well as my own that this definitely works. Please try and confirm that nothing unusual is going on in your setup and that if you are using packer you are making sure that it has properly recompiled and everything has been reloaded

**Comment by Gako358** [comment]
Actually had to load the highlights after the option, and I had to take inn a list of colors that I could use, now it is working.
Thank you for your help, this can be closed now

**Comment by akinsho** [comment]
As I mentioned before, the highlights can all be found in the highlights' table under `:help bufferline-highlights`. I just looked at this myself and found the group i.e. `separator_{selected|visible}` will change the separator colour

<img width="1400" alt="Screen Shot 2022-03-18 at 23 34 28" src="https://user-images.githubusercontent.com/22454918/159096970-90992546-bf31-4f8a-93e8-2ebc17ae4a0e.png">

**Comment by wellcomez** [comment]
> As I mentioned before, the highlights can all be found in the highlights' table under `:help bufferline-highlights`. I just looked at this myself and found the group i.e. `separator_{selected|visible}` will change the separator colour
> 
> <img alt="Screen Shot 2022-03-18 at 23 34 28" width="1400" src="https://user-images.githubusercontent.com/22454918/159096970-90992546-bf31-4f8a-93e8-2ebc17ae4a0e.png">

how to color of number area?
