### ISSUE TITLE
[Bug]: error on buffer close, switches to tabs after

### ISSUE THREAD

**Issue by mcauley-penney** [akinsho/bufferline.nvim#338]
### What happened?

After the recent feature merges, closing a buffer results in an error which somehow results in tabs appearing to be used after. Pleas see the attached GIF. 

Second Edit: I'm now noticing that it's happening with a few different events that open other buffers: "UndotreeToggle" with mbbill/undotree and "StartupTime" with dstein64/vim-startuptime.

![error](https://user-images.githubusercontent.com/59481467/158222080-69e62d4d-2504-433d-a808-eee758239caf.gif)

The mapping that I'm using to close buffers is 
`vim.api.nvim_set_keymap("n", "<C-w>", "<cmd>bd<CR>", { noremap = true, silent = true })`. As you can see in the bufferline, the style changes entirely. That style that is displayed after the error is the style I have for tabs at the moment, almost the default.

### What did you expect to happen?

Buffers would close without an error

### Additional Information
First edit: Here is a still of the error given:

![image](https://user-images.githubusercontent.com/59481467/158223274-04dee930-a337-4c56-8072-9c1b610b65b8.png)

### commit

f6a264b7f6067badf32f6e4b421e92bf76eae564

**Comment by akinsho** [comment]
Hi @mcauley-penney, can you please share a minimal configuration, so I can reproduce this bug. I don't see this issue in my daily usage and using `:bd` does not automatically reproduce this, so it is probably related to something in your configuration/setup, but I don't know what.

**Comment by shaeinst** [comment]
i have similar issue.
when i try to close the modified file with ```:bd``` (this gonna give No write error) then save the file and again try to close with same command, ```:bd```, i get following error
![image](https://user-images.githubusercontent.com/41078534/158224418-df57c3b3-8cf6-4ce2-9e70-7e3986cff1d4.png)

**Comment by akinsho** [comment]
@shaeinst as I mentioned above, I need a configuration that reproduces this issue, so I can test it myself. My setup does not recreate this issue, so I cannot debug or fix it without a specific *minimal* configuration that reproduces this issue.

**Comment by mcauley-penney** [comment]
@akinsho Okay, no problem! I'll work on trimming this down. Also, I commented out the items above that would be problematic for others, such as the usage of some functions that I define elsewhere. Sorry about that, I noticed it after I posted

**Comment by akinsho** [comment]
Okay so I removed the highlight settings due to all the missing logic and tried with just the setting in the setup function and I don't see this issue. The minimal config I am working with is
```lua
vim.cmd("packadd bufferline.nvim")

local opt_tbl = {
	enforce_regular_tabs = true,
	options = {
		always_show_bufferline = true,
		groups = {
			items = {
				{
					name = "[src]:",
					matcher = function(buf)
						local t = buf.filename
						return t:match("%.c") or t:match("%.cpp") or t:match("%.lua")
					end,
				},
				{
					name = "[src2]:",
					matcher = function(buf)
						local t = buf.filename
						return t:match("%.py") or t:match("%.sh")
					end,
				},
				{
					name = "[data]:",
					matcher = function(buf)
						local t = buf.filename
						return t:match("%.json") or t:match("%.md") or t:match("%.txt")
					end,
				},
				require("bufferline.groups").builtin.ungrouped,
			},
		},
		indicator_icon = "",
		modified_icon = "%m",
		separator_style = "thin",
		show_tab_indicators = true,
		show_buffer_icons = true,
		show_buffer_close_icons = false,
		show_close_icon = false,
	},
}

require("bufferline").setup(opt_tbl)
```

**Comment by shaeinst** [comment]
@akinsho can please try with your current config.
1. open a file
2. make any change
3.  try to close the buffer with :bd
4. undo chnage
5. again try to close the buffer with :bd
please let me know you can reproduce the error i mentioned.

**Comment by mcauley-penney** [comment]
@akinsho Tested that configuration, no issues at all. It's elsewhere and I'm going to dig for it

Sorry for the all the noise in this issue, I'm fairly new with reporting issues with Neovim/plugins

**Comment by mcauley-penney** [comment]
@akinsho: in the [above comment](https://github.com/akinsho/bufferline.nvim/issues/338#issuecomment-1067079947) I mention that, after removing `always_show_bufferline = false`, I get a different error and provided a screenshot. That error only exists if I have `j-hui/fidget.nvim` included, which it looks like you removed recently from your own config. If I remove fidget and that setting, it resolves my issue completely. 

In sum, with `always_show_bufferline = false` I get the original issue. Without it but with fidget, I get a different issue. Without both, I have no issues

**Comment by akinsho** [comment]
@mcauley-penney sorry closed this a little quickly, had meant to write relates not fixed in my commit. Anyway, I believe it comes down to `always_show_bufferline` which had some logic moved to the wrong place. It should now be fixed, though. Let me know if it isn't. Regarding `fidget` the error you are seeing about closing the last window is from nvim as far as I know and would occur if you were trying to close the only open window which is what `bd` on a single window would do AFAIK.

**Comment by akinsho** [comment]
anyway hopefully this change should have returned bufferline's behaviour to how it was before

**Comment by akinsho** [comment]
For future reference I believe this was a duplicate of #337 just a different manifestation 🤞🏿

**Comment by mcauley-penney** [comment]
I updated and it fixed using that setting. Thank you!  

> For future reference I believe this was a duplicate of #337 just a different manifestation 🤞🏿

I appreciate the gentle reminder to check open issues first. Thank you again!

**Comment by akinsho** [comment]
> I appreciate the gentle reminder to check open issues first. Thank you again!
@mcauley-penney lol wasn't actually a nudge towards you, I was dealing with both issues simultaneously and didn't realise for quite a while that they were the same since the error was different.
