### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by keaising** [akinsho/bufferline.nvim#344]
### What happened?

When I try to execute `: BufferLineSortByDirectory` or `: BufferLineSortByExtension`, I get this error

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/8179012/159335326-057543ed-ad1c-473a-9d68-1236ea18cdbc.png">

After researching, I find that in `commands.lua`  you call for 

```lua
sorters.sort_buffers(sort_by, state.components)
```

https://github.com/akinsho/bufferline.nvim/blob/master/lua/bufferline/commands.lua#L255

But in `sorters.lua` only export a `sort` function

https://github.com/akinsho/bufferline.nvim/blob/master/lua/bufferline/sorters.lua#L95

I think maybe here is a bug, but when I try to change 

```lua
sorters.sort_buffers(sort_by, state.components)
```

into 

```lua
sorters.sort(sort_by, state.components)
```

I get an error about mis-type.

I'm not farmilliar with lua, could you help to find the problem?

### What did you expect to happen?

Expected behaviour

Dont throw errror when I execute `: BufferLineSortByDirectory` or `: BufferLineSortByExtension`

### Additional Information

...

**Comment by akinsho** [comment]
@keaising thanks for raising this. I wasn't aware it had broken. I'll look into it 👍🏿
