### ISSUE TITLE
[Feature Request]: Tabs aren't being aligned in split view

### ISSUE THREAD

**Issue by thisizkp** [akinsho/bufferline.nvim#345]
### Screenshot
<img width="1792" alt="Screenshot 2022-03-22 at 4 37 11 PM" src="https://user-images.githubusercontent.com/4737336/159493880-3a99dd46-2b3e-4a9a-8b11-4901b56aedbf.png">

### Steps
1. Open a file
2. Search for a new file using `<leader>ff` and do `Ctrl V` to open the new file in split view

The more files we open, more it gets confusing and difficult to keep track of which tab is associated with which pane.

### What did you expect to happen?

Expected behaviour: Tabs should respect split view

(Not a bug -- but more like a feature request. But it didn't allow modifying the labels)

**Comment by akinsho** [comment]
@thisizkp this isn't really feasible if I understand you correctly. Is the general idea you mean to keep tabs located above the window they relate to? It's possible tbh, but the amount of work is very high. I really am not sure if I would take on that level of complexity for what I think is a somewhat marginal gain.

![buffer groups](https://i.redd.it/7kn6lmkp7l931.png)

Is this what you mean? ☝🏿

**Comment by thisizkp** [comment]
Yes, that is what I meant. If the amount of work is very high, then yeah might not be worth doing it at this point. 

But would like to know, how do you manage when you have multiple files in split views? Isn't it confusing?

**Comment by akinsho** [comment]
@thisizkp I really don't find it confusing, but I guess quite importantly I almost never have more than 3 splits open, so as long as all visible splits are open it's usually pretty easy to tell which split is which. I've never really thought of it as being potentially confusing or problematic before

**Comment by thisizkp** [comment]
Ha okay. Yeah, I'm new to `vim/neovim` coming from `VSCode`. It is a bit difficult to get used to. Anyways, thanks for the response. Closing this issue. We can reopen in the future if we want to implement the above change.
