### ISSUE TITLE
[Bug]: BufferLineCycleNext cycles through closed buffers

### ISSUE THREAD

**Issue by ikerurda** [akinsho/bufferline.nvim#352]
### What happened?

After closing a buffer with any of the options available (`:bd`, clicking the `X`, `:BufferLinePickClose`, ...) if `always_show_bufferline` is set to `false` and only one buffer is left, `:BufferLineCycleNext` will cycle between the last opened and the last closed buffer.

### What did you expect to happen?

I was expecting not to cycle buffers as only one last buffer is open.

### Additional Information

Note that this only happens when `always_show_bufferline = false`

**Comment by akinsho** [comment]
@ikerurda this should now be fixed on the `dev` branch and will be ported over here when that branch is ready to merge

**Comment by akinsho** [comment]
This is fixed now and merged into the main branch
