### ISSUE TITLE
[Bug]: Setting "mode" in config causes an error

### ISSUE THREAD

**Issue by evprkr** [akinsho/bufferline.nvim#355]
### What happened?

Setting `mode = "tabs"` in setup causes the error:

```
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...k/packer/start/bufferline.nvim/lua/bufferline/config.lua:211: attempt to call method 'mode' (a string
 value)
stack traceback:
        ...k/packer/start/bufferline.nvim/lua/bufferline/config.lua:211: in function 'is_tabline'
        ...k/packer/start/bufferline.nvim/lua/bufferline/config.lua:603: in function 'resolve'
        ...k/packer/start/bufferline.nvim/lua/bufferline/config.lua:637: in function 'apply'
        ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:280: in function '__load'
        [string ":lua"]:1: in main chunk
```

### What did you expect to happen?

Expected behavior is to only show tabs and not buffers

### Additional Information

...

**Comment by akinsho** [comment]
@evprkr can you link the configuration you are using that causes this problem. Is the mode correctly set inside the options table?

**Comment by evprkr** [comment]
@akinsho Thanks for the quick response. I nuked it out of frustration (been screwing trying to transition to neovim from vim for two days and I needed to do work so I moved back to vim for right now) but I just recreated it here: 

https://gist.github.com/evprkr/e5a36bc7316bc31279ffcd622c75bdc9

Just about as barebones as you could get. I should note, I previously had tried to use NvChad, but I had issues with that so I `rm -rf`'d the entire `~/.config/nvim` folder, uninstalled then reinstalled neovim via brew, and set it all up from scratch. Bufferline was the first plugin I installed after setting up Packer.

**Comment by akinsho** [comment]
@evprkr your configuration is set up incorrectly, the options above should be set *inside an options table* please have a close look at the README configuration. The above should appear like
```lua
config = {
  options = {
		mode = "tabs"
  }
}
```

**Comment by akinsho** [comment]
Closing this out now since as I mention in the comment above I believe this is due to using the wrong keys in the config
