### ISSUE TITLE
[Question] Is there any other way to change the highlight group?

### ISSUE THREAD

**Issue by askfiy** [akinsho/bufferline.nvim#362]
I want to change different styles of highlight groups for different themes, I'm sure that these themes are loaded with `after = {"bufferline.nvim"}`, but all highlight group changes have no effect (I mean the of BufferLine highlight group)

I am aware of the highligts option, but I have a lot of themes and I would prefer to manually set the performance of each theme on the BufferLine.

```
in theme file

    -- bufferline
    local normal_fg = "#D4D4D4"
    local normal_bg = "#1E1E1E"

    utils.hi.set("BufferLineBufferVisible", {fg = normal_fg, bg = normal_bg, gui = "NONE"})
    utils.hi.set("BufferLineBufferSelected", {fg = normal_fg, bg = normal_bg, gui = "NONE"})

--------------------------
utils.lua

function M.hi.set(group, color)
    local style = color.gui and "gui=" .. color.gui or "gui=NONE"
    local fg = color.fg and "guifg=" .. color.fg or "guifg=NONE"
    local bg = color.bg and "guibg=" .. color.bg or "guibg=NONE"
    local sp = color.sp and "guisp=" .. color.sp or "guisp=NONE"
    local blend = color.blend and "blend=" .. color.blend or "blend=NONE"
    vim.cmd("highlight " .. group .. " " .. style .. " " .. fg .. " " .. bg .. " " .. sp .. " " .. blend)
end
```

**Comment by akinsho** [comment]
@askfiy tbh this all seems to go directly against how this plugin was designed. Firstly, the plugin was developed to inherit styles automatically from any theme and appear consistent between themes.

Why are you trying to tweak the appearance between themes? Personal preference or a bug?

Secondly, all highlights should go in to the `config.highlights`, users are not supposed to directly manipulate `BufferLine*` highlight groups. The plugin programmatically sets these groups, and they are only expected to be collected via the config.

**Comment by askfiy** [comment]
I'd prefer to set some highlights on different themes to make them look cooler, i.e. is there no way to do that?

That means I need to `require` the `bufferline` again in each different theme.

I feel so troublesome...

Perhaps `bufferline` should provide an interface that allows the user to change the highlight group externally?

**Comment by akinsho** [comment]
@askfiy you can do this more simply by just creating a palette map in your config and passing that the bufferline e.g.
```lua
-- theme1.lua
return {
  fill = {
   ...
  }
}

--- theme2.lua
return {
  buffer_visible = {
   ...
  }
}


--- In bufferline.lua
require('bufferline').setup({
	highlights = require('theme1')
})
--- Or
require('bufferline').setup({
	highlights = require(vim.o.colors) -- if you name the theme file directly the same as the colorscheme name
})
```

You shouldn't require bufferline multiple times that is a bad idea, regarding externally exposing highlights this has already been discussed in a few issues #320. As I have mentioned before, there are a few different reasons why this plugin doesn't do that. Anyway if you want to discuss that aspect of things you can comment in the linked issue

**Comment by askfiy** [comment]
okay, thank you.
