### ISSUE TITLE
Question: How to make this transparent?

### ISSUE THREAD

**Issue by bryant-the-coder** [akinsho/bufferline.nvim#363]
![image](https://user-images.githubusercontent.com/92417638/162136276-67a2310e-8eb7-47b8-82b7-5702693b5571.png)
how to make the rest of the line transparent?

**Comment by akinsho** [comment]
@bryant-the-coder I don't know how to do that, I don't use transparent settings in my terminal. Please have a look at all the highlighting in `:help bufferline-highlights` and try to find what works for you, or ask around.
