### ISSUE TITLE
[Bug]: nvim-bufferline.lua/lua/bufferline/utils.lua:238: attempt to index local 'opts' (a nil value)

### ISSUE THREAD

**Issue by LuYanFCP** [akinsho/bufferline.nvim#364]
### What happened?

```bash
Error executing vim.schedule lua callback: ...acker/start/nvim-bufferline.lua/lua/bufferline/utils.lua:238: attempt to index local 'opts' (a nil value)
stack traceback:
        ...acker/start/nvim-bufferline.lua/lua/bufferline/utils.lua:238: in function 'notify'
        ...cker/start/nvim-bufferline.lua/lua/bufferline/config.lua:165: in function <...cker/start/nvim-bufferline.lua/lua/bufferline/config.lua:163>
```
I made the following changes which resolved the issue

lua/bufferline/utils.lua:23
```lua
function M.notify(msg, level, opts)
  local nopts = { title = "Bufferline" }
  if opts and opts.once then
    return vim.notify_once(msg, level, nopts)
  end
  vim.notify(msg, level, nopts)
end
```

### What did you expect to happen?

only update bufferline using packer to latest version today.

### Additional Information

neovim env:
NVIM v0.7.0-dev+1400-g233014f92
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/ly/repos/github/neovim/build/config -I/home/ly/repos/github/neovim/src -I/home/ly/repos/github/neovim/.deps/usr/include -I/usr/include -I/home/ly/repos/github/neovim/build/src/nvim/auto -I/home/ly/repos/github/neovim/build/include
Compiled by ly@6G-KIN-PlatformA

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

**Comment by akinsho** [comment]
Should be fixed now thanks for reporting
