### ISSUE TITLE
[Question]: CycleNext when multiple groups

### ISSUE THREAD

**Issue by zbouslikhin** [akinsho/bufferline.nvim#370]
### What happened?

When having multiple groups, it seems like it's only possible to cycle through buffers of that group while the other groups are toggled off. 

### What did you expect to happen?

Is there anyway to cycle through all buffers regardless to the group they belong to?

### Additional Information

...

**Comment by akinsho** [comment]
@zbouslikhin I don't fully understand the problem you are describing. It should by default be possible to cycle into every buffer as long as the group it is in is not *hidden*, if it is hidden then by design you should not be able to cycle into it. If you want to be able to cycle into a group, then don't hide it.

**Comment by zbouslikhin** [comment]
Suppose we have two groups which are not hidden and contain the following buffers:
- Group A (Python):
  - my.py (we are currently modifying this file)
  - main.py
- Group B (JavaScript):
  - config.js
  - package.json 

At first, as all groups are not hidden, cycling use `BufferLineCycleNext` works fine, but once we are about to cycle to `config.js`, which is part of group B, for some reasons, group A hides automatically and can not be cycled through its content anymore. 

See screen capture below.

https://user-images.githubusercontent.com/47977073/162701000-8ade4a72-ecef-4023-8ef0-1d7686c6ac6a.mov

**Comment by akinsho** [comment]
@zbouslikhin can you share your bufferline config that produces this issue, groups should not hide automatically unless configured to do so

**Comment by akinsho** [comment]
@zbouslikhin can you share your config?

**Comment by zbouslikhin** [comment]
Sorry for the late answer.

This might not be relevant as I didn't notice that I have `auto_close = true` in the config of few of the groups. Switching it to false fixed the problem.
