### ISSUE TITLE
[Bug]: `handle_close_buffer()` not working anymore

### ISSUE THREAD

**Issue by ndom91** [akinsho/bufferline.nvim#374]
### What happened?

I have a remap to close the active buffer that looks like this:

```
noremap("<c-x>", '<cmd>lua require("bufferline").handle_close_buffer(vim.fn.bufnr("%"))<CR>')
```

(I searched through your source code and found a reference to "bufferline.utils" executing 'handle_buffer_close', so I tried that as well (`require("bufferline.utils")...`), but that didn't work either)

This worked fine the past few weeks / months. However, after a recent `:PackerSync` (update) around 1 week ago, this no longer seems to be a valid method.

I get the following error when executing the mapped shortcut:

![image](https://user-images.githubusercontent.com/7415984/163246646-ae1ffee8-d469-4c5e-884f-735b529a6bc3.png)

### What did you expect to happen?

Buffer should close

### Additional Information

...

### commit

Using `Packer` and setup like so:
```
use {
  "akinsho/bufferline.nvim",
  tag = "*",
  config = function()
    require "plugin_configs.bufferline"
  end
}
```
Pulled the latest updates just now, `~/.local/share/nvim/pack/packer/start/bufferline.nvim` says its at `874f869` (tag `1.1.1`).

Using `neovim` version `0.7.0-dev+714-g3aff3d634`

**Comment by akinsho** [comment]
@ndom91 apologies I renamed some functions to be more agnostic since I added tabpage support, but I had thought I had added in the old versions with a deprecation warning, but this missed my list. Can you try using `bufferline.handle_close` instead.

**Comment by ndom91** [comment]
Hi @akinsho, thanks for the quick response!

Unfortunately `bufferline.handle_close()` seems to throw the same error :/

![image](https://user-images.githubusercontent.com/7415984/163563695-c1c5e4eb-5ef1-4833-9476-dc329aa2bd8d.png)

Here's the mapping I'm attempting to use again for reference:

```
nnoremap("<c-x>", '<cmd>lua require("bufferline").handle_close(vim.fn.bufnr("%"))<CR>')
```

**Comment by akinsho** [comment]
@ndom91 what version of bufferline are you using? Is it definitely the most up to date? I just tested this locally on main on the latest commit, and it seems to work fine?

**Comment by ndom91** [comment]
@akinsho figured out the issue - I still had `"bufferline.utils"` in the require statement :facepalm:. Works like a charm now with `require("bufferline").handle_close(...` :tada:
