### ISSUE TITLE
[Feature Request] Delete multiple buffers based on file-type

### ISSUE THREAD

**Issue by madhurachanna** [akinsho/bufferline.nvim#381]
There is vim function to delete buffers based on file-type/extension
```
function! s:DeleteBufferByExtension(ext)
  let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) && bufname(v:val) =~ "\.'.a:ext.'$"')
  if empty(buffers) |throw "no *.".a:ext." buffer" | endif
  exe 'bd '.join(buffers, ' ')
endfunction

command! -nargs=1 DeleteBufferByExtension :call s:DeleteBufferByExtension(<f-args>)
```

It would be nice if we have this feature?

**Comment by akinsho** [comment]
Hi @madhurachanna,
so this plugin is not a buffer manager, it provides a nice UI for the tabline but does not take opening, closing or changing buffers except in very small ways such as a close button. I don't think this sort of command belongs in this plugin

**Comment by akinsho** [comment]
Going to close this out to ensure I don't forget too later as I don't think this is something that should be added to this plugin as I commented above. Anyone who wants this can use the function above in their config or they can use 
`:bd *.js<Tab>` which will expand to all js files and can use this pattern instead
