### ISSUE TITLE
[question] about number highlight group

### ISSUE THREAD

**Issue by shaeinst** [akinsho/bufferline.nvim#391]
what's the highlight group name for this number?
![image](https://user-images.githubusercontent.com/41078534/164284200-9bdd331c-b86e-4269-a0ce-839257c91d93.png)

**Comment by gegoune** [comment]
Was about to ask exactly the same question as with nightfox I am getting missing colouring for those. Tried
```
BufferLineNumbersVisible
BufferLineNumbersSelected
```
but couldn't get those numbers to appear any differently.

**Comment by akinsho** [comment]
You should configure the numbers highlighting through your config not be targeting the highlight groups. It should be numbers, numbers_visible etc in the highlights table

**Comment by akinsho** [comment]
Or it might be number singular please try both in not at my computer so you'll have to do some digging if not either.

**Comment by gegoune** [comment]
Hey Akin, I just tried, but doesn't seem to work:
<img width="159" alt="Screenshot 2022-04-20 at 20 18 10" src="https://user-images.githubusercontent.com/69750637/164286908-5ef330f0-3d38-49c0-8f64-c936812ddf2b.png">
<img width="435" alt="Screenshot 2022-04-20 at 20 18 21" src="https://user-images.githubusercontent.com/69750637/164286944-50403b9a-4e14-4eca-9bb2-43843847ab36.png">

**Comment by shaeinst** [comment]
didn't work
```lua
highlights = {
    numbers_visible = {
        guifg = {highlight = "TestBuffNum", attribute = "fg"},
        guibg = {highlight = "TestBuffNum", attribute = "bg"},
    },
}
```

**Comment by akinsho** [comment]
I just tested 
```lua
    highlights = {
      numbers = {
        guifg = 'red',
      },
    },
```
In  my config and this produces a red highlight, can you please check that the highlight group you are testing against has been correctly set. Try using a basic color like `red` or `blue` please. Also please be aware that `visible` if specifically for  a buffer open in another window but that is not focused. You need to set all three unless you don't want to for whatever reason.

**Comment by gegoune** [comment]
That makes sense, I have misunderstood those highlight groups then. It works when set up through `setup({highlighs={}}). Will try to make highlight groups work as well as I would like to have all highlighting done in single place (colorscheme).

Which brings me to ask this question: your plugin tries to theme itself based on current colorscheme, if one wants to make some changes `themable` is required, also plugin order seems to matter in that case as well. I am thinking if it's really worth it (I assume it is since you set it up like that in the first place)? Many plugins just leave theming to colorschemes.

**Comment by akinsho** [comment]
@gegoune I explained my rationale in another issue I'm on mobile so please like for the issue about default highlights. The entire point of this plugin's highlights is that they are supposed to be automatic. They are derived from existing native vim highlights plugins shouldn't have to change them at all the plug-in just picks colours from the available native vim groups and uses those

**Comment by shaeinst** [comment]
thanks. since problem is solved, we can close this issue.
