### ISSUE TITLE
Full path in table passed to matcher

### ISSUE THREAD

**Issue by gegoune** [akinsho/bufferline.nvim#393]
Hey Akin, I only got to try out tab groups now, pretty amazing! Great work.

I tried to get `matcher` match part of paths rather than specifying filenames. I have discovered that `path` key of a table passed to function for `matcher` is same as `filename` if given file is in root of `CWD`. With plugins changing `CWD` (like `project.nvim`)  matcher fails as soon as I select any buffer from such group. I assume it is done like tthatis by design so wondering whether there could be something like `fullpath` added always retaining full path.

Hope it makes sense.

**Comment by akinsho** [comment]
@gegoune you can get the full path using the buffer id and the expand function in vim e.g `vim.fn.expand("<buf_id>:p:h")`

**Comment by gegoune** [comment]
Thank you very much!

Got it working with
```lua
matcher = function(buf)
  return vim.fn.expand(vim.api.nvim_buf_get_name(buf.id) .. ':p:h'):match '/<myPattern>'
end,
```
