### ISSUE TITLE
[Question] Keeping buffers sorted

### ISSUE THREAD

**Issue by sbeyer** [akinsho/bufferline.nvim#394]
I want to keep my buffers in the bufferline sorted by tabs without calling `:BufferLineSortByTabs` (or its lua equivalent) after every window/tab action. What's the idiomatic/simplest way to achieve this?

Thank you!

**Comment by akinsho** [comment]
@sbeyer you should set the `sort_by` field in your config, please check the docs or readme for the option

**Comment by sbeyer** [comment]
Oops, how could I miss it 😱

**Comment by akinsho** [comment]
Will close this out then 👍🏾
