### ISSUE TITLE
Error with character pipe in bufferline.nvim 

### ISSUE THREAD

**Issue by GTG88Debian** [akinsho/bufferline.nvim#395]
To install bufferline.nvim I copied the recommended configuration, I got this error:

E5112: Error while creating lua chunk: /home/gtg/.config/nvim/lua/plugins.lua:174: '}' expected (to close '{' at line 
172) near '|'

I think it's related to the pipe character "|" but I don't know how to solve it. I'm using NVIM v0.7.0-dev

thanks in advance

**Comment by akinsho** [comment]
@GTG88Debian please do not copy and paste the configuration you do not need all of it please read the README carefully and only use the options you need

**Comment by GTG88Debian** [comment]
Ok, thanks for your answer
