### ISSUE TITLE
[Bug] Tab separator needs additional configuration to work

### ISSUE THREAD

**Issue by nitevatt** [akinsho/bufferline.nvim#396]
Hello, I have noticed that the tab separator accepts name as the first argument, while the pill separator accepts group, which is provided by default as the first argument. This results in tab separator not working by default.

So the README says:

https://github.com/akinsho/bufferline.nvim/blob/f02e19bd29a27944e6bcc1e7a492fe07534b6630/README.md?plain=1#L404-L406

But the actual configuration should look like this:

```lua
separator = {
  style = function(group, hls, count)
    return require("bufferline.groups").separator.tab(group.name, hls, count)
  end
}
```

Am I doing something wrong or this needs to be fixed? I think that either README or the tab separator function itself should be updated:

https://github.com/akinsho/bufferline.nvim/blob/f02e19bd29a27944e6bcc1e7a492fe07534b6630/lua/bufferline/groups.lua#L108-L114

**Comment by akinsho** [comment]
@nitevatt so the `tab` separator is very unloved and tbh should probably not be exposed as I haven't really spent as much time on it as the `pill` and probably gave myself more work than necessary by having two options out of the box. That being said I've fixed the issue on the `dev` branch in 3f855273cab29967bc454d3474224042815dd175 but I think in the long run I will need to think about if this second style is something I actually want to support
