### ISSUE TITLE
[Bug]: Symbol color cannot be modified

### ISSUE THREAD

**Issue by denstiny** [akinsho/bufferline.nvim#399]
### What happened?

The issue is that...
```lua
require("bufferline").setup{
  highlights = {
    fill = {
      guibg = bg,
    },
  },
  options = {
    show_close_icon = false,
    custom_areas = {
      left = function()
        local _mode_me = vim.fn.mode()
        local result = {}
        print(_mode_me)  -- print model name
        if _mode_me == 'n' then
          table.insert(result,{text = "   " , guifg = "#2C6881",guibg=bg})

        elseif _mode_me == 'i' then
          table.insert(result,{text = "   " , guifg = "#713A50",guibg=bg})

        elseif _mode_me == 'v' or _mode_me == 'V' then
          table.insert(result,{text = "   " , guifg = "#2ABCD7",guibg=bg})

        else
          table.insert(result,{text = "   " , guifg = "#713A50",guibg=bg})

        end
        return result
      end,
    }
  }
}
```

![图片](https://user-images.githubusercontent.com/57088952/165815036-29234f63-520b-4426-b273-d5d2d6a81d48.png)
****
I tried to make him modify the color of the ’ '  symbol according to my mode, but he was not effective.

### What did you expect to happen?

https://user-images.githubusercontent.com/57088952/165815519-12909506-2cc4-4187-a43a-ad0c66a13667.mp4

### Additional Information

...

**Comment by denstiny** [comment]
I don't understand, in the early version that is no problem

**Comment by denstiny** [comment]
Why do you want to delete it

**Comment by akinsho** [comment]
> I don't understand, in the early version that is no problem
Why do you want to delete it

@denstiny I don't really know exactly when you mean or which commit you are referring two. I genuinely don't have much of an idea of how to help. I haven't worked on custom areas in a long while, so 🤷🏾‍♂️ no idea why or when it would have changed.

**Comment by denstiny** [comment]
it can run very well

**Comment by denstiny** [comment]
> > 没看懂，早期版本没问题  
> > 为什么要删除它
> 
> @denstiny我真的不知道你的意思是什么时候或者你指的是哪个提交。 我真的不知道如何提供帮助。 我很久没有在自定义区域上工作了，所以🤷🏾‍♂️不知道为什么或何时会改变。
Well, you're doing great, thank you very much for your answer

**Comment by akinsho** [comment]
@denstiny I have *no idea* why that commit would have broken your custom area. All it did was load the plugin on startup like dozens of other plugins rather than delaying startup pointlessly to try to reduce startup cost, which was pretty silly to add in the beginning anyway 🤷🏾‍♂️. That commit doesn't even touch custom areas.

**Comment by akinsho** [comment]
This should be fixed in `dev` now
