### ISSUE TITLE
[Bug]: Custom area diagnostics incorrectly highlighted

### ISSUE THREAD

**Issue by jjc224** [akinsho/bufferline.nvim#401]
### What happened?

Upon opening a **second** file/buffer, the diagnostics in `custom_areas` are highlighted incorrectly.

As can be seen, the first buffer will have its diagnostics correctly highlighted, while the second does not (it should be green, not yellow):
<img width="938" alt="image" src="https://user-images.githubusercontent.com/14149636/166144124-853a7a4d-b62b-4491-ac89-3c483182d0a1.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/14149636/166144140-7eb74b7a-f29f-4af5-a810-5a3f9b9ca0c3.png">

I have tested this with various buffer contexts, and what I have observed is the diagnostics' highlights from the second buffer will be determined by those in the first buffer. For instance:
<img width="939" alt="image" src="https://user-images.githubusercontent.com/14149636/166144606-36bd1fb6-979c-42e3-a730-6ff773915acc.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/14149636/166144611-69b3a526-2c76-4956-ad88-d5466c07990b.png">

I can consistently reproduce this for any two or more files using a minimal config such as:
```Lua
require('bufferline').setup {
  options = {
    diagnostics = 'nvim_lsp',

    custom_areas = {
      right = function()
        local result = {}
        local seve    = vim.diagnostic.severity
        local error   = #vim.diagnostic.get(0, {severity = seve.ERROR})
        local warning = #vim.diagnostic.get(0, {severity = seve.WARN})
        local info    = #vim.diagnostic.get(0, {severity = seve.INFO})
        local hint    = #vim.diagnostic.get(0, {severity = seve.HINT})

        if error ~= 0 then
          table.insert(result, {text = "  " .. error, guifg = "#EC5241"})
        end

        if warning ~= 0 then
          table.insert(result, {text = "  " .. warning, guifg = "#EFB839"})
        end

        if hint ~= 0 then
          table.insert(result, {text = "  " .. hint, guifg = "#A3BA5E"})
        end

        if info ~= 0 then
          table.insert(result, {text = "  " .. info, guifg = "#7EA9A7"})
        end
        return result
      end,
    }
  }
}
```

### What did you expect to happen?

Correct `guifg` highlighting for given diagnostics for all buffers (not just the first buffer).

For the first example, the hint diagnostic should be green rather than yellow (which is the `guifg` set for warnings).
For the second example, the diagnostics should respectively be yellow and green (warning and hint).

### Additional Information

This occurs for me with the latest stable Neovim and latest bufferline as of this writing.
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by akinsho** [comment]
@jjc224 this is now fixed in `dev` you can test it out there.

**Comment by jjc224** [comment]
> @jjc224 this is now fixed in `dev` you can test it out there.

Looks good.

**Comment by intrntbrn** [comment]
This bug seems to be back.

![imgur-2023_09_25-18:57:33](https://github.com/akinsho/bufferline.nvim/assets/1234183/6a2390f9-e319-4cff-8be2-1b044f93c7f2)

I've noticed that the following highlights are created:
![imgur-2023_09_25-18:49:34](https://github.com/akinsho/bufferline.nvim/assets/1234183/437650dc-10a3-4776-9194-21f6378ac468)

It has nothing to do with colorschemes and also happens with the default theme.
