### ISSUE TITLE
[Bug]: Unexpected behavior of BufferLineCycleNext

### ISSUE THREAD

**Issue by askfiy** [akinsho/bufferline.nvim#416]
### What happened?

When using the `BufferLineCycleNext` command, there is some probability that two adjacent buffers will be swapped instead of moving the current buffer to the right.

### What did you expect to happen?

Move the current buffer to the right.

### Additional Information

Well, it really has this problem. But it is difficult to trigger, sometimes it is very frequent, sometimes it is normal.

So I can't provide a minimal configuration to reproduce it, it just has a chance to trigger.

It has happened 1-10 times a day for the last week.

I don't know if other users have encountered this problem...

**Comment by akinsho** [comment]
@askfiy it's going to be very hard to figure out what you're seeing, especially if it is not reproducible. At the very least can you please post your config, at least the relevant parts of it. Also, can you try on your side to figure out what the pattern is that reproduces it. There's very little chance I'll be able to fix this without clearer steps to reproduce.

**Comment by askfiy** [comment]
Well, it finally happened again.


![Peek 2022-05-14 14-13](https://user-images.githubusercontent.com/81478335/168413448-2599a637-645e-425b-adda-2454f0fc1170.gif)

Below is my configuration:

```
require("bufferline").setup({
    options = {
        numbers = "ordinal",
        indicator_icon = "▎",
        buffer_close_icon = "",
        modified_icon = "●",
        close_icon = "",
        left_trunc_marker = "",
        right_trunc_marker = "",
        -- diagnostics source
        diagnostics = "nvim_lsp",
        -- split style："slant" | "thick" | "thin" | { "|", "|" }
        separator_style = "thin",
        ---@diagnostic disable-next-line: unused-local
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
            local c = ""
            if diagnostics_dict.error then
                c = c .. icons.diagnostics.Error .. diagnostics_dict.error
            elseif diagnostics_dict.warning then
                c = c .. icons.diagnostics.Warn .. diagnostics_dict.warning
            elseif diagnostics_dict.info then
                c = c .. icons.diagnostics.Info .. diagnostics_dict.info
            elseif diagnostics_dict.hint then
                c = c .. icons.diagnostics.Hint .. diagnostics_dict.hint
            end
            return c
        end,
        offsets = {
            {
                filetype = "NvimTree",
                text = "File Explorer",
                highlight = "Directory",
                text_align = "center",
            },
            {
                filetype = "aerial",
                text = "Outline Explorer",
                highlight = "Directory",
                text_align = "center",
            },
            {
                filetype = "undotree",
                text = "Undo Explorer",
                highlight = "Directory",
                text_align = "center",
            },
            {
                filetype = "dbui",
                text = "Database Explorer",
                highlight = "Directory",
                text_align = "center",
            },
            {
                filetype = "spectre_panel",
                text = "Project Blurry Search",
                highlight = "Directory",
                text_align = "center",
            },
        },
    },
})
```

**Comment by askfiy** [comment]
I use `Manjaro`, the system kernel version is `5.15.38`, and the Neovim version is `v0.7.0`, the desktop environment is `dwm-6.3` do you need any other information?

**Comment by akinsho** [comment]
@askfiy a clear way to reproduce this would be the most useful thing, at the moment I see a bug you're describing but have zero way to make it happen on my end to fix it. Also, it's really important to clarify that you are using a *minimal* init.lua i.e you don't have conflicting mappings or plugins or things like that

**Comment by askfiy** [comment]
I think it might be caused by `session`. So I will close this question, thank you.
