### ISSUE TITLE
[Bug]: Custom separators having a weird "space"

### ISSUE THREAD

**Issue by rodhash** [akinsho/bufferline.nvim#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi

I changed the separators to this, a rounded one similar to what we have in groups:
`separator_style = {'', ''},`

It worked just fine as the print screen below, however in the current buffer I always get a "blank" space:
![image](https://user-images.githubusercontent.com/29671981/171525352-a8ffd4aa-fb7e-4ecf-a47d-984611520496.png)

### What did you expect to happen?

Expected behaviour: current buffer to not have this "blank" space.

All other buffers show up just fine, only the current one gets affected by this space.

### Config

```
require("bufferline").setup{
options = {
        -- numbers = "none",
        indicator_icon = '',
        buffer_close_icon = '',
        tab_size = 4,
        close_icon = '',
        left_trunc_marker = '',
        right_trunc_marker = '',
        modified_icon = '●',
        diagnostics_update_in_insert = false,
        show_buffer_icons = false,
        show_tab_indicators = true,
        persist_buffer_sort = true,
        separator_style = {'', ''},
        offsets = {{filetype = "NvimTree", text = "File Explorer" }},
        },
      }


```

### Additional Information

The only way I found to change this "blank" space was changing the color for the separator itself. So it seems to me this space is somehow linked to the separator:

https://user-images.githubusercontent.com/29671981/171526007-b41fbe4f-9b76-4603-a3a6-83478da52f2c.mp4

I tried other traditional colorschemes like gruvbox but no luck so far, checked the src code but couldn't find where this space is created.

Any suggestion pls?

Thank you

**Comment by rodhash** [comment]
Forgot to mention my env:

bufferline: `940a24c`
lualine: `c12b167`
packer: `4dedd3b`
nvim: NVIM v0.8.0-dev+124-g815b65d77

**Comment by akinsho** [comment]
@rodhash it doesn't look like you changed any of the highlights for the indicator? Can you try to change the indicator highlights for the selected buffer and see if that does what you want? Please read the docs to figure out how to do that, specifically the highlights section

**Comment by rodhash** [comment]
Sorry not sure what happend to my copy/paste but I actually have custom highlights groups set:

```
          highlights = {
            fill = {
              guifg = {attribute="fg",highlight="fillFg"},
              guibg = {attribute="bg",highlight="fillBg"}
            },
            background = {
              guifg = {attribute="fg",highlight="inactiveFg"},
              guibg = {attribute="bg",highlight="inactiveBg"},
              gui = "bold"
            },
            buffer_selected = {
              guifg = {attribute="fg",highlight="bufFg"},
              guibg = {attribute="bg",highlight="bufBg"},
              -- Updated: removing underline
              gui = "bold"
            },
            -- unsure
            -- buffer_visible = {
            --   guifg = {attribute="fg",highlight=""},
            --   guibg = {attribute="bg",highlight=""},
            -- },
            tab_selected = {
              guifg = {attribute="fg",highlight="tabSelFg"},
              guibg = {attribute="bg",highlight="tabSelBg"},
              gui = "bold"
            },
            tab = {
              guifg = {attribute="fg",highlight="inactiveFg"},
              guibg = {attribute="bg",highlight="inactiveBg"}
            },
            -- unsure
            -- duplicate_selected = {
            --   guifg = {attribute="fg",highlight="BufferLineDuplicateSelected"},
            --   guibg = {attribute="bg",highlight=""},
            --   gui = "italic",
            -- },
            duplicate_visible = {
              guifg = {attribute="fg",highlight="dupVisFg"},
              guibg = {attribute="bg",highlight="dupVisBg"}
            },
            -- unsure
            -- duplicate = {
            --   guifg = {attribute="fg",highlight="BufferLineDuplicate"},
            --   guibg = {attribute="bg",highlight=""},
            --   gui = "italic",
            -- },
            modified = {
              guifg = {attribute="fg",highlight="Search"},
              guibg = {attribute="bg",highlight="inactiveBg"}
            },
            modified_selected = {
              guifg = {attribute="fg",highlight="Search"},
              guibg = {attribute="bg",highlight=""}
            },
            modified_visible = {
              guifg = {attribute="fg",highlight=""},
              guibg = {attribute="bg",highlight=""}
            },
            separator = {
              --guifg = {attribute="fg",highlight="EndOfBuffer"},
              --guifg = {attribute="fg",highlight="LineNr"},
              guifg = {attribute="fg",highlight="SepFg"},
              guibg = {attribute="bg",highlight="SepBG"},
              gui = 'bold',
            },
            separator_selected = {
              guifg = {attribute="fg",highlight="sepSelFG"},
              guibg = {attribute="bg",highlight="sepSelBG"}
            },
            separator_visible = {
              guifg = {attribute="fg",highlight="sepSelFG"},
              guibg = {attribute="bg",highlight="sepSelBG"}
            },
            -- unsure
            -- indicator_selected = {
            --   guifg = {attribute="fg",highlight="Search"},
            --   guibg = {attribute="bg",highlight="Search"}
            -- },
            tab_close = {
              guifg = {attribute="fg",highlight="Search"},
              guibg = {attribute="bg",highlight="fillBg"}
            },
            buffer_visible = {
              guifg = {attribute="fg",highlight="bufVisFg"},
              guibg = {attribute="bg",highlight="bufVisBg"},
              gui = 'bold'
            },
           close_button = {
             guifg = {attribute="fg",highlight="inactiveCloseBtnFg"},
             guibg = {attribute="bg",highlight="inactiveCloseBtnGg"}
           },
           close_button_visible = {
             guifg = {attribute="fg",highlight="search"},
             guibg = {attribute="bg",highlight=""}
           },
           close_button_selected = {
             guifg = {attribute="fg",highlight="search"},
             guibg = {attribute="bg",highlight="bufBg"}
           },


          }
```

**Comment by rodhash** [comment]
Oh wait, I just realized that "blank" space is the `indicator_icon` ..

switching to "thin" or "thick" styles I'm able to properly change its highlight colors .. interesting that for slant or custom ones I'm having trouble .. doing some more checks.

**Comment by akinsho** [comment]
@rodhash this is generally by design, I didn't really build this plugin with people changing to custom separators in mind, I offered it only as an afterthought really. I built it with the default and offered alternatives in mind, I don't really optimize for custom use cases since I don't use any custom separators 🤷🏿‍♂️ but maybe you can change the indicator icon selected colour to match the rest of the background

**Comment by rodhash** [comment]
Thanks for the feedback, appreciate the details.

Alright I understand the idea and I'm good with this default value, was just playing around w/ different layouts and possible tweaks.

Thanks!

**Comment by rodhash** [comment]
One last update for future ref if helps .. I managed to make some chars work and others not.

So apparently it depends a bit on the char we use, I tried couple others without issue. That rounded one not sure what happened.

This one also works as expected:
![image](https://user-images.githubusercontent.com/29671981/171841138-7a00bb4e-1b5e-4230-b126-826d5a97f9b9.png)

So if someone else also tries to customize, apparently not all custom chars will fit properly .

**Comment by cdelledonne** [comment]
@rodhash may I ask you to post your configuration for the last screenshot? Thanks a lot :)

**Comment by rodhash** [comment]
Hi,

Sorry but I changed my config a few times after my last msg, currently I'm using a total different setup sorry. However the config is posted above in the first msg.

In that last msg however I had the following custom chars set:

`separator_style = {'', ''},`

It's a combination of two chars that make this bold italic space you saw in the above msg.

**Comment by rodhash** [comment]
In case your terminal can't render the above chars, try installing the Victor Mono font, this is what I'm using:

```
   ~
 _  kitty + list-fonts --psnames| grep Victor
VictorMono Nerd Font
    Victor Mono Bold Nerd Font Complete (VictorMonoNerdFontComplete-Bold)
    Victor Mono Italic Nerd Font Complete (VictorMonoNerdFontComplete-Italic)
    Victor Mono Light Nerd Font Complete (VictorMonoNerdFontComplete-Light)
    Victor Mono Medium Nerd Font Complete (VictorMonoNerdFontComplete-Medium)
    Victor Mono Regular Nerd Font Complete (VictorMonoNerdFontComplete-Regular)
    Victor Mono SemiBold Nerd Font Complete (VictorMonoNerdFontComplete-SemiBold)

```
