### ISSUE TITLE
How to chose custom icons Plugin ?

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [akinsho/bufferline.nvim#440]
Hi. I'd like to use 'ryanoasis/vim-devicons' instead of 'nvim-dev-icons' for your plugin.
Is it possible?
Thanks.

**Comment by akinsho** [comment]
@AndreSouzaAbreu I don't really provide first class support for the vim based devicons plugin but if you do not install the lua based one and have the vim based one then that should work if you have both installed then it will use the lua one. Sorry but I'm not going to go any further with support for the vim based one

**Comment by AndreSouzaAbreu** [comment]
Ok, got it. Thanks for the response!
