### ISSUE TITLE
[Feature Request]: selected tab indicator color

### ISSUE THREAD

**Issue by tobealive** [akinsho/bufferline.nvim#446]
### What?

Searching through the docs and attempting to change different highlight colors I couldn't find anything to adapt the selected tab indicator / separator color. It's always white _(top right of the screenshot. For clarification: its not a separator to the close button, the white line moves between the active tabs)_.
  
![Screenshot_20220608_195343](https://user-images.githubusercontent.com/34311583/172686582-6384d1fa-0f44-4a77-8646-346f167baca3.png)

This doesn't seem to be an issue when using nvim GUIs. But the issue persists in different TUIs. E.g., kitty, konsole, tilix. 

Something to add that's related not to the tab, but buffer indicator: Adding a `indicator_selected` highlight doesn't seem to change anything. I'm assuming this should target the selected buffers indicator _(the component whichs icon is defined by `indicator_icon`?)_.

### Why?

Just a tiny cosmetic issue with low priority, but might be a quick fix.

**Comment by akinsho** [comment]
@tobealive there shouldn't be any kind of visible line separator for the minimal tabs, i.e. it should just be a black line. All that should show is the colour of the selected one should change. I don't know why that looks white on your machine, frankly.

<img width="161" alt="image" src="https://user-images.githubusercontent.com/22454918/172690911-cf252645-3f4b-42c6-9ae5-6f8e7ad443db.png">

It's worth mentioning that I'm not aggressively tackling issues in this repo, as I need a bit of a break from nvim plugins. If you manage to dig in and find more info please share on here for future reference either way

**Comment by ZennMystic** [comment]
I hate to intrude in someone else post. Sorry if its rude. no offense. I don't know were else to turn. This post is similar to my issue.

I have set the tab up for errors:
`diagnostics = "nvim_lsp",
    diagnostics_indicator = function(count, level, diagnostics_dict, context)
    local icon = level:match("error") and " " or " "
        return " " .. icon .. count
    end`

It looks good:

![Selected](https://user-images.githubusercontent.com/35722455/177198601-74af0871-9606-4e9e-9872-fbb282fa8d59.png)

But is I switch to another tab and leave the error in. The Red turns green and looks ugly like this:

![unselect](https://user-images.githubusercontent.com/35722455/177198959-0f12e47e-6535-4dfd-9b46-e824b3b4034d.png)

How do I change it?  I can change the label/name of the tab and colour  using error {fg ... bg ... stuff} but not the error icon itself... 

Anyone help me?

**Comment by tobealive** [comment]
Yes of course.

To style the diagnostics, in your case the error you need to change the  guifg and guibg values in for `error_diagnostic` to your liking. The `<*>_diagnostic` highlights target just the diagnostic indicator icons and numbers. You have the same groups without `_diagnostic` that will change the highlighting of the filename when a diagnostic is present for that buffer. Of course may need to customize the highlights to the different states (selected / visible) to fit your liking.

You can check a bunch of options with `h: bufferline-highlights`

**Comment by tobealive** [comment]
To finish this issue. I found to solution not too long after opening, should have came back to this. 

Checking the source I found `separator_selected` is used here for this tab separator.

So when ones using a TUI client with transparency enabled setting the hl for this one will solve this.

I'll take the liberty to close this one as this is not an issue anymore.
