### ISSUE TITLE
Is There Any Guidance To Use Alternate styling In Bufferline?

### ISSUE THREAD

**Issue by MRVAX** [akinsho/bufferline.nvim#450]
I want to set the bufferline's tyling using as same as the examples in README.md, is there any examples?  
Maybe I have to change a new Terminal to using this feature? I'm use Gnome for linux and my terminal is Native Gnome Terminal too.

**Comment by akinsho** [comment]
@MRVAX I've documented in the README and in the help docs how to use alternate styling, I'm not sure what further guidance is needed. Other users seem able to get this working. This issue doesn't clarify any specific problems or config issue, I'm not sure what is expected here. Have you checked both sources of documentation I referenced

**Comment by MRVAX** [comment]
Sorry, It seems my configuration have some problem, appreciate for your reply <3, i would try to reconfig my file again.
