### ISSUE TITLE
[Bug]: closed buffers are displayed

### ISSUE THREAD

**Issue by trueegorletov** [akinsho/bufferline.nvim#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that when you install both [lualine](https://github.com/nvim-lualine/lualine.nvim) and bufferline it turns unable to get proper tab bar functionality as all closed tabs don't disappear from it.

![Screenshot 2022-06-17 at 17 58 56](https://user-images.githubusercontent.com/105159089/174331235-f863f1e7-1853-446f-be6c-337e95bd1651.png)

I can't say if it is really caused by conflict because I haven't checked bufferline itself as I initially thought it's lualine-side bug, but discovered this appears when you adding bufferline plugin to themed lualine.

### What did you expect to happen?

Expected behaviour is, clarify, to get rid of closed buffers in my bufferline.

### Config

vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()
    -- Packer itself
    use 'wbthomason/packer.nvim'

    --
    -- Lualine separated from everything other
    --
    use { 
        'nvim-lualine/lualine.nvim', 
        requires = { 'kyazdani42/nvim-web-devicons', opt = true },
    }

    use { 'akinsho/bufferline.nvim', requires = 'kyazdani42/nvim-web-devicons', }

    use 'tomasiser/vim-code-dark'
end)

require('lualine').setup { options = { theme = 'codedark' } }
require('bufferline').setup()

### Additional Information
I use neovim 0.7.0 stable with latest bufferline and lualine plugins and code-dark lualine theme installed from homebrew on macOS 12 Monterey.

**Comment by trueegorletov** [comment]
I have just checked and it seems that bug appears even without any other plugins except bufferline itself

**Comment by akinsho** [comment]
@trueegorletov I don't really understand the issue you are describing or how to reproduce it based on the information you have put here. I'm able to remove old buffers without issue and presumably since this logic hasn't changed for a very long time this is the case for most other users. So this likely means an issue in your config. Can you confirm that you have set `hidden` and clarify what you mean by closed buffer are displayed?

**Comment by trueegorletov** [comment]
I hope there is a misunderstanding because of some my mistake and this behaviour is expected by default, but this is what I meant: 

https://user-images.githubusercontent.com/105159089/174354232-6ae37ee7-cc27-4ea9-88bb-c6566ecab368.mp4

**Comment by trueegorletov** [comment]
Yeah, thanks for your reply, this really was my incomprehension, this was because of using default 'buffers' mode. Sorry for this stupid issue.
