### ISSUE TITLE
[Feature Request]: name_formatter for tabs mode

### ISSUE THREAD

**Issue by nullchilly** [akinsho/bufferline.nvim#454]
### What?

Currently `name_formatter` only works with buffer

```
name_formatter = function(buf)  -- buf contains a "name", "path" and "bufnr"
	return vim.t.cp_problem.name
end
```

### Why?

I would like to use tab mode for my competitive programming plugin only, for example:

![image](https://user-images.githubusercontent.com/56817415/174433421-f34ccf46-bb69-4f56-ae75-d6693b0d8167.png)

Would be nice as I am currently forced to code my own tabline just for the name_formatter

**Comment by nullchilly** [comment]
Also I would like to have a custom area on the right of the tabline like this

![image](https://user-images.githubusercontent.com/56817415/174433842-7cb50ec5-c5ec-49f2-b22c-91b5acc71250.png)

Would this be fine?
```lua
local res = test_status()
vim.o.tabline = _G.nvim_bufferline() .. res
```

**Comment by akinsho** [comment]
@nullchilly if you would like to add functionality to tabs you will need to contribute this yourself. I don't use tabs mode and so re-implementing buffer functionality for tabs depends *entirely* on tab users. See #400 or #430 for reference. This should be small to add and you can do it by copying the logic in `buffers.lua` to `tabs.lua` and apply it to the tab name.

Regarding the custom area, this is already supported please check the readme about `custom_areas`

**Comment by nullchilly** [comment]
Thanks, I will copy the logic, one question though
How can I set tab size based on the stylua.toml. Do I need to change it manually or parse the indent_width itself.

In the `custom_areas` readme:
```
Please note that this function will be called a lot and should be as inexpensive as possible so it does not block rendering the tabline.
```
How often will it redraw? I would like to call `redrawtabline` myself.

**Comment by akinsho** [comment]
@nullchilly you can either run `stylua` yourself in the CLI after installing it, or you can add stylua to your formatters for lua using something like `null-ls` the choice is yours. You shouldn't change the `stylua.toml` nor need to parse it in some way.

Re. the custom area, the advice is mainly about not trying to do some long processing or parsing a huge json or something. If you are just rendering some basic numbers, it should be fine. Also, you can call redrawtabline yourself at any point, but you don't need to unless you are doing something very custom. Nvim already call redraw very often.
