### ISSUE TITLE
[Feature Request]: Remove vimscript wrapper for click support

### ISSUE THREAD

**Issue by nullchilly** [akinsho/bufferline.nvim#456]
### What?

```
function Click(num, clicks, button, flags)
	print(num, clicks, button, flags)
end

vim.o.tabline = "%1@v:lua.Click@ Click"
```
This works

### Why?

No more https://github.com/akinsho/bufferline.nvim/blob/main/autoload/nvim_bufferline.vim

**Comment by akinsho** [comment]
@nullchilly have you tried the example in the snippet that you shared? Because I did a while ago, and it doesn't work. So neovim upstream have fixed it. It is still required to use a vim script wrapper

**Comment by nullchilly** [comment]
Yes it didn't work for 0.5

**Comment by akinsho** [comment]
Can you raise a PR? and I'll test it, if it works then I'll happily merge it 👍🏾

**Comment by nullchilly** [comment]
It will be merged to main when neovim 0.8 released

**Comment by akinsho** [comment]
Ah, thanks for the heads-up @nullchilly didn't realize it was 0.8 only, well it's in the dev branch for now

**Comment by nullchilly** [comment]
Fortunately I didn't break dozen people's workflow D:

**Comment by akinsho** [comment]
Gonna close this out since the work is technically done though 👍🏿
