### ISSUE TITLE
[Question] - Which highlight groups are the colors actually derived from?

### ISSUE THREAD

**Issue by Davincible** [akinsho/bufferline.nvim#462]
I've read a bunch of issues and docs about color changing, and you've often mentioned you want to derive the colors from the general theme but nowhere could I find _which_ highlight groups it's actually derived from.

I tried looking at the code but couldn't fine which highlight groups are pulled

**Comment by akinsho** [comment]
This is covered under `:help bufferline-colorscheme-development`

**Comment by Davincible** [comment]
Unfortunately, the docs only cover a limited number of groups. I'm looking to change the buffer text color of unselected buffers, as I don't like the current one, but none of the groups do the trick.

![image](https://user-images.githubusercontent.com/25869544/176694672-333e9e44-2a53-482c-99ff-684561b4cf6e.png)

**Comment by akinsho** [comment]
@Davincible all the highlights are in `:h bufferline-highlights` you will need to look very carefully to find which groups you need.

**Comment by akinsho** [comment]
@Davincible I really don't know all the highlight groups off the top of my head. Maybe you can try the background highlight group. You'll have to do a little trial and error on your side to figure this out.

**Comment by Davincible** [comment]
Alright
