### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by MangoJuiceee** [akinsho/bufferline.nvim#463]
### What?

How i can show diagnostics with coc linters from all tabs to this custom area in the left-side of bufferline?

<img width="1389" alt="Screenshot 2022-06-29 at 22 06 43" src="https://user-images.githubusercontent.com/72989195/176516374-18b0d6cb-2e05-4d5a-830d-a43a09bc2f1f.png">

### Why?

Why my custom area can't catch errors from coc diagnostics? What i doing wrong? I want show warnings and errors from all opened tabs in this session.
My bufferline config: 

```
lua << EOF
require("bufferline").setup {
	options = {
		numbers = "ordinal",
		separator_style = "slant",
		mode = "buffers",
		indicator_icon = '▎',
		buffer_close_icon = '',
		modified_icon = '●',
		close_icon = '',
		left_trunc_marker = '',
		right_trunc_marker = '',
		max_name_length = 18,
		tab_size = 25,
		show_close_icon = false,
		show_buffer_default_icon = true,
		show_buffer_close_icons = true,
		show_buffer_icons = true,
		show_tab_indicators = true,
		color_icons = true,
		diagnostics = "coc",

		diagnostics_indicator = function(count, level, diagnostics_dict, context)
			local icon = level:match("error") and " " or " "
			return " " .. icon .. count
		end,

		custom_areas = {
			right = function()
				local result = {}
				local seve = vim.diagnostic.severity
				local error = #vim.diagnostic.get(0, {severity = seve.ERROR})
				local warning = #vim.diagnostic.get(0, {severity = seve.WARN})
				local info = #vim.diagnostic.get(0, {severity = seve.INFO})
				local hint = #vim.diagnostic.get(0, {severity = seve.HINT})

				if error >= 0 then
					table.insert(result, {text = " " .. "  " .. error, guifg = "#EC5241", guibg = "#4C3C53",})
				end

				if warning >= 0 then
					table.insert(result, {text = "  " .. warning, guifg = "#EFB839", guibg = "#4C3C53",})
				end

				if hint >= 0 then
					table.insert(result, {text = "  " .. hint, guifg = "#A3BA5E", guibg = "#4C3C53",})
				end

				if info >= 0 then
					table.insert(result, {text = "  " .. info .. "   " ,guifg = "#7EA9A7", guibg = "#4C3C53",})
				end
				return result
			end,
		}
	}
}

require('bufferline').exec()
EOF
```

**Comment by akinsho** [comment]
@MangoJuiceee I'm not a coc user, so I don't know how you would do this. FWIW this is not quite a feature request or a bug but rather a configuration issue/question. I think this sort of issue is best solved by reading the docs of the plugin in question and trying to piece together a solution. Unfortunately, I'm worse placed to answer this question than you are, since I'm not even a user of the same plugin.

**Comment by akinsho** [comment]
Just FWIW using `vim.diagnostic.get` does not use CoC at all. You need to figure out how to get diagnostics for coc through some sort of function call and then add the values there. The custom area is intended as a tool for advanced users who are happy to put in some legwork to solve their issues. Unfortunately I personally can't help each person craft their own custom area
