### ISSUE TITLE
[Bug]: bad visual effect after open file

### ISSUE THREAD

**Issue by cathaysia** [akinsho/bufferline.nvim#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

please notice bufferline

https://user-images.githubusercontent.com/42114817/176996041-ab302624-98ac-4a2e-ba6d-0c2a374dcbd6.mp4

### What did you expect to happen?

a bufferline like this:

![图片](https://user-images.githubusercontent.com/42114817/176996025-d42bfd0f-e94b-41f1-ab04-fb4815ba09d1.png)

### Config

```lua
    bufferline.setup {
        options = {
            right_mouse_command = nil,
            middle_mouse_command = 'bdelete! %d',

            buffer_close_icon = '',
            modified_icon = '',
            close_icon = '',
            show_close_icon = false,
            left_trunc_marker = ' ',
            right_trunc_marker = ' ',
            max_name_length = 14,
            max_prefix_length = 13,
            tab_size = 20,
            show_tab_indicators = true,
            enforce_regular_tabs = false,
            view = 'multiwindow',
            show_buffer_close_icons = false,
            separator_style = 'thin',
            always_show_bufferline = true,
            diagnostics = 'nvim_lsp',
            themable = true,

            indicator_icon = '',
            show_buffer_icons = true,
            persist_buffer_sort = false,
            sort_by = 'id',
            diagnostics_update_in_insert = true,
            diagnostics_indicator = function(_, _, diagnostics_dict, _)
                local s = ''
                for e, n in pairs(diagnostics_dict) do
                    local sym = e == 'error' and '' or (e == 'warning' and '' or '')
                    s = s .. n .. sym
                end
                return s
            end,
            offsets = {
                { filetype = 'NvimTree', text = '文件浏览' },
                { filetype = 'vista_kind', text = '符号浏览' },
                { filetype = 'undotree', text = '文件历史' },
            },
            custom_filter = function(buf_number)
                local ft = vim.bo[buf_number].filetype

                if ft ~= 'qf' then -- 过滤掉 AsyncTask 的 build 窗口
                    return true
                end
            end,
        },
    }
```

### Additional Information

...

**Comment by akinsho** [comment]
@cathaysia this issue is quite unclear, I cannot at all tell from your video what is missing that you expect. Compared to the picture from the README you have not set numbers or close icons, but you are not using a minimal configuration but have copied a huge amount of the config, so you will need to figure out which options need to be turned on and off. This is not an issue with this plugin though but a configuration issue which should not be dealt with here

**Comment by cathaysia** [comment]
as you can see in this video, when I open two files, then bufferline just like this:

![图片](https://user-images.githubusercontent.com/42114817/177020998-f3816236-be78-4953-9237-b4bdfe0eff74.png)

and what I except is 
![图片](https://user-images.githubusercontent.com/42114817/177021010-25aee4c5-c593-4c83-921e-d3481f2da17a.png)

emm, or rather, all my tabs has one background color, but I want inactive tabs and active tabs to have different colors.

It looks like the problem is that the bufferline has some problems with the colors, if I use configuration below, then this problem will more clear:

```lua
    bufferline.setup {
        options = {
            separator_style = "slant",
            always_show_bufferline = false,
            themable = true,
        },
    }
```

![图片](https://user-images.githubusercontent.com/42114817/177021124-453972ee-3056-46f7-96af-bc3630160185.png)

**Comment by cathaysia** [comment]
I already know the reason for this bug is because I set colorscheme after loaded bufferline. Sorry
