### ISSUE TITLE
[Feature Request]: Add an option to disable italic in highlights

### ISSUE THREAD

**Issue by lcheylus** [akinsho/bufferline.nvim#475]
### What?

Thanks for your work on bufferline plugin, it's a must-have one to use Neovim.

I would like to have a config option to disable globally italic in highlight groups.

```
options = {
  gui_italic = true | false  -- disable italic in highlights groups
}
```

### Why?

In my daily use, I don't like graphic styles / GUI in bufferline with italic. In my configuration, I redefined highlight groups to disable italic (defined in `lua/bufferline/config.lua`): 

```
highlights = {
    buffer_selected = {
      gui = 'bold'  -- gui = "bold, italic" by default
    },
    numbers_selected = {
      gui = 'bold'
    },
    diagnostic_selected = {
      gui = 'bold'
    },
    error_diagnostic_selected = {
      gui = 'bold'
    },
    error_selected = {
      gui = 'bold'
    },
    warning_diagnostic_selected = {
      gui = 'bold'
    },
    warning_selected = {
      gui = 'bold'
    },
    info_diagnostic_selected = {
      gui = 'bold'
    },
    info_selected = {
      gui = 'bold'
    },
  }
```
I would like to have a config option to disable globally italic in highlight groups instead of redefining each one.

You can also add an config option to disable globally "bold" in highlight groups.

**Comment by akinsho** [comment]
Hi @lcheylus,

The number of options this plugin provides has gone absolutely crazy there are *way* too many IMO which increases the maintenance burden hugely. I'm very against adding new ones without a very good reason. I appreciate that some people may or may not like style x or feature x but tbh I can't easily accommodate everyone, as I mentioned in the README this plugin is __opinionated__ you can disable this highlights in your config as you've shown in this example, I think this is a much better solution that yet another option whilst parsing a users config to do x if y.

**Comment by lcheylus** [comment]
Hi @akinsho

OK, I understand perfectly your opinion. It's true that the number of options for your plugin are really (too) numerous.

Too bad because I had started to develop/test code in `lua/bufferline/highlights.lua` (function `convert_gui`) to send you a PR for my request.

Wontfix => close this issue.

**Comment by akinsho** [comment]
@lcheylus it might be useful to point out in working on a PR to pass on all the default highlights if highlights is specified as an option in this case a use can map through the highlights and set bold to false in a loop

**Comment by akinsho** [comment]
This will I believe give you an easy solution to disable all bold styling

**Comment by akinsho** [comment]
You can try https://github.com/akinsho/bufferline.nvim/pull/472 and see if disabling things in a loop works for you sorry there are no docs yet

**Comment by lcheylus** [comment]
Great, when your PR #472 is merged, it will be simple to define a function for highlights to suppress italic/bold style (gui) in every group where it's defined.

I'm waiting for your merge before testing it. I could document my solution here.

**Comment by akinsho** [comment]
@lcheylus better to test now if you can in case there are bugs or issues

**Comment by akinsho** [comment]
This is merged in to `dev` now, so feel free to try this out on that branch.

**Comment by lcheylus** [comment]
I updated my bufferline plugin with `dev` branch via Packer.

My `highlights` function to remove italic in gui for each group where it's defined : 

```lua
highlights = function(config)
  local hl = {}

  for name, tbl in pairs(config.highlights) do
    local tbl_copy = {}
    for k, v in pairs(tbl) do
      -- Modify gui to remove italic
      if k == 'gui' then
        local parts = vim.split(v, ',')
        for _, part in pairs(parts) do
          if part ~= 'italic' then
            tbl_copy['gui'] = part
          end
        end
      else
        tbl_copy[k] = v
      end
    end
    hl[name] = tbl_copy
  end

  return hl
end
```

With this function, my tests are OK : no side effect and italic removed in every highlight group (`buffer_selected, numbers_selected, diagnostic_selected`...)

**Comment by akinsho** [comment]
Oh that's kind of messy still I had forgotten that because bufferline long pre-dates `nvim_set_hl` users use `guifg` and a string `gui` field for their bufferlines, and under the hood I actually convert that to more approachable `bold = true` etc. This is a hard one to fix though since it will involve x number of people having to change their configs, which will be a pain.

At some point I guess I will want to introduce a deprecation, so highlights will be
```lua
{
  background = color,
  foreground = color,
  bold = false,
  italic = false,
}
```
this will make a map in this situation much simpler, but will need to go through the whole rigmarole of figuring out a deprecation strategy for the current highlight style 🤕
