### ISSUE TITLE
[Bug]: How can I render the bufferline transparent?

### ISSUE THREAD

**Issue by ArcticOc** [akinsho/bufferline.nvim#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to make bufferline transparent.
![Screenshot_20220715_132746](https://user-images.githubusercontent.com/43022588/179158195-257b6da9-e0c1-440e-a443-bb35e390bcd2.png)

now only the title is transparent.

### What did you expect to happen?

entire bufferline transparent

### Config

`vim.cmd[[hi NvimTreeNormal guibg=NONE ctermbg=NONE]]`
```lua
bufferline.setup {
  options = {
    close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
    right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
    offsets = {
    {
    filetype = "NvimTree",
    text = "",
    highlights = "NvimTreeNormal",
    padding = 1,
    }
  },
    separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
  },
    indicator_icon = '▎',
    buffer_close_icon = '',
    modified_icon = '●',
    close_icon = '',
    left_trunc_marker = '',
    right_trunc_marker = '',
   highlights = {
      background = {
         guibg = "NONE",
      },
      fill = {
         guibg = "NONE",
      },
      close_button = {
         guibg = "NONE",
      },
      separator_visible = {
         guibg = "NONE",
      },
      tab_close = {
         guibg = "NONE",
      },
   },
}
```

### Additional Information

...

**Comment by akinsho** [comment]
@ArcticOc I don't use transparency, so I can't give you an out-of-the-box answer. Other users of this plugin have been able to achieve this in their configs, you need to find every highlight group and set its background to none. If you are using `dev` you can specify the highlights option as a `function` and loop through it to set all `guibg` fields to `NONE` e.g. #475.

In either case this isn't a bug with this plugin and specific to your configuration for this plugin, so I'm going to close this out.

**Comment by Runeword** [comment]
Try this
 ```
require('bufferline').setup({
    options = {
      indicator_icon = ' ',
      separator_style = { '', '' },
      tab_size = 0,
      buffer_close_icon = '',
      modified_icon = '',
      close_icon = '',
    },
  })
  cmd([[
  autocmd ColorScheme * highlight BufferLineFill guibg=none
  autocmd ColorScheme * highlight BufferLineBackground guifg=#7a7c9e
  autocmd ColorScheme * highlight BufferLineBufferSelected guifg=white gui=none
  ]])
```
