### ISSUE TITLE
[Bug]: BufferLineGoToBuffer -1  not working

### ISSUE THREAD

**Issue by 8427003** [akinsho/bufferline.nvim#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BufferLineGoToBuffer -1  not working

### What did you expect to happen?

go to buffer last item

### Config

:BufferLineGoToBuffer -1 
can't working

### Additional Information

...

**Comment by akinsho** [comment]
@8427003 I've just tried this locally, and it works fine for me. Can you please clarify in detail what you mean when you say it doesn't work?

**Comment by 8427003** [comment]
sorry ，it is not a bug。i wan’t get the recently used item。i misunderstanding  the -1

**Comment by 8427003** [comment]
go to the item recently used, can support ? @akinsho

**Comment by akinsho** [comment]
@8427003 I don't really understand the feature request, if you want to go back to the alternate buffer I recommend using the builtin neovim mapping, `:help CTRL-^`. I'm going to close this since it's not really an/the issue and there is a neovim builtin to go to the last buffer
