### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chybl** [akinsho/bufferline.nvim#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever i close a buffer, the offset for NvimTree disappears.
it comes back when i open up anther buffer again.

### What did you expect to happen?

not to do what happened.

### Config

```
require('bufferline').setup {
    offsets = {{filetype = "NvimTree", text = "File Explorer"}}
}
```

### Additional Information

...

**Comment by akinsho** [comment]
@chybl this issue does not have enough information. I really can't get a clear sense of what exactly you are seeing. If nvim tree is the only buffer, then this will not work. The offset requires that the nvim tree buffer is full height and positioned on the left or right for it to work

**Comment by akinsho** [comment]
Please fill out clear information with a *minimal reproducible init.lua* otherwise I'll have to close this issue

**Comment by chybl** [comment]
Ok so whenever I have more than one buffer open, and I close the buffet I'm currently on, NvimTree gets expended to the whole screen and I don't see any buffers.

I would like it so that if I have multiple buffers open, and I close a buffer, it just opens the next available buffer or at least doesn't expand NvimTree.

I'm guessing this is more of a PEBKAC, but could you help me learn

**Comment by chybl** [comment]
Sorry, I'm on mobile and I accidentally closed.

**Comment by akinsho** [comment]
@chybl there are quite a few solutions to this problem online which you can find, I personally don't use nvim tree currently so don't have a solution for that. Maybe try doing something like `:bd | b#` to go to the alternate buffer, or maybe ask in that repo how other users are solving it. Tbh I think you should be able to find a solution looking online I don't have one readily available, and it isn't really the remit of this plugin.

**Comment by chybl** [comment]
ty!!
