### ISSUE TITLE
[Bug]:  attempt to call field 'notify_once' (a nil value)

### ISSUE THREAD

**Issue by dylode** [akinsho/bufferline.nvim#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that when I start neovim I get this error:

Error detected while processing /home/dylan/.config/nvim/after/plugin/bufferline.lua:
E5113: Error while calling lua chunk: ...ck/packer/start/bufferline.nvim/lua/bufferline/utils.lua:176: attempt to call field 'notify_once' (a nil value)
stack traceback:
        ...ck/packer/start/bufferline.nvim/lua/bufferline/utils.lua:176: in function 'notify'
        ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:265: in function 'setup'
        /home/dylan/.config/nvim/after/plugin/bufferline.lua:2: in main chunk

And it does not load. (I'm a beginner)

### What did you expect to happen?

Expected behaviour: It should not error and it should display the tabs

### Config

local use = require('packer').use
require('packer').startup(function()
  use 'wbthomason/packer.nvim' -- Package manager itself.
  use 'EdenEast/nightfox.nvim' -- Theme
  use 'itchyny/lightline.vim'  -- Status line
  use {'akinsho/bufferline.nvim', tag = "v2.4.0", requires = 'kyazdani42/nvim-web-devicons'}
end)

vim.opt.termguicolors = true
require("bufferline").setup{}

### Additional Information

...

**Comment by akinsho** [comment]
@dylode I believe `notify_once` was added in neovim `0.7`, this plugin only supports nvim 0.7+ can you please confirm that your neovim is up-to-date and that this error still persists?

**Comment by dylode** [comment]
> @dylode I believe `notify_once` was added in neovim `0.7`, this plugin only supports nvim 0.7+ can you please confirm that your neovim is up-to-date and that this error still persists?

Thank you. I was assuming I ran the newest neovim.
