### ISSUE TITLE
[Bug]: NvimTree offset not working

### ISSUE THREAD

**Issue by dylode** [akinsho/bufferline.nvim#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that the offset does not seems to be working for NvimTree.

![image](https://user-images.githubusercontent.com/78496445/182024953-81c11fec-045f-46bc-a751-83a113d801f2.png)

### What did you expect to happen?

Expected behaviour: it should offset the bufferline

### Config

```
require('bufferline').setup {
    options = {
        offsets = {
            {filetype = "NvimTree", text = "File Explorer", text_align = "left"}
        },
    }
}
```

### Additional Information

If I type echo &filetype in the NvimTree it shows "NvimTree"

I might be overlooking something again

**Comment by akinsho** [comment]
@dylode please have a very close look at the docs and your config, this feature definitely works as I use it daily. I'm not by a computer at the moment so can't dig in at the moment

**Comment by dylode** [comment]
> @dylode please have a very close look at the docs and your config, this feature definitely works as I use it daily. I'm not by a computer at the moment so can't dig in at the moment

For me layout[1] == leaf not row?

https://github.com/akinsho/bufferline.nvim/blob/main/lua/bufferline/offset.lua#L129

**Comment by akinsho** [comment]
@dylode this feature will only work if for *full height* windows if there are other buffers underneath nvim tree this feature will not work.

**Comment by dylode** [comment]
> @dylode this feature will only work for _full height_ windows if there are other buffers underneath nvim tree this feature will not work.

![image](https://user-images.githubusercontent.com/78496445/182122808-c383483f-f4f3-4be4-9681-b09e0fad1538.png)

I'm not running anything underneath nvim tree except for lualine.
![image](https://user-images.githubusercontent.com/78496445/182123126-927215da-32df-4506-8692-b91af38e80b8.png)
And if I disable lualine it's the same? Does that status line count as a buffer?

This is my config: https://github.com/dylode/nvim

**Comment by dylode** [comment]
> @dylode this feature will only work for _full height_ windows if there are other buffers underneath nvim tree this feature will not work.

I had to add the following to lualine config:
disabled_filetypes = {'NvimTree'}

and after I reinstalled the plugin it worked (also looks better)
Thanks.
