### ISSUE TITLE
[Feature Request]: show buffers in the current tab only

### ISSUE THREAD

**Issue by ofirgall** [akinsho/bufferline.nvim#494]
### What?

Show buffers that has been opened only in the current tabpage

### Why?

I use tabpage to create a new "window" in the same directory, when I have multiple tabpages the bufferline becomes irrelevant because it shows so many buffers that I don't intend to use in the current tabpage.

**Comment by akinsho** [comment]
Please have a look at https://github.com/tiagovla/scope.nvim which will solve your problem
