### ISSUE TITLE
[Question/feature request]: is there a way to only show buffers of the current tab?

### ISSUE THREAD

**Issue by najish-syncoria** [akinsho/bufferline.nvim#496]
I sometimes find it messy when buffers from different tabs gets mixed up. It would be convenient if there was a "both" mode to do that.

Or if there is already a way to do that manually.

**Comment by akinsho** [comment]
I've just added a section about this to the readme as this is the second request I've gotten about this in 2 days please use the plugin that I've mentioned in the README.
