### ISSUE TITLE
[Bug]: offset doesn't work with NvimTree

### ISSUE THREAD

**Issue by B4mbus** [akinsho/bufferline.nvim#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Offset doesn't work for NvimTree. 
![image](https://user-images.githubusercontent.com/75364377/184507986-69f3aa63-66c6-440d-8af8-3f1709aef655.png)
I've seen an issue in which the author of this plugin explains "this feature only works for full height windows". I have no idea what that means, but the offset never worked regardless of anything. The `File explorer` seen there is a winbar.

### What did you expect to happen?

Offset working.

### Config

This is my configuration:
```lua
require 'bufferline'.setup {
	options = {
		diagnostics = 'nvim_lsp',
	},
	offsets = {
		{
			filetype = 'NvimTree', 
			text = 'File Explorer',
			text_align = 'center'
		}
	},
}
```

### Additional Information

I'm on **Windows 10 Pro N**, the neovim version is **0.8.0-dev-788**, I'm running it from inside neovide, on nvim-qt it seems to work properly.

**Comment by akinsho** [comment]
@B4mbus unfortunately I get this issue on an almost weekly basis and there are quite a few like  it. From the above screenshot, it appears your configuration is set up incorrectly. You have placed the offsets key in the wrong place. Please have a careful look at the default configuration to see the correct structure.

**Comment by B4mbus** [comment]
@akinsho oh man :flushed: this is really my fault. Very sorry, you are right, works now. Thanks!
