### ISSUE TITLE
[Bug]: attempt to call local 'cmd' (a nil value)

### ISSUE THREAD

**Issue by ivanmoreau** [akinsho/bufferline.nvim#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I get this error when starting nvim:
```
Error detected while processing /Users/ivanmolinarebolledo/.config/nvim/init.v
im:
line   10:
E5108: Error executing lua ...al/share/nvim/plugged/bufferline.nvim/lua/buffer
line.lua:211: attempt to call local 'cmd' (a nil value)
stack traceback:
        ...al/share/nvim/plugged/bufferline.nvim/lua/bufferline.lua:211: in fu
nction 'setup_commands'
        ...al/share/nvim/plugged/bufferline.nvim/lua/bufferline.lua:264: in fu
nction 'setup'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

### What did you expect to happen?

It should work without the previous error.

### Config

This is my minimal .vimrc
```
set termguicolors
 
call plug#begin()
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/bufferline.nvim', { 'tag': 'v2.*' }
call plug#end()
 
lua << EOF
require("bufferline").setup{}
EOF
```

### Additional Information

I traced the error to a minimal example that causes it. Turns out that a version of Neovim of at least 0.7 is not enough. I had an old 0.7 nightly (NVIM v0.7.0-dev+1400-g233014f92) and it was giving me that error. After I updated to stable NVIM v0.7.2, it just worked.

Maybe it would be better to change the Readme so it requires a newer Nvim version?

**Comment by akinsho** [comment]
@ivanmoreau did you try a *stable* neovim 0.7, old nightlies are not guaranteed to work at all. The command I added is valid in stable neovim 0.7.

In general, when any plugin author refers to a point release e.g. 0.7 or 0.7.2 we mean *stable* not nightly. If you are ever using a nightly older than a week, I'd suggest nothing is guaranteed to work.

**Comment by ivanmoreau** [comment]
@akinsho my mistake, then. I did not. I had an outdated Brew version, with an outdated Neovim-nightly recipe.

I was using and old nightly because some plugin required for something that I don't remember. But it's not longer an issue.

But thank you for pointing it out.

Have a great day.
