### ISSUE TITLE
[Feature Request]: Keybinding for closing the current buffer

### ISSUE THREAD

**Issue by molsenhiq** [akinsho/bufferline.nvim#513]
### What?

I recently switched from barbar to bufferline and one of the features i'm missing is the ability to close the current buffer/tab with a keybinding.
I tried using :bd as suggested in a different issue. However that behaves differently by closing the entire "window" while barbar just switched to the next buffer/tab in the same window.

### Why?

Having a keybinding for closing the current tab/buffer (without closing the current window) is very convenient for de cluttering when you have lots of tabs open. Currently I've been using the mouse to right click on the tabs for closing them.

**Comment by akinsho** [comment]
@molsenhiq so a big difference between barbar and this plugin is that it dips its toes into buffer management, which this plugin explicitly does not do. I think it's a user's responsibility to decide how this sort of thing works, it also adds more of a maintenance burden for me. There are a lot of plugins that offer this functionality

* vim-bbye
* vim-sayonara
* nvim-bufdel
* https://github.com/famiu/bufdelete.nvim

**Comment by akinsho** [comment]
This plugin doesn't provide keybinds and probably never will

**Comment by molsenhiq** [comment]
Alright, thanks for links. I found this as well [LunarVim:bufferline.lua](https://github.com/LunarVim/LunarVim/blob/45f9825d1e666890ed37baf15a14707ae40e5cff/lua/lvim/core/bufferline.lua#L147-L219)

**Comment by akinsho** [comment]
Going to close this out now then, there's also some *very old* discussion in neovim to just add a command that allows a user to close a buffer without messing up the window layout but I think the biggest blocker is that no one has contributed a solution since this could very well be native, and we wouldn't need dozens of solutions to a super common use case

**Comment by codemang** [comment]
I have this in my vimrc from a while ago that works with this plugin as well:

```
  nmap <Space>q :bp <BAR> bd #<CR> " Close the current buffer tab
```
