### ISSUE TITLE
[Feature Request]: better modified icon behaviour/ options

### ISSUE THREAD

**Issue by joe23rep** [akinsho/bufferline.nvim#518]
### What?

first off english isnt my native language so please bare with me

now to my requests. 

first id like to see i smarter modified icon behaviour. what i mean is this:
go into a file and add a letter. remove that letter. your file is again like it was before, but bufferline still shows it as modified. i know it can be done since in lightline it works.

then it would really help if you could change the background for the modified icon. i have set up my bufferline this way that my bufferline is basically transparent and only the active buffer has a background. now when i have an inactive modified buffer it shows up transparent exept for the background of the modified icon

and lastly it would be nice if one could opt out of showing the modified icon all together. like i wrote above i have the modified status already in my statusline so theres no need to show it twice

heres a picture so you can understand what i mean a bit better
![Selection_001](https://user-images.githubusercontent.com/59401314/185769191-b3765d39-fea1-44ef-a754-2c7c581b8328.png)

### Why?

i think many people like to tinker with their setup and would like a bit more customizability

**Comment by akinsho** [comment]
@joe23rep you can change the background color of the modified icon using the `modified`, `modified_visible` and `modified_selected` highlights. Please check `:help bufferline-highlights` for details. Regarding the icon, you can just change it to an empty space `modified_icon = ' '` 🤷🏿.

Regarding changing the modified state without saving the file if you know how it is done please recommend a solution, I don't know how to do that and don't have time to start reading other plugins code to see how they do it. It's also not a big enough problem for me to warrant that.

**Comment by joe23rep** [comment]
thank you. ill do that
