### ISSUE TITLE
How to: Open nvim help in a new buffer instead of a split

### ISSUE THREAD

**Issue by CharlesARoy** [akinsho/bufferline.nvim#521]
Does Bufferline have a command that could be used to open the help in its own buffer?

Note, I've seen pages like [this](https://vi.stackexchange.com/questions/3716/open-help-windows-in-new-buffer-instead-of-split-windows) and [this](https://vi.stackexchange.com/questions/358/how-to-full-screen-browse-vim-help) which recommend using e.g. `<C-w> o` after opening the help, but that's not quite what I want. That is, I'd like the help to open in a new buffer automatically without having to type extra and I'd like to see the help in its own buffer, not as a maximized window.

If you know of a way to do this with Bufferline (or native vim commands), I'd be very grateful.

**Comment by akinsho** [comment]
Hi @CharlesARoy,

So I really don't think this issue actually relates to Bufferline at all. How the help buffer opens is really something for a user to sort out in their config, whereas this is just a plugin to provide nice visualization for buffers.

I'd recommend using some sort of autocommand or ftplugin file that used a `wincmd` to position the window as you please. In either case, I'm going to close this out, perhaps ask on reddit or the neovim matrix chat.
