### ISSUE TITLE
'indicator_icon' will be deprecated

### ISSUE THREAD

**Issue by shaeinst** [akinsho/bufferline.nvim#524]
full message:
```
'indicator_icon' will be deprecated: It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon'
```
there is no mention of this deprecation in [Announcements and Breaking Changes](https://github.com/akinsho/bufferline.nvim/issues/387). And as the error says `It should be changed to indicator and icon specified as indicator.icon, with indicator.style = 'icon'`, can i be certain with this statement?

**Comment by akinsho** [comment]
@shaeinst I maintain several plugins and have several announcement threads I simply forgot to update that one, but yes the deprecation warning is correct please also check the default config in `:help buffer-configuration`. if you are using a custom indicator it will need to changed to
```lua
config = {
  options = {
	indicator = {
      style = 'icon'
	  icon = '|',
    }
}
```

**Comment by akinsho** [comment]
> can I be certain with this statement?

Generally speaking such notifications are painstakingly written by me, you should always take those at face value more than any other source.

**Comment by shaeinst** [comment]
@akinsho i will, thanks.

**Comment by shaeinst** [comment]
i think there are some mistakes in code snippet (comma and close curly bracket missing) 
And in announcement threads, comma(,) is missing after `style='icon'`
```lua
config = {
  options = {
    indicator = {
      style = 'icon',
      icon = '|',
    }
  }
}

```
