### ISSUE TITLE
Settings don't work

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [akinsho/bufferline.nvim#529]
Hello, my settings for bufferline don't work i am using nvim 7.2 with init.vim 
i have this code for the setting up: `lua << EOF
require("bufferline).setup{}
EOF
let bufferline = get(g:, 'bufferline', {})
let bufferline.animation = v:true
let bufferline.closable = v:false
let bufferline.icon_separator_active = '▎'
let bufferline.icon_separator_inactive = '▎'
let bufferline.icon_close_tab = ''
let bufferline.icon_close_tab_modified = '●'
let bufferline.icon_pinned = '車'` 
But bufferline don't want to work with this settings.What i need to do?

**Comment by akinsho** [comment]
@Bogdan-Torkhov sorry but the code you have pasted is not really legible at all, but it looks pretty incorrect. None of it has been set up correctly. Can you please look at the documentation in `:help bufferline` to set things up correctly.

*Do no copy paste this*, it should look more like
```vim
lua << EOF
require('bufferline').setup {
	options = {
     -- Add options here
	}
	highlights = {
	 -- Add highlights here
    }
}
EOF
```

**Comment by Bogdan-Torkhov** [comment]
@akinsho can you send me all code with my settings?

**Comment by akinsho** [comment]
@Bogdan-Torkhov sorry but you should read through the documentation and figure out how to configure it properly, I can't write configs for all users. It's up to you to figure out how to make this plugin work. Please read through the documentation. If you do not need to configure anything special, then just use the defaults. The example below will load the defaults.

```vim
lua << EOF
require('bufferline').setup()
EOF
```

If you are having trouble understanding how set up lua plugins in neovim please read
`:help lua-heredoc`, I also recommend reading https://github.com/nanotee/nvim-lua-guide
