### ISSUE TITLE
[Feature Request]: Auto adjust tab size and auto rename tab filename

### ISSUE THREAD

**Issue by ray-x** [akinsho/bufferline.nvim#532]
### What?

I worked on some projects for most of the files in the projects have very long file names, e.g.

`international_address_suggestion_table.js`, `international_address_suggestion_table.spec.js`,  `international_address_mapping.js`,   `international_address_mapping.spec.js`, 

I have a tab size fixed to 18. But it is hard to tell which file I am working on if I open the above files.
I can reset the tab size to 32, but seems to waste lots of space.
There is an auto-resize feature in barbar.nvim. I think I would need something like that.

Also if it possible to condense the test file name?
e.g. If `international_address_mapping.js`,   `international_address_mapping.spec.js` are shown side by side,
we show 
| international_address_mapping.js | .spec.js|
Or something a-like. 

### Why?

It helps to improve ux in cases when multiple long file names looks similar.

**Comment by akinsho** [comment]
This is a reasonable request @ray-x especially if it blocks your work. I'll see about adding an auto-size option or something.

The thing about the files though I think is quite specific it's a nice to have for sure but I think it can be achieved by using the name formatter for test files in combination with a custom sorter i.e. you can write a sorting function that puts files with similar names together. If it works for you then we can add it to the wiki

**Comment by ray-x** [comment]
Thanks!
I will create name formatter function for now. I may going to transfer 
`international_address_mapping.js` -> `intaddmap....js` and
`international_address_mapping.spec.js` -> `intaddmap.spe....js`.

I think dynamic tab-size can be a good feature to bring into bufferline.

**Comment by akinsho** [comment]
@ray-x got a PR up for the auto sizing names behaviour can you try it and let me know

**Comment by akinsho** [comment]
closed by #533 feel free to open another issue for the tab navigation thing but please ensure the bug you're describing is clear 🙏🏿
