### ISSUE TITLE
[Bug]: Configs Not Sourcing Correctly

### ISSUE THREAD

**Issue by JBlocklove** [akinsho/bufferline.nvim#541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Only a few configs seem to work when I get the options using `require("bufferline").setup{}`. On its own it seems to be fine, but when I add options, most done seem to do anything. I added `indicator = { style = 'underline' },` which seemed to work, although it looked odd, but I also added `show_buffer_close_icons = false,` and the close icons are still there.

I eliminated all options other than not showing the buffer close icons and it still doesn't work. I tried this with several options and I don't think any are working quite right if at all.

### What did you expect to happen?

The bufferline should use the configs as they are defined.

### Config

This is the full section of my configs that I've tried.
```
require("bufferline").setup{
	options = {
		right_mouse_command = nil,
		left_mouse_command = nil,
		middle_mouse_command = nil,
		indicator = {
			style = 'underline' -- WORKING BUT DOESN'T LOOK RIGHT
		},
		diagnostics = false,
                offsets = {
                    {
                        filetype = "NvimTree",
                        text = "File Explorer",
				        highlight = "PanelHeading",
				        padding = 1,
                        separator = true,
                    },
                },
                show_buffer_close_icons = false, -- NOT WORKING
                show_close_icon = false, -- NOT WORKING
                separator_style = "slant", -- NOT WORKING
                sort_by = 'id',
        }
}
```

**Comment by JBlocklove** [comment]
I moved the configs over to where I add the plugin with `packer` and that seems to fix the issue for me, however I don't think that should be necessary so I'll leave the issue open until someone who understands this better than I can take a look.

**Comment by akinsho** [comment]
This issue does not appear to be due to a bug with this plugin, but rather about how things should be ordered when setting up plugins. As such, I'm going to close it out. In the case of packer, it is correct and expected that you setup the plugin in its config key. There are other ways to load plugins that ensure the correct order, but that is not an issue/discussion specifically for this plugin
