### ISSUE TITLE
Is there a way to make buffer ordering consistent with bufferline sorting?

### ISSUE THREAD

**Issue by omerdn1** [akinsho/bufferline.nvim#543]
Take the following scenario with custom option:
```lua
sort_by = "insert_after_current"
```
1. Open file_1
2. Open file_2
3. Navigate back to file_1
4. Open file_3

The buffer will show buffers as follows: file_1 → file_3 → file_2

The problem now begins when trying to navigate between the buffers.
If I execute `:bprevious` from file_3, I will be directed to file_2, instead of the more logical file_1.

This is happening because the buffer ordering is not consistent with the bufferline sorting.
`:ls` output:
```
1  "file_1"  
2  "file_2"
3  "file_3"
```

Is there a way currently to have the following enforced in the scenario above?
```
1  "file_1"  
2  "file_3"
3  "file_2"
```

**Comment by akinsho** [comment]
@omerdn1 you are expected to use bufferline's cycle commands if you are using bufferline's sorting since there is no way to make vim's internal sort order match

**Comment by akinsho** [comment]
See `:help bufferline-sorting` re. the commands you need to use. There is no way to change neovim's internal representation of buffers or it's order.

**Comment by omerdn1** [comment]
@akinsho Thank you for the quick response.
Unfortunately, the command `:help bufferline-sorting` gives no output
