### ISSUE TITLE
[Feature Request]: Show icon based on filetype instead of file extension

### ISSUE THREAD

**Issue by 4e554c4c** [akinsho/bufferline.nvim#549]
### What?

Sometimes two files which have the same extension have different filetypes.
I see this very often because I often write [hack](https://hacklang.org/) which can have the `.php` filetype even though it is an entirely different programming language.

This also occurs in vim when there is no filename attached to a buffer, but it still has a filetype.

### Why?

I often find myself editing buffers (either through a buffer without an attached file or a file with a different filetype than is ordinary) which have a different filetype than that associated with its filename's extension. I would like to be able to still have the correct icon shown in these situations without overriding the file extension globally.

**Comment by akinsho** [comment]
@4e554c4c please try the latest commit of the `dev` branch, this should now be fixed. I'll release this when next I get a chance
