### ISSUE TITLE
The append-on-right effect for newly opened buffer has disappeared

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#562]
As title. For append-on-right I meant opening buffer on the right of the current one.  I have a long time not following this plugin. And it seems that this amazing effect has gone. Could you provide some pointer to set this up?

**Comment by akinsho** [comment]
@nyngwang this functionality is provided by a sorter called `sort_by = 'insert_after_current'` please check the documentation for information like this in the future 🙏🏿
