### ISSUE TITLE
[Feature Request]: `BufferLineClose` command for closing the current buffer

### ISSUE THREAD

**Issue by Pocco81** [akinsho/bufferline.nvim#570]
### What?

A command for closing the current buffer (alternatively, it would be cool if you could expose a function for doing so)

### Why?

There's already `BufferLineCloseLeft` and `BufferLineCloseRight`. Makes sense to have one for closing the current buffer.

**Comment by akinsho** [comment]
@Pocco81 I've previously discussed this in several issues. Please have a look at previous discussions. In short, there are *dozens* of plugins that do this. This plugin's primary focus is *UI*, not buffer management. The only reason the alternate commands exist is that they are *only* possible through bufferline and tbh I should probably never have added them and stuck to UI only functionality.

https://github.com/akinsho/bufferline.nvim/issues/513
https://github.com/akinsho/bufferline.nvim/issues/311
https://github.com/akinsho/bufferline.nvim/issues/309

**Comment by akinsho** [comment]
Going to close this out as a duplicate, hopefully given the context of the previous issues and the explanation above, this makes sense. Personally I use `vim-bbye` but there are many Lua only alternatives for this.

**Comment by Pocco81** [comment]
Thanks for the reply!
