### ISSUE TITLE
[Bug]: Buffer still appears after clicking close button, clicking it again then gives error 

### ISSUE THREAD

**Issue by poetaman** [akinsho/bufferline.nvim#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that... Prior to reinstalling this plugin whenever I clicked on the close button (x) next to file name in the bufferline, it immediately closed the buffer and the file name immediately disappeared. Now the first time I click on the close button (x), visually nothing changes. bufferline does delete the file buffer, but it still appears in the bufferline till I open another do another action like move to another buffer. If one is to click the same close button again, then it gives an expected error which I have pasted below. This happens only if the close button is clicked for a buffer other than the one currently being seen in the window.

```
Error detected while processing function nvim_bufferline#handle_close_buffer:
line    1:
E5108: Error executing lua ....vim/plugged/bufferline.nvim/lua/bufferline/commands.lua:72: Vim(bdelete):E516: No
buffers were deleted: bdelete! 4
stack traceback:
        [C]: in function 'cmd'
        ....vim/plugged/bufferline.nvim/lua/bufferline/commands.lua:72: in function 'handle_user_command'
        ....vim/plugged/bufferline.nvim/lua/bufferline/commands.lua:86: in function 'handle_close'
        [string "luaeval()"]:1: in main chunk
Press ENTER or type command to continue
```

### What did you expect to happen?

Clicking close button next to a file name that is not currently the one focussed in window should immediately remove the file from the bufferline on top.

### Config

```
Plug 'kyazdani42/nvim-web-devicons'
Plug 'akinsho/bufferline.nvim', { 'tag': 'v2.*' }

lua require("bufferline").setup{}

if has('nvim')
lua << EOF
    require'bufferline'.setup {
        highlights = {
            fill = {
                fg = '#777777',
                bg = '#252525',
                },
            background = {
                fg = '#777777',
                bg = '#252525',
                },
            modified = {
                fg = '#777777',
                bg = '#252525',
                },
            modified_selected = {
                fg = '#ffd787',
                bg = '#303030',
                },
            buffer_selected = {
                fg = '#eeeeee',
                bg = '#303030',
                bold = true,
                italic = true,
                },
            close_button = {
                fg = '#777777',
                bg = '#252525',
                },
            tab_close = {
                fg = '#777777',
                bg = '#252525',
                },
            tab = {
                fg = '#b9b9b9',
                bg = '#252525',
                },
            tab_selected = {
                fg = '#368aeb',
                bg = '#303030',
                },
            close_button_selected = {
                fg = '#ffffff',
                bg = '#252525',
                },
            separator = {
                fg = '#252525',
                bg = '#252525',
                },
            separator_selected = {
                fg = '#252525',
                bg = '#252525',
                },
            indicator_selected = {
                fg = '#008400',
                bg = '#303030',
                },
            },
        }
EOF
endif
```

### Additional Information

...

**Comment by shaeinst** [comment]
can confirm.
but note that it happens when we try to close other buffer from current buffer

**Comment by lispyclouds** [comment]
For me its happening only after the nvim 0.8 upgrade and when I try to close a buffer which is not the current one.

**Comment by akinsho** [comment]
This is fixed in `dev` now please try out that branch to confirm. I'll merge that in later

**Comment by lispyclouds** [comment]
Works perfectly! Thanks for the quick fix! 🚀

**Comment by AnazThaj** [comment]
Works with the mouse click, however doesn't work when exiting by :q

**Comment by AnazThaj** [comment]
> This is fixed in `dev` now please try out that branch to confirm. I'll merge that in later

Works with the mouse click, however doesn't work when exiting by :q

**Comment by shaeinst** [comment]
`:q` quits the current window. use `:bd` instead
> Works with the mouse click, however doesn't work when exiting by :q
