### ISSUE TITLE
[Bug]: groups.lua, seems a miss spelling

### ISSUE THREAD

**Issue by Zero-Swangel** [akinsho/bufferline.nvim#578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

groups.lua, line 107
```
local indicator = {
    { higlight = hl, text = padding },
    { highlight = indicator_hl, text = padding .. group.name .. count .. padding },
    { highlight = hl, text = padding },
  }
```
new to lua and nvim, I think it's a miss spelling, but no bugs found

### What did you expect to happen?

highlight

### Config

...

### Additional Information

...

**Comment by akinsho** [comment]
@Zero-Swangel thanks for pointing this out I've just pushed a fix for the typo 👍🏿
