### ISSUE TITLE
[Enhancement]: Allow using 'insert_after_current' sort for tabs

### ISSUE THREAD

**Issue by alexventuraio** [akinsho/bufferline.nvim#584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I have two tabs opened and I move (focus) to the first one and the I create a new tab with `:tabnew` it creates the new tab at the very end of the tabs (in this case in the third place).

It looks weird that when you go to the next one you focus on the last one and the to the second one.

![tabs-error](https://user-images.githubusercontent.com/13169164/195228809-b6b6f898-0563-4774-a369-f008721f2133.gif)

### What did you expect to happen?

Since I'm in the first tab, I was expecting the new tab to be created right after the current one (second place in this example).

### Config

```vim
require('bufferline').setup({
  options = {
    mode = 'tabs',
    indicator = {
      style = 'underline',
    },
    diagnostics = 'nvim_lsp',
    offsets = {
      {
        filetype = "NvimTree",
        text = "פּ",
        text_align = "center",
        separator = true,
      }
    },
    show_tab_indicators = true,
    separator_style = 'slant',
  }
})
```

**Comment by akinsho** [comment]
@alexventuraio there is already a mechanism when using buffers mode to set the sort order to insert the new buffer after the current, like you describe. This mechanism will have to be adapted to work with tabs somehow. I'd suggest starting by looking in `sort.lua` and seeing how it works for buffers. It shouldn't be too hard to adapt for tabs by just passing a tabs current buffer in.

I personally don't use tabs mode, and features for tab mode are contributed by tab users, not by me. Feel free to raise a PR 🙏🏿

**Comment by rwblokzijl** [comment]
This is fixed in https://github.com/akinsho/bufferline.nvim/pull/592. When this hits `main` all tabs opened will be after the current one. Just like the vim builtin tabline.

**Comment by alexventuraio** [comment]
> This is fixed in https://github.com/akinsho/bufferline.nvim/pull/592. When merged into `main` all tabs opened will be after the current one. Just like the vim builtin tabline.

Sweet, thanks so much @rwblokzijl 

Is there any planning day for the next reales with this new fix?

**Comment by akinsho** [comment]
Just released your changes @rwblokzijl hoping this works but haven't tested personally. Will close this out unless someone reports back that it doesn't work 🤞🏿

**Comment by sheharyarn** [comment]
Just tried the new release out, and it's working beautifully! Thank you all!

**Comment by alexventuraio** [comment]
@rwblokzijl @akinsho I have recently updated to the latest version and now it is working as expected!
Thanks so much! ❤️
