### ISSUE TITLE
[Bug]: Bufferline does not refresh if BufferLineCloseLeft and BufferLineCloseRight are invoked using a keybinding

### ISSUE THREAD

**Issue by shans10** [akinsho/bufferline.nvim#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I directly use `BufferLineCloseLeft` or `BufferLineCloseRight` commands it closes the buffers to the left or right respectively and the bufferline is refreshed/redrawn to reflect those changes however when I invoke those commands using a keybinding, in my case `<leader>b[` and `<leader>b]` respectively then it does the job of closing the buffers however the bufferline is not redrawn to show the changes unless a new action or keybinding is invoked(just pressing the leader key does the job) however if I just keep on navigating up/down inside the buffer then the bufferline is not redrawn to show the changes.

### What did you expect to happen?

Bufferline should redraw as soon as the keybinding is invoked since it works without the keybinding.

### Config

local status_ok, bufferline = pcall(require, "bufferline")
if not status_ok then return end
bufferline.setup(tnvim.user_plugin_opts("plugins.bufferline", {
  options = {
    offsets = {
      { filetype = "NvimTree", text = "File Tree", highlight = "PanelHeading", padding = 1 },
      { filetype = "neo-tree", text = "File Tree", highlight = "PanelHeading", padding = 1 },
      { filetype = "Outline", text = "", padding = 1 },
    },
    show_close_icon = true,
    max_name_length = 14,
    max_prefix_length = 13,
    tab_size = 20,
    separator_style = "thin",
    show_duplicate_prefix = false,
  },
}))

### Additional Information

NVIM v0.8.0
OS: Arch Linux

**Comment by eXvimmer** [comment]
I have the same issue as well. This happened (I think) after upgrading to neovim 0.8 LTS.

**Comment by akinsho** [comment]
This fix is now merged into main in tag v3.0.0
