### ISSUE TITLE
Round corner style and off and on Bufferline

### ISSUE THREAD

**Issue by RicardoRien** [akinsho/bufferline.nvim#593]
It is possible style tabs with round corners like when we make groups?
Another question, It is possible display **on** and **off** all Bufferline? In order to create a full _Zen Mode_
![image](https://user-images.githubusercontent.com/55299652/197365820-bebe89f1-b5ab-484c-b147-503a558a2eeb.png)

Thanks in advance

**Comment by akinsho** [comment]
@RicardoRien you can change the `separator_style` and then tweak the highlights to try and get this styling, but it isn't officially supported via an option and I likely won't add it. You can hide the tabline by using `:help showtabline` please read through that option for more info
