### ISSUE TITLE
[Bug]: Bright foreground color being applied to active tab instead of filename

### ISSUE THREAD

**Issue by gallor** [akinsho/bufferline.nvim#597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that the foreground color to the active tab is a bright highlight. I can directly modify it via the highlight groups but I have been unable to get it just "work" out of the box. I have tried under multiple colorschemes (monokai, hybrid, firewatch, evening) and even with a fully stripped vimrc that only included loading the plugin and dev-icons, setting the termguicolors and registering the 2 plugins. I'm using a patched font (InconsolataGo) and have tried on both Mac on iTerm2 (the nerd font is selected) and on Ubuntu terminal (also with nerd font Inconsolata). Am I missing some kind of configuration? Thanks!
![SCR-20221027-nj7](https://user-images.githubusercontent.com/4968271/198407676-469a8959-e847-4682-8368-d87a1ca71f4d.png)

### What did you expect to happen?

Expected behaviour:
To not have the bright background and instead have the text turn that color.

### Config

" This is a barebones vimrc that I used to still recreate the issue in iTerm2 on OSX
set termguicolors
call plug#begin('~/.local/share/nvim/plugged')
Plug 'kyazdani42/nvim-web-devicons' " File icons for explorer
Plug 'akinsho/bufferline.nvim', { 'tag': 'v3.*' }
Plug 'rakr/vim-two-firewatch' " colorscheme for example
call plug#end()
colorscheme two-firewatch
:lua require('nvim-web-devicons').setup{}
:lua require('bufferline').setup{}

### Additional Information

...

**Comment by akinsho** [comment]
@gallor this seems very likely to be a configuration rather than a plugin issue. Are you using `tmux`? That can often cause highlighting issues.

**Comment by akinsho** [comment]
@gallor I don't think specific tmux fixes should go in the README since not everyone uses that myself included. You could add any info to the wiki but tbh I find tmux stuff changes and this information is already spread out in blogs
