### ISSUE TITLE
Open multiple tabs causes lagging

### ISSUE THREAD

**Issue by TroyCode3** [akinsho/bufferline.nvim#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When a open multiple tabs in the same project, bufferline starts causing lagging, even when I did nothing else but just writing code. FYI: I use :BufferLineSortByTabs

### What did you expect to happen?

Opening multiple tabs shouldn't cause significant lagging.

### Config

lua << EOF
require("bufferline").setup{
options = {
  mode = "tabs",
  numbers = "ordinal",
  }
}
EOF

### Additional Information

...

**Comment by rwblokzijl** [comment]
1. What is the minimum number of tabs that causes lag?
2. Does the issue persist when:
	a. using `sort_by = "id"`?
	b. not using `BufferLineSortByTabs`?  (`sort_by = "tabs"` solves the same problem)

**Comment by TroyCode3** [comment]
1. The minimum was 4.
2.
a. It still persists.
b. It also still persists.

**Comment by rwblokzijl** [comment]
Can you provide a minimum neovim config (without any other plugins) that replicates the problem?

**Comment by TroyCode3** [comment]
Sorry, it might not be your plugin's problem. When I tested my plugins individually, everything was smooth, but when I combined then together, it started lagging.

**Comment by rwblokzijl** [comment]
Ok, no worries :)

**Comment by akinsho** [comment]
Will close this out in this case 👍🏿 thanks for jumping in @rwblokzijl 🙌🏿
