### ISSUE TITLE
[Bug]: Modify indicator not inside buffer tab

### ISSUE THREAD

**Issue by huyhoang8398** [akinsho/bufferline.nvim#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The modify indicator not inside buffer tab
![image](https://user-images.githubusercontent.com/25379882/198975278-0d76c7b7-00ff-47ac-93ce-2c1cdae79af2.png)

### What did you expect to happen?

Modify indicator has same background color as buffer tab

### Config

local status, bufferline = pcall(require, "bufferline")
if (not status) then return end

bufferline.setup({
  options = {
    show_buffer_close_icons = false,
    show_tab_indicators =  false, 
    show_close_icon = false,
    color_icons = true,
  },
  highlights = {
    background = {
      bg = '#061115',
      fg = '#D9D7D6',
    },
    buffer_selected = {
      bg = '#f6dc95',
      fg = '#061115',
      bold = true,
    },
    buffer_visible = {
      bg = '#0D181C',
      fg = '#D9D7D6',
    },
    modified = {
      bg = '#061115',
      fg = '#D9D7D6',
    },
    modified_visible = {
      bg = '#f6dc95',
      fg = '#061115',
    },
    modified_selected = {
      bg = '#f6dc95',
      fg = '#061115',
    },
    fill = {
      bg = '#061115'
    }
  },
})

### Additional Information

...

**Comment by akinsho** [comment]
@huyhoang8398 the indicator is inside the tab, the issue is that you have not actually changed the highlighting for the entire tab. You have only changed the highlighting for the name section. You need to change all the highlights that constitute a buffer tab if you intend to change the colors properly.
