### ISSUE TITLE
X button does nothing, looks like a close button, how do i make it work?

### ISSUE THREAD

**Issue by OldWorldOrdr** [akinsho/bufferline.nvim#604]
![Screenshot from 2022-11-01 21-34-11](https://user-images.githubusercontent.com/57970114/199374419-e9cd3407-bcd7-4b9b-9670-6c592d72c4c3.png)

**Comment by OldWorldOrdr** [comment]
if someone wants to tell me how to fix the red highlights in my vim config while im here that would be greatly appriciated

**Comment by OldWorldOrdr** [comment]
litterally just noticed the gaps in the lualine segments arent colored correctly

**Comment by akinsho** [comment]
The button you are pointing to closes tabs not buffers. I can confirm that it does work but in your screenshot there are no tabs so it won't do anything

**Comment by travatomic** [comment]
@OldWorldOrdr regarding the red in your lua heredoc. I had this issue as well when i was using viml. I fixed it by moving the lua code to a separate file (`.config/nvim/lsp.lua` in my case), and then referencing it from init.vim using:
```
lua require('lsp') 
```

**Comment by OldWorldOrdr** [comment]
> @OldWorldOrdr regarding the red in your lua heredoc. I had this issue as well when i was using viml. I fixed it by moving the lua code to a separate file (`.config/nvim/lua/lsp.lua` in my case), and then referencing it from init.vim using:
> ```
> lua require('lsp') 
> ```

Not the solution I would have liked but it works.  Thanks
