### ISSUE TITLE
[Bug]: Changed background of Buffer lines

### ISSUE THREAD

**Issue by OlegGulevskyy** [akinsho/bufferline.nvim#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After updating the package, my background color changed from being transparent like the rest of the screen, becoming completely grey
![image](https://user-images.githubusercontent.com/43781031/199621946-593c0405-0080-4889-8fab-711cac5b0a1c.png)

### What did you expect to happen?

Colors not changing when updates are done

### Config

```
local status_ok, bufferline = pcall(require, "bufferline")
if not status_ok then
  return
end

bufferline.setup {
  options = {
    close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
    right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
    offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
    separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
  },
  highlights = {
    fill = {
      fg = { attribute = "fg", highlight = "#ff0000" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },
    background = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },

    buffer_visible = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },

    close_button = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },
    close_button_visible = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },

    tab_selected = {
      fg = { attribute = "fg", highlight = "Normal" },
      bg = { attribute = "bg", highlight = "Normal" },
    },
    tab = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },
    tab_close = {
      fg = { attribute = "fg", highlight = "TabLineSel" },
      bg = { attribute = "bg", highlight = "Normal" },
    },

    duplicate_selected = {
      fg = { attribute = "fg", highlight = "TabLineSel" },
      bg = { attribute = "bg", highlight = "TabLineSel" },
      underline = true,
    },
    duplicate_visible = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
      underline = true,
    },
    duplicate = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
      underline = true,
    },

    modified = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },
    modified_selected = {
      fg = { attribute = "fg", highlight = "Normal" },
      bg = { attribute = "bg", highlight = "Normal" },
    },
    modified_visible = {
      fg = { attribute = "fg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },

    separator = {
      fg = { attribute = "bg", highlight = "TabLine" },
      bg = { attribute = "bg", highlight = "TabLine" },
    },
    separator_selected = {
      fg = { attribute = "bg", highlight = "Normal" },
      bg = { attribute = "bg", highlight = "Normal" },
    },
    indicator_selected = {
      fg = { attribute = "fg", highlight = "LspDiagnosticsDefaultHint" },
      bg = { attribute = "bg", highlight = "Normal" },
    },
  },
}
```

### Additional Information

...

**Comment by akinsho** [comment]
@OlegGulevskyy it looks like you are tweaking the bufferline highlights to a different colour. This issue can probably be fixed by finding the right highlight group name and finding the colour you need to set for it. It's a configuration issue rather than a bug in the plugin. Please look carefully at your highlights and find the right one you need to change

**Comment by OlegGulevskyy** [comment]
Ok but no changes were made to the config in the past month, that's whats weird. Literally came from holidays, updated plug-ins and got this weird look

**Comment by akinsho** [comment]
@OlegGulevskyy a lot of things can be impacting this e.g. a change to your colorscheme etc. it could also be that the previous way you set highlights was invalid and since any number of updates it has changed. In short a user has the ability to change the bufferline background and there is a highlight group to do that. It is up to the user to choose whatever colour they want that works for them.

**Comment by euh2** [comment]
> @OlegGulevskyy a lot of things can be impacting this e.g. a change to your colorscheme etc. it could also be that the previous way you set highlights was invalid and since any number of updates it has changed. In short a user has the ability to change the bufferline background and there is a highlight group to do that. It is up to the user to choose whatever colour they want that works for them.

What is the name of the higlight group which fills the whole line? I experienced the same as OP.

**Comment by nachovizzo** [comment]
@OlegGulevskyy I managed to solve it with

```lua
	highlights = {
    fill = {
      bg = {
        attribute = "bg",
        highlight = "Pmenu"
      }
    }
	},
```

**Comment by atoder** [comment]
> 

Thank you! Changing most of the highlights from Tabline to Pmenu fixed a lot of colorscheme problems
