### ISSUE TITLE
[Bug]: Highlights are not applying

### ISSUE THREAD

**Issue by OlegGulevskyy** [akinsho/bufferline.nvim#608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am trying to fix look of bufferline that I raised [in here](https://github.com/akinsho/bufferline.nvim/issues/605), but it seems like I cannot even change colors properly, at this stage I am not even sure how to customize this.

Here is the config I am attempting to use
```lua
local status_ok, bufferline = pcall(require, "bufferline")
if not status_ok then
	return
end

bufferline.setup {
	options = {
		close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
		right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
		offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
		separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
	},
	highlights = {
		separator_selected = {
			fg = "#ffd43b",
			bg = "#ffd43b",
		},
		separator_visible = {
			fg = "#ffd43b",
			--[[ bg = '<colour-value-here>' ]]
		},
		separator = {
			fg = "#ffd43b",
			--[[ bg = '<colour-value-here>' ]]
		},

	}
}

```

Which results in this
![image](https://user-images.githubusercontent.com/43781031/200179851-bc335cc1-1afa-4999-8c19-c284aab4eaee.png)

### What did you expect to happen?

I expect `highlights` group to change their respective categories.
For example, here I set to `separator_selected` a yellow color ( `#ffd43b` ) and expect when a tab is selected, the color to change. Right now, it's black and nothing seems to change it.
This relates to pretty much to every property that I try - they do not change the colors at all, with exception of few - like all I manage to change is the color of separator really, but no tab colors, no font colors, no separator colors, nothing changes.

How can I debug this?

### Config

```lua
local status_ok, bufferline = pcall(require, "bufferline")
if not status_ok then
	return
end

bufferline.setup {
	options = {
		close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
		right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
		offsets = { { filetype = "NvimTree", text = "", padding = 1 } },
		separator_style = "thin", -- | "thick" | "thin" | { 'any', 'any' },
	},
	highlights = {
		separator_selected = {
			fg = "#ffd43b",
			bg = "#ffd43b",
		},
		separator_visible = {
			fg = "#ffd43b",
			--[[ bg = '<colour-value-here>' ]]
		},
		separator = {
			fg = "#ffd43b",
			--[[ bg = '<colour-value-here>' ]]
		},

	}
}
```

### Additional Information

...

**Comment by trankchung** [comment]
Do you have `vim.o.termguicolors = true` in your config? It works fine for me.

**Comment by akinsho** [comment]
I unfortunately do not have the time to personally debug highlight related issues like this as there are unfortunately way too many of them which usually relate to a user's config and settings. I'm able to see that highlights work and apply for me locally and the tests for highlighting are all passing so I'll close this out as this is likely a user config issue
