### ISSUE TITLE
[Question]: How to adjust the underline thickness?

### ISSUE THREAD

**Issue by ricbermo** [akinsho/bufferline.nvim#611]
### What?

Hi, 
Thanks for taking your time to create this amazing peace of software.

I'm trying to adjust the underline thickness, just like your "kitty" example, but I have not been able to. I've tried adjusting the `indicator` setting w/o luck. Would you mind pointing me in the right direction?

Thanks in advance

**Comment by akinsho** [comment]
@ricbermo there is documentation on kitty's website please have a look at https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.modify_font (in general questions like this are better suited to kitty's repo or looking at it's docs not here please)

**Comment by ricbermo** [comment]
@akinsho thanks for sharing the link. I honestly thought it was a bufferline config.
