### ISSUE TITLE
[Question] Need help identifying plugin and colorscheme

### ISSUE THREAD

**Issue by avatus** [akinsho/bufferline.nvim#615]
Hello all, just a quick couple of questions.

I was wondering what plugin provides that 'breadcrumb' line right under the bufferline in the hover state preview here
https://user-images.githubusercontent.com/22454918/189106657-163b0550-897c-42c8-a571-d899bdd69998.gif

Also, does anyone know which colorscheme is present in that same preview? 

Thanks!

**Comment by rwblokzijl** [comment]
It might be [Barbecue.nvim](https://github.com/utilyre/barbecue.nvim)

**Comment by akinsho** [comment]
The colorscheme is horizon.nvim and the winbar is a mixture of data from nvim-navic and local customizations I made
