### ISSUE TITLE
[Feature Request]: Add underline_indicator sp option

### ISSUE THREAD

**Issue by nullchilly** [akinsho/bufferline.nvim#617]
### What?

Currently underline_sp is set to TabLineSel.bg

https://github.com/akinsho/bufferline.nvim/blob/7c07dee2714778a84a9adda6e676c8e2151085f2/lua/bufferline/config.lua#L370-L373

Which means I have to do
```lua
TabLineFill = { bg = cp.black }
```

in order to set

![image](https://user-images.githubusercontent.com/56817415/201733790-4fdbd109-9f5e-4e06-92df-c362412bb54a.png)

### Why?

Currently `highlights.indicator_selected` only accept `fg` and `bg` option

TabLineSel isn't exclusive to bufferline.nvim, setting bg to a bright color will break vanilla tabline behavior:
![image](https://user-images.githubusercontent.com/56817415/201734023-20f41ff4-ac29-41eb-ae2d-e454c3a1a40d.png)

It doesn't hurt to add sp to `indicator_selected`:
```lua
require("bufferline").setup { highlights = { 
  indicator_selected = { sp = "#F5C2E7" }
} }
```

**Comment by ratheesh** [comment]
@nullchilly, I believe it is already there

![image](https://user-images.githubusercontent.com/70958/203227389-e482bf2d-523f-4876-8c1d-e7cd77b5214c.png)

PS: you can ignore other field such fg and bg.

**Comment by ratheesh** [comment]
@nullchilly, In my configuration, I am setting underline attribute only in `indicator_selected`. It works fine for me as shown in the previous screenshot.
Here is my bufferline config file.
https://github.com/ratheesh/dot-nvim/blob/main/nvim/nvim/lua/plugins/bufferline.lua

I hope this helps.
