### ISSUE TITLE
[Bug]: Not working with session manager

### ISSUE THREAD

**Issue by ShiChenCong** [akinsho/bufferline.nvim#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Open two buffer, close neovim, reopen it, only show one buffer tab.

### What did you expect to happen?

Open two buffer, close neovim, reopen it, Show two buffer tab.

### Config

```lua
vim.opt.termguicolors = true
require("bufferline").setup {
  options = {
    hover = {
      enabled = true,
      delay = 200,
      reveal = { 'close' }
    },
    offsets = { { filetype = "NvimTree", text = "File Explorer", text_align = "center" } },
    separator_style = "slant",
    custom_filter = function(buf_number, buf_numbers)
      local buf_name = vim.fn.bufname(buf_number)
      if string.find(buf_name, 'fugitive') then
        return false
      end

      local filetype = vim.bo[buf_number].filetype
      if filetype == 'qf' or filetype == '' then
        return false
      end
      return true
    end
  }
}
```

### Additional Information

https://www.reddit.com/r/neovim/comments/yvk3m9/session_plugin_not_working_with_bufferlinenvim/

**Comment by akinsho** [comment]
I don't have enough information from this issue to know what to fix, and a link to reddit won't do. I use a session manager myself and this works fine, so I don't believe this plugin is the likely cause. When a session is restored using vim's native session mechanism, the buffers are re-opened and bufferline picks them up. Bufferline does not do *any* special logic for this. As long as the plugin is using the native vim sessions, it should work. If it is not, then it is not supported 🤷🏿

**Comment by ShiChenCong** [comment]
After reading plugin source code, found the problem was due to my custom_filter.Thank you for your patience
