### ISSUE TITLE
[Bug]: bd# doesn't update bufferline

### ISSUE THREAD

**Issue by GnikDroy** [akinsho/bufferline.nvim#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

`bd#` doesn't update bufferline

### What did you expect to happen?

bufferline to be updated

### Config

```lua
require("bufferline").setup({})
```

### Additional Information

Open a few buffers. Switch between them. Use `:bd#`

**Comment by chomosuke** [comment]
I had this issue too but it went away after I changed to v3.*. Perhaps this is something that's fixed recently?

**Comment by akinsho** [comment]
I'm unable to reproduce this on the latest version of the plugin. Please ensure that you are using the latest version of this plugin and have updated your neovim to the latest version as well. If you have done both of those things and are still facing this issue, please post a minimal init.lua for how I can reproduce this issue and I'll re-open this.

**Comment by GnikDroy** [comment]
OS: Arch Linux 6.0.10, also tested on Windows
Neovim Version: v0.8.1
Bufferline versions attempted: `master`, `v3.1.0`
Terminal Emulator: kitty 0.26.5, Windows terminal
Shell: fish 3.5.1, powershell

The minimal version is literally `require("bufferline").setup({})` I have disabled everything else. `init.lua` is empty other than the following lines. Here is a the full `init.lua`

```lua
vim.g.maplocalleader = ","
vim.keymap.set("n", "<leader>bd", ":bn<cr>:bd#<cr>", { desc = "Close buffer" })

local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
    if fn.empty(fn.glob(install_path)) > 0 then
        print("Packer not found. Installing packer...")
        fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })
        if vim.v.shell_error == 0 then
            print("Sucessfully installed packer.")
            vim.cmd([[packadd packer.nvim]])
            return true
        else
            vim.api.nvim_err_writeln("Cannot install packer.")
            vim.api.nvim_err_writeln("Make sure git is installed, and internet connection is stable.")
            return nil
        end
    end
    return false
end

local packer_bootstrapped = ensure_packer()
if packer_bootstrapped ~= nil then
  require("packer").startup(function(use)
      use("wbthomason/packer.nvim")
      use({
      'akinsho/bufferline.nvim', tag = "v3.*", config = function() require("bufferline").setup({}) end
      })
      if packer_bootstrapped then require("packer").sync() end
  end)
end
```

`bd#` does sometimes update bufferline, but it is unreliable. Open multiple files and try it a couple of times.

So, open vim, `:e` two files. `:bd#` or use the keybinding `<leader>bd`. Notice that the bufferline is not updated. It gets updated once i try to click on the bufferline.

Also, to reinterate, yes I performed `PackerCompile`, yes the version is `v3.1.0`
Heres the output from the repository in `pack/packer/bufferline` `commit 028a879 (HEAD, tag: v3.1.0)`

Heres the output from `PackerStatus`
```
packer.nvim - Total plugins 2
- bufferline.nvim
- packer.nvim
```

It seems at least one other person has had this issue. Let me know if you need any further information.

**Comment by akinsho** [comment]
@GnikDroy can you please try the latest actual commit in the repo rather than the latest tag

**Comment by GnikDroy** [comment]
@akinsho I have tested with the most recent commit. The screencast also shows 4ecfa81e at 1:12

**Comment by akinsho** [comment]
@GnikDroy this issue is probably similar to another issue that was raised a few weeks ago after nvim 0.8 released. Some change in that release seems to have caused the tabline to refresh less frequently. I added a fix for that by adding an extra redraw because the command they were using was internal to this plugin. In your case (which I have not been able to reproduce) the issue seems to be caused by running a command completely external to this plugin. The decision to redraw the tabline or not is largely controlled by neovim not by this plugin.

I notice you are using neovim nightly which I don't target, I recommend checking that this issue is not related to using an unstable version of neovim and if not then try adding a `bd# | redraw` or something to your command since otherwise I'm not sure what else I can do since this behaviour has always worked and seems like a change in neovim

**Comment by GnikDroy** [comment]
`bd# | redraw!` works for now. Hopefully, others having this problem have something to refer to now. Thank you for your time.
