### ISSUE TITLE
[Feature Request]: Separate buffers in different tabs

### ISSUE THREAD

**Issue by PiyushDuggal-source** [akinsho/bufferline.nvim#623]
### What?

If we create new [tab](https://vim.fandom.com/wiki/Using_tab_pages) in Vim(nvim), we would like to see only those files in the bufferline which are in that Tab, and if we switch between tabs then only those files should be visible in the bufferline which are specific for that particular tab.

### Why?

Now if we open new [tab](https://vim.fandom.com/wiki/Using_tab_pages) in Vim(nvim) then bufferline shows all the opened buffers and if we switch between buffers then the projects also shuffles, if we separate them, then open project files will stay on one tab and other project files will stay on other tabs for consistency. Thanks :)

**Comment by akinsho** [comment]
@PiyushDuggal-source has been requested many times and I have answered this issue before. Please have a look at the readme where I point users towards a plugin called scope.nvim which does what you are requesting. If this is functionality you want please use that plugin and if you still have other ideas, please read the previous issues.
