### ISSUE TITLE
[Bug]: BufferLineCycleNext when current buffer is unsaved

### ISSUE THREAD

**Issue by lcfd** [akinsho/bufferline.nvim#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If the current buffer is unsaved I can't change the buffer using BufferLineCycleNext until I save the buffer.

```
Error executing Lua callback: ...packer/start/bufferline.nvim/lua/bufferline/commands.lua:44: Vim:E37: No write since last change (add ! to override)
stack traceback:
        [C]: in function 'nvim_set_current_buf'
        ...packer/start/bufferline.nvim/lua/bufferline/commands.lua:44: in function 'open_element'
        ...packer/start/bufferline.nvim/lua/bufferline/commands.lua:190: in function 'cycle'
        ...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:228: in function <...ite/pack/packer/start/bufferline.nvim/lua/bufferline.lua:228>
```

### What did you expect to happen?

I expect that I can change the buffer without saving the current buffer.

### Config

```lua
  bufferline.setup {
      options = {
          mode = "buffers"
      }
  }
```

### Additional Information

...

**Comment by akinsho** [comment]
This is not an issue with this plugin. This is likely because you have not set hidden in your config. All this plugin does is called the underlying native mechanisms out of finding the correct buffer

**Comment by minhanghuang** [comment]
> This is not an issue with this plugin. This is likely because you have not set hidden in your config. All this plugin does is called the underlying native mechanisms out of finding the correct buffer

yes, I had same issues and resolved it by closed `markdown linter`
