### ISSUE TITLE
[Bug]: Highlight groups BufferLineBuffer* doesn't change buffer icon's background

### ISSUE THREAD

**Issue by trankchung** [akinsho/bufferline.nvim#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Setting the BufferLineBuffer, BufferLineBufferSelected, and BufferLineBufferVisible highlight groups `bg` to `#19212e` doesn't change the inactive buffer's icon background. Please see attached screenshot.

Also, I took all the BufferLine* highlight groups and set all their background to same color but that inactive buffer icon still doesn't change. What color group does it use?

<img width="707" alt="image" src="https://user-images.githubusercontent.com/573808/204323937-f9df6807-7b68-49e2-b7ef-17c633d81116.png">

Thanks,

### What did you expect to happen?

The background color for inactive buffer icon should change.

### Config

```lua
local bg = "#19212e"

BufferLineBufferBuffer = { bg = bg },
BufferLineBufferSelected = { bg = bg },
BufferLineBufferVisible = { bg = bg },
```

### Additional Information

...

**Comment by trankchung** [comment]
Turns out the highlight groups are BufferLineDevIconLua and BufferLineDevIconTxt.

**Comment by RoRep1ay** [comment]
HI @ckt114 , i'm facing the same issue. Could you guide me on how you fix this issue?

**Comment by ckt114** [comment]
Bufferline create a highlight group for devicon file type in the format of BufferLineDevIcon* where the * is Lua, Json, etc and it’s impossible to figure all of them out. So I ended up just use the `highlights` key in the setup and override the `bg` for the groups I wanted like below. 

```

local highlights = function()
  local fg = “#ffffff”
  local bg = “#00000”
  return {
    background = {
      bg = bg,
    },
    buffer_selected = {
      bg = bg,
      fg = fg,
      bold = true,
    },
    buffer_visible = {
      bg = bg,
    },
    close_button = {
      bg = bg,
    },
    duplicate = {
      bg = bg,
    },
    duplicate_selected = {
      bg = bg,
      fg = fg,
      bold = true,
    },
    duplicate_visible = {
      bg = bg,
    },
    fill = {
      bg = bg,
    },
    indicator_visible = {
      bg = bg,
    },
    modified = {
      bg = bg,
    },
    separator = {
      bg = bg,
      fg = bg,
    },
    separator_visible = {
      bg = bg,
      fg = bg,
    },
  }
end

require("bufferline").setup({
  highlights = highlights,
  …
})
```

**Comment by RoRep1ay** [comment]
Hello @ckt114 , thank you for your help. It's working now :)
