### ISSUE TITLE
[Bug]: Can't get NvimTree offset to work

### ISSUE THREAD

**Issue by joaquincorradi** [akinsho/bufferline.nvim#629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The sidebar offset is not working for me. I'm using NvimTree as my file manager. I didn't write any code by myself, I just copied and pasted the `:help bufferline-config` configuration.

### What did you expect to happen?

**Expected behaviour:**

![imagen](https://user-images.githubusercontent.com/53107439/204963615-4eeedd49-f388-4520-bb4a-45a5e27d8873.png)

**Actual behaviour:**

![imagen](https://user-images.githubusercontent.com/53107439/204963785-bb9e94b9-511a-4258-b49b-35d7732a5bbf.png)

### Config

I got the following basic config:
```
local setup, bufferline = pcall(require, "bufferline")
if not setup then
	return
end

bufferline.setup({
	options = {
		offsets = {
			filetype = "NvimTree",
			text = "File Explorer",
			text_align = "center",
			separator = true,
		},
	},
})
```

### Additional Information

...

**Comment by akinsho** [comment]
@joaquincorradi your configuration is incorrect. The option should be a list of tables, not a single table. I'm going to close this up because this can result if you configure things correctly and I've verified locally that offsets do work.
