### ISSUE TITLE
[Feature Request]: Show bufferline if 1 buffer is open, but hide if 0?

### ISSUE THREAD

**Issue by jakobkhansen** [akinsho/bufferline.nvim#631]
### What?

Hi, is it possible to hide the bufferline if there are 0 open buffers (like unlisted dashboard) and show it if there is 1 or more buffers open? `always_show_bufferline` is not quite what I had in mind since this hides the bufferline if there is 1 buffer open.

### Why?

Its nice to be able to have a `always show bufferline` functionality without showing the black bar on the dashboard (like alpha-nvim).

Thanks!

**Comment by akinsho** [comment]
@jakobkhansen you can achieve this functionality in your own config by using the native nvim `showtabline` option in the configuration for your dashboard plugin. No custom logic is needed here as I believe a bunch of users already do this as standard

**Comment by jakobkhansen** [comment]
Thanks, for anyone else wanting to do this for alpha-nvim, add this to the config object:

```lua
    opts = {
        setup = function()
            vim.api.nvim_create_autocmd("User", {
                pattern = "AlphaReady",
                desc = "disable tabline for alpha",
                callback = function()
                    vim.opt.showtabline = 0
                end,
            })
            vim.api.nvim_create_autocmd("BufUnload", {
                buffer = 0,
                desc = "enable tabline after alpha",
                callback = function()
                    vim.opt.showtabline = 2
                end,
            })
        end,
    },

```
