### ISSUE TITLE
[Feature Request]: Tab naming

### ISSUE THREAD

**Issue by distek** [akinsho/bufferline.nvim#634]
### What?

It would be nice to have named tabs instead of the current ` 1 | 2 | 3 `

i.e. ` project 1 | project 2 | nvim-conf `

Something like a `BufferlineTabRename` or similar?

### Why?

If you're a tab _and_ buffer user, allows for less thinking about which tab has what during a long session or coming back to nvim after a period of being away from the desk.

tabline.nvim has this already, but I very much prefer the existing feature set of bufferline.nvim

Haven't dug in to the code yet, so I'm not sure how much this would take. But I can maybe submit a PR if it's not too bad.

**Comment by akinsho** [comment]
I'm personally not particularly keen on this feature, so will definitely not be adding it myself. I've been trying to keep the feature set of this plugin similar to a normal tab bar in another editor, so don't really want this to necessarily include the kitchen sink.

That being said, if someone else wants to contribute, it 🤷🏿. I'll leave this open for a few weeks and if no one has stepped forward with a PR I'll close this out but doesn't mean I'm no longer open to the PR just don't like lingering issues

**Comment by AlexSWall** [comment]
Any thoughts on the PR, @akinsho?
