### ISSUE TITLE
[Bug]: Checking to see if there is a typeo

### ISSUE THREAD

**Issue by casonadams** [akinsho/bufferline.nvim#640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Is this correct?
https://github.com/akinsho/bufferline.nvim/blob/main/lua/bufferline/highlights.lua#L76

local hl_keys = {
  guisp = "sp",
  guibg = "bg",
  guifg = "fg",
  default = "default",
  foreground = "fg",
  **background = "fg", <---- THIS ONE HERE?**
  fg = "fg",
  bg = "bg",
  sp = "special",
  special = "special",
  italic = "italic",
  bold = "bold",
  underline = "underline",
  undercurl = "undercurl",
  underdot = "underdot",
}

### What did you expect to happen?

I would expect

local hl_keys = {
  guisp = "sp",
  guibg = "bg",
  guifg = "fg",
  default = "default",
  foreground = "fg",
  **background = "bg", <-- THIS ONE HERE!**
  fg = "fg",
  bg = "bg",
  sp = "special",
  special = "special",
  italic = "italic",
  bold = "bold",
  underline = "underline",
  undercurl = "undercurl",
  underdot = "underdot",
}

### Config

default

### Additional Information

...

**Comment by akinsho** [comment]
Does look like a typo. PR definitely welcome

**Comment by casonadams** [comment]
MR here:
https://github.com/akinsho/bufferline.nvim/pull/643
