### ISSUE TITLE
[Bug]: Inconsistent underline color

### ISSUE THREAD

**Issue by rockofox** [akinsho/bufferline.nvim#647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whatever I do, I can't get the underline to just be in one color.

<img width="214" alt="Screenshot 2022-12-25 at 16 55 53" src="https://user-images.githubusercontent.com/5049120/209474608-8e0cca67-1da4-4650-984e-e0b7d47331c5.png">

### What did you expect to happen?

The underline should be #f24f72 in case of my config

### Config

```lua
local hasBufferline, _ = pcall(require, "bufferline")

if hasBufferline then
    require('bufferline').setup {
        options = {
            diagnostics = "nvim_lsp",
            middle_mouse_command = "bdelete! %d",
            show_close_icon = false,
            show_buffer_close_icons = true,
            diagnostics = 'nvim_lsp',
            diagnostics_indicator = function(count, level) return (icons[level] or '?') .. ' ' .. count end,
            diagnostics_update_in_insert = false,
            hover = { enabled = true, reveal = { 'close' } },
            indicator = {
                style = "underline",
            },
            offsets = {
                {
                    filetype = "NvimTree",
                    text = "",
                    highlight = 'NvimTreeNormal',
                    --separator = '▏',
                }
            },
        },
        highlights = {
            offset_separator = {
                bg = '#06080A'
            },
            indicator_selected = {
                fg = '#f24f72',
                bg = 'bg'
            },
            fill = {
                fg = 'bg',
                bg = '#242528'
            },
            background = {
                bg = '#242528'
            },
            close_button = {
                bg = '#242528'
            },
            close_button_visible = {
                bg = '#242528'
            },
            close_button_selected = {
                bg = 'bg'
            },
            separator = {
                bg = '#242528'
            },
            tab_close = {
                fg = '#ccccee',
                bg = '#ec5f67'
            },
        },
    }

    local opts = { noremap = true, silent = true }
    vim.keymap.set('n','gD', '<Cmd>BufferLinePickClose<CR>', opts)
    vim.keymap.set('n','gb', '<Cmd>BufferLinePick<CR>', opts)
    vim.keymap.set('n','<leader><tab>', '<Cmd>BufferLineCycleNext<CR>', opts)
    vim.keymap.set('n','<S-tab>', '<Cmd>BufferLineCyclePrev<CR>', opts)
    vim.keymap.set('n','[b', '<Cmd>BufferLineMoveNext<CR>', opts)
    vim.keymap.set('n',']b', '<Cmd>BufferLineMovePrev<CR>', opts)
    vim.keymap.set('n','<leader>1', '<Cmd>BufferLineGoToBuffer 1<CR>', opts)
    vim.keymap.set('n','<leader>2', '<Cmd>BufferLineGoToBuffer 2<CR>', opts)
    vim.keymap.set('n','<leader>3', '<Cmd>BufferLineGoToBuffer 3<CR>', opts)
    vim.keymap.set('n','<leader>4', '<Cmd>BufferLineGoToBuffer 4<CR>', opts)
    vim.keymap.set('n','<leader>5', '<Cmd>BufferLineGoToBuffer 5<CR>', opts)
    vim.keymap.set('n','<leader>6', '<Cmd>BufferLineGoToBuffer 6<CR>', opts)
    vim.keymap.set('n','<leader>7', '<Cmd>BufferLineGoToBuffer 7<CR>', opts)
    vim.keymap.set('n','<leader>8', '<Cmd>BufferLineGoToBuffer 8<CR>', opts)
    vim.keymap.set('n','<leader>9', '<Cmd>BufferLineGoToBuffer 9<CR>', opts)
end

```

### Additional Information

kitty 0.26.2

**Comment by diegoulloao** [comment]
same issue here

**Comment by LICF01** [comment]
Same here, the indicator not using the specified color

**Comment by Xiione** [comment]
I am running kitty 0.26.5 and fish 3.5.1 - exporting the TERM environment variable as `xterm-256color` is what caused both the bufferline underlines and all other lsp underlines to be rendered incorrectly.
In my case, removing `set -gx TERM xterm-256color` from my config.fish fixed the issue. When I do not manually export the variable like this, the value of TERM is `xterm-kitty`.

**Comment by rockofox** [comment]
Huh, weird. I really had it set to `xterm-256color`. but removing that and making sure it is set to `xterm-kitty` just caused the underline to disappear entirely.
<img width="1336" alt="Screenshot 2023-01-10 at 09 18 21" src="https://user-images.githubusercontent.com/5049120/211497892-c35a343f-1f2c-4cec-aa73-6a43c73151b1.png">

**Comment by akinsho** [comment]
Can people in this issue try using the plugin a) without tmux b) with a different colorscheme to see if either of those things are the cause. If either are the cause, then the plugin is very likely not the root cause of your issues

**Comment by LICF01** [comment]
> Can people in this issue try using the plugin a) without tmux b) with a different colorscheme to see if either of those things are the cause. If either are the cause, then the plugin is very likely not the root cause of your issues

I'm not using tmux and for the colorscheme I tested with another but the same, I cannot change the underline highlight, this is my setup


```lua
bufferline.setup({
	options = {
		indicator = {
			style = "underline", --"icon" | "underline" | "none",
		},
		diagnostic = false,
		offsets = {
			{
				filetype = "neo-tree",
				text = "File Explorer",
				text_align = "center", -- "left" | "center" | "right"
				separator = false,
			},
		},
		separator_style = "thick", -- "slant" | "thick" | "thin" | { "any", "any" },
	},
	highlights = {
		indicator_selected = {
			fg = "#FFA066",
			bg = "#FFA066",
		},
	},
})
```
The underline should be the #FFA066 but it is setting that  color to the  bar in the left

![image](https://user-images.githubusercontent.com/41651420/212316542-d11c49c3-7cb8-40aa-9abc-57b454fb4f3d.png)

**Comment by akinsho** [comment]
The config above won't change the underline colour because it is based off of the `TabLineSel` group. The idea is that the underline uses the same *base* group as is used for the indicator, but it doesn't directly inherit the value used by the `indicator_selected`. I have tested locally that setting the value of `TabLineSel` in your colorscheme or configuration will change the underline colour.

If someone would like to contribute a fix so that the underline indicator directly inherits from the `indicator_selected` please feel free to raise a PR,


the requisite change will need to be in:
https://github.com/akinsho/bufferline.nvim/blob/b02041a16bf37f13c3802223bad35aee8cfcf3b5/lua/bufferline/config.lua#L373

Otherwise this should work if the correct highlight group is set

**Comment by interbattles** [comment]
for some reason i'm getting this in foot term? :/ (tried in kitty and worked fine)
also is it *normal* that when i `echo $TERM` from inside neovim it's xterm256 instead of the correct one i get outside of neovim?

(sorry this issue is dead but i dont want to open a new one)
