### ISSUE TITLE
[Bug]: I have to call `colorscheme catppuccin/tokyonight/...` twice to apply to seperators

### ISSUE THREAD

**Issue by matthis-k** [akinsho/bufferline.nvim#648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I call colorscheme once, this is the result
![2022-12-26T21:31:19,930435787+01:00](https://user-images.githubusercontent.com/69082876/209581697-07ba3be5-00e8-444c-9a57-87c623200a82.png)
:

### What did you expect to happen?

Expected behaviour is what happens after calling it again:
![2022-12-26T21:34:15,490608467+01:00](https://user-images.githubusercontent.com/69082876/209581902-98fdc2c1-dc80-4d55-be03-2b97ca37bb8d.png)

### Config
```lua
local config = function()
    require("bufferline").setup({
        options = {
            mode = "buffers",
            numbers = "none",
            close_command = "bdelete! %d",
            right_mouse_command = "bdelete! %d",
            left_mouse_command = "buffer %d",
            middle_mouse_command = "bdelete! %d",
            indicator = {
                icon = "▎",
                style = "icon",
            },
            buffer_close_icon = '',
            modified_icon = '●',
            close_icon = '',
            left_trunc_marker = '',
            right_trunc_marker = '',
            max_name_length = 18,
            max_prefix_length = 15,
            truncate_names = true,
            tab_size = 18,
            diagnostics = "nvim_lsp",
            diagnostics_update_in_insert = true,
            diagnostics_indicator = function(count, level, diagnostics_dict, context)
                return "(" .. count .. ")"
            end,
            offsets = {
                {
                    filetype = "neo-tree",
                    text = "File Explorer",
                    text_align = "left",
                    separator = true
                }
            },
            color_icons = true,
            show_buffer_icons = true,
            show_buffer_close_icons = true,
            show_buffer_default_icon = true,
            show_close_icon = true,
            show_tab_indicators = true,
            show_duplicate_prefix = true,
            persist_buffer_sort = true,
            separator_style = "slant",
            enforce_regular_tabs = true,
            always_show_bufferline = true,
            hover = {
                enabled = true,
                delay = 200,
                reveal = { 'close' }
            },
            sort_by = 'insert_after_current',
        }
    })
end
```

**Comment by akinsho** [comment]
@matthis-k I'm not immediately sure what action is required on my part. Colorschemes are free to handle applying highlights in whatever way they want which can often lead to issues with plugins such as this one. This does not immediately indicate a bug with this plugin. If you are able to reproduce this issue with other plugins and a minimal init.lua please post that in this thread and I'll reopen this but as you might find from previous closed issues I've been asked a lot about individual colorschemes only to find the issue was not with this plugin after losing a lot of my free time investigating

**Comment by shell-Raining** [comment]
@matthis-k I also had this problem today, but found a solution after looking at the docs of these two plugins, maybe this page can help you

[catppuccin Integrations](https://github.com/catppuccin/nvim#integrations)

this is my minimal config

```lua
-- bufferline.lua
require("bufferline").setup({
    highlights = require("catppuccin.groups.integrations.bufferline").get({
        styles = { "italic", "bold" },
        custom = {
            all = {
                fill = { bg = "#000000" },
            },
            mocha = {
                background = { fg = mocha.text },
            },
        },
    }),
    options = {
        numbers = "ordinal",
        separator_style = 'slant',
    },
})

```

```lua
-- catppuccin.lua
require("catppuccin").setup({
    flavour = "mocha", -- latte, frappe, macchiato, mocha
})

-- setup must be called before loading
vim.cmd.colorscheme "catppuccin-mocha"

```

**Comment by ema2159** [comment]
@matthis-k I am experiencing this issue too. The hacky way of solving it I found was to load the color scheme twice in my configuration, once before and once after bufferline is loaded. It's hacky but it works.

**Comment by ansidev** [comment]
@ema2159 Follow the official guides from the colorscheme author.

FYI: https://github.com/catppuccin/nvim#special-integrations
