### ISSUE TITLE
[Bug]: Pinned buffers don't persist across sessions

### ISSUE THREAD

**Issue by mokafolio** [akinsho/bufferline.nvim#649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When saving a session with pinned buffers, they are not restored when reloading the session.

### What did you expect to happen?

I'd expect the pinned buffers to still be pinned after reloading the session.

### Config

    require("bufferline").setup({
        options = {
            show_close_icon = true,
            diagnostics = "nvim_lsp",
            always_show_bufferline = false,
            separator_style = "thick",
            offsets = {
                {
                    filetype = "neo-tree",
                    text = "Neo Tree",
                    highlight = "Directory",
                    text_align = "left"
                }
            }
        }
    })

### Additional Information

I can see that there is code to persist and restore pinned buffers insider _groups.lua_ . I am not quite sure why it does not work or if there is a setting I am missing. I am using `mini.sessions` to save and reload (global) sessions. It internally just uses `:mksession`. Thank you!

**Comment by akinsho** [comment]
@mokafolio do your session options include `globals`?

**Comment by mokafolio** [comment]
Amazing, that fixed it, I was not aware of `sessionoptions`. Thank you!

**Comment by basava70** [comment]
> Amazing, that fixed it, I was not aware of `sessionoptions`. Thank you!

Hey,
where do I add set sessionoptions += globals ?
I have added this command in my init.lua but pinned buffers are still not being saved.
Can you help me ?

**Comment by mokafolio** [comment]
this is what my `sessionoptions` look like: ```vim.opt.sessionoptions = {
    "buffers", "curdir", "tabpages", "winsize", "globals", "folds", "terminal",
    "help"
}```

**Comment by basava70** [comment]
> this is what my `sessionoptions` look like: `vim.opt.sessionoptions = { "buffers", "curdir", "tabpages", "winsize", "globals", "folds", "terminal", "help" }`

Thanks for the reply, still didnt work. I pinned but after restarting nvim, its blank again. you mentioned groups.lua, where and what do you have in groups.lua?

**Comment by mokafolio** [comment]
`groups.lua` is part of the library source that I was referencing, nothing to do there. You might be setting  your options in the wrong place/time.

**Comment by mokafolio** [comment]
do tabs save at all are only pinned tabs not working? How are you saving your sessions? Are you positive the sessions are actually properly saved?

**Comment by utkarshgupta137** [comment]
I was facing the same problem, but I fixed it by starting bufferline before my session plugin.

lazy.vim:
```lua
{
  "olimorris/persisted.nvim",
  dependencies = {
    "akinsho/bufferline.nvim", -- <------ important ------
  },
  event = "VeryLazy",
  opts = {
    autoload = true,
  },
}
```
