### ISSUE TITLE
[Feature Request]: How to hide truncated file count (not sure if it's already provided)

### ISSUE THREAD

**Issue by wanaiqing** [akinsho/bufferline.nvim#656]
### What?

hide the count(circled in the picture below) of truncated files when screen is not wide enough
![Screenshot 2023-01-12 21 10 55](https://user-images.githubusercontent.com/20230818/212075710-a378cc33-318d-4566-9b4a-b5cc47cf1887.png)

### Why?

the count is messing up with buffer IDs

**Comment by akinsho** [comment]
@wanaiqing I'm not sure if I understand how you even get the layout you are looking at, i.e. `2 ...` I don't use the numbers view at all and bufferline shouldn't truncate what is essentially no text. Can you please provide a clearer issue description.

**Comment by wanaiqing** [comment]
> @wanaiqing I'm not sure if I understand how you even get the layout you are looking at, i.e. `2 ...` I don't use the numbers view at all and bufferline shouldn't truncate what is essentially no text. Can you please provide a clearer issue description.

I'm using a terminal without font replacement support which means icons cannot be displayed correctly, so I turned them off, and the ellipsis is a right_trunc_marker, my configuration snippet is below:
`require("bufferline").setup{
  options = {
    show_buffer_icons = false,
    show_buffer_close_icons = false,
    show_close_icon = false,
    left_trunc_marker = '...',
    right_trunc_marker = '...',
    truncate_names = false,
    numbers = function(opts)
      return opts.id
    end,
  }
}
`

**Comment by akinsho** [comment]
Ah right, this isn't a supported option. In the almost 3 years this plugin has existed, this is the first time I've ever had this requested. I think the number of configuration options has become incredibly unwieldy and as I say in the README. This plugin is opinionated. I'm not against hiding them, but frankly the number of options available makes this plugin much harder to maintain, so I won't add this in unless more people start clamouring for it.

At the moment, it doesn't make sense to add an option every single time a user wants something, which is how I got to this many options in the first place 😮‍💨

**Comment by wanaiqing** [comment]
> Ah right, this isn't a supported option. In the almost 3 years this plugin has existed, this is the first time I've ever had this requested. I think the number of configuration options has become incredibly unwieldy and as I say in the README. This plugin is opinionated. I'm not against hiding them, but frankly the number of options available makes this plugin much harder to maintain, so I won't add this in unless more people start clamouring for it.
> 
> 
> 
> At the moment, it doesn't make sense to add an option every single time a user wants something, which is how I got to this many options in the first place 😮‍💨 

alright it doesn't matter, just curious, thanks for reply
