### ISSUE TITLE
[Feature Request]: Add option for custom 'slope' seperator

### ISSUE THREAD

**Issue by Taaqif** [akinsho/bufferline.nvim#658]
### What?

Hoping to have the ability to style the separators similar to this  
![image](https://user-images.githubusercontent.com/1954204/212603672-22cdef57-2232-454d-9919-6efaa57fe856.png)

![image](https://user-images.githubusercontent.com/1954204/212604822-a416248d-b3af-464f-8906-7f26e54bfd1d.png)

### Why?

Some people like the sloped look and it seems the simplest option would be to update the sep_options to have a new option 'slope'

**Comment by akinsho** [comment]
This is now merged into `dev`
