### ISSUE TITLE
Any startuptime benchmark?

### ISSUE THREAD

**Issue by linrongbin16** [akinsho/bufferline.nvim#666]
Hi, is there a startuptime benchmark for this plugin? especially compare with barbar?
Thanks!

**Comment by akinsho** [comment]
@linrongbin16 this is something that you can do yourself using a plugin manager like lazy.nvim or packer.nvim. This plugin in my experience is very unlikely to be contributing significantly to any startup time issues unless you're in the class of people aiming for sub 10ms. In either case benchmarking isn't something I'm going to get into but please feel free to check yourself 🤷🏿‍♂️
