### ISSUE TITLE
[Bug]: Allow to change winhl base on window?

### ISSUE THREAD

**Issue by tmpm697** [akinsho/bufferline.nvim#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have two window, one neo-tree and other buffers window, i use `winhl` base on window change to set different colors but this plugin seems to fix the color of buffers to `Normal` that can't be changed

how to respect current settings of window's `winhl`?

### What did you expect to happen?

When i change window, `winhl` apply to bufferline.

Like when i open neo-tree window the buffername and its bar set to yellow color,

when i change window to buffers, the buffername and its bar change to smth else.

### Config

all kind of configs

### Additional Information

...

**Comment by akinsho** [comment]
This issue isn't very coherent, unfortunately. `winhl` has nothing to do with this plugin because this plugin works on the tabline which is not specific to windows. I'm not really sure what is expected here. I guess you could go down the rabbit hole of trying to reload and change the highlights for bufferline when changing window, but that is a deep rabbit hole best left for user config files and nothing to be added here

**Comment by tmpm697** [comment]
saying, i have this:

```
Neotree             | buffer1 | buffer2
```

`neo-tree` spawn window at left, and we have other buffer windows at right.

I have `autocmd` to change `winhl` base on window focusing, so when i focus on `neo-tree` window: `Neotree             |`, i also want to change its buffer tab/bar/line color, but currently i can not. howto?

**Comment by akinsho** [comment]
@tmpm697 Please have a look at the help documentation specifically for offsets and adding highlights for an offset.

**Comment by tmpm697** [comment]
https://github.com/akinsho/bufferline.nvim/blob/main/doc/bufferline.txt#L540 only change current color of the text `Neotree`, i want to change color of `fg/bg` of buffer bar of `that` window.

So think like this, the buffer bar of a window, stick with that window and separate from other window's buffer bar.
smth like this and for specific window is what i needed: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/711#issuecomment-1401930011

But above will require bufferline acks window's events like `enter/leave..etc`
