### ISSUE TITLE
[Feature Request]: Tab namming

### ISSUE THREAD

**Issue by masriomarm** [akinsho/bufferline.nvim#670]
### What?

Assign names to tabs, and display tab name + tab number

### Why?

Enhance productivity, tab names + scope would enable one to create workspace.

**Comment by akinsho** [comment]
Someone else previously raised an issue for this and a PR, which was helpful. I'd suggest finding the closed issue and trying to get it back into a mergeable state. Personally, I don't use tabs and won't be implementing this myself. Secondly and most importantly IMO

> enable one to create workspace.

The notion above is not really correct, tabs *aren't workspaces*, although people are trying hard to make them work like that, but it isn't why they exist. I personally think this approach will only lead to more trouble, and it's worth a) getting more used to what tabs actually represent in vim b) asking in neovim core to change the meaning of tabs

**Comment by masriomarm** [comment]
Thanks for your reply, you're totally right. In the past couple of days I tried to force tabs to work as workspaces and it wasn't that satisfying. Adapeting to tabs as it is, is indeed better.
