### ISSUE TITLE
[Feature Request]: Persist Pinned Buffers

### ISSUE THREAD

**Issue by otavioschwanck** [akinsho/bufferline.nvim#676]
### What?

Persist pinned buffers (by cwd).  Could work like harpoon, separated by project (like a bookmark)

### Why?

Harpoon power with tabs!

**Comment by akinsho** [comment]
@otavioschwanck buffers are already persisted if the user is using vim sessions and they have added `globals` to their `sessionoptions`. This is more than enough for me personally and I don't particularly want to add some mechanism outside of neovim sessions for doing this. Is some contributor wants to do this though then please detail your plan in this issue (which I'll re-open) and you can go ahead with a PR. For my side the existing solution is enough and I don't have the time to do some custom other thing.
