### ISSUE TITLE
[Bug]: unpinned buffer not save in session file

### ISSUE THREAD

**Issue by NavePnow** [akinsho/bufferline.nvim#687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I first pin a buffer and save the session. The pinned buffer is saved in session file at `BufferlinePinnedBuffers`.
However, after I restore the session and unpin that buffer, the session does not change according to that.

### What did you expect to happen?

unpinned buffer will be removed in the session file.

### Config

``` lua
local M = {
	"akinsho/bufferline.nvim",
	event = "VeryLazy",
	keys = {
		{ "<leader>p", "<cmd>BufferLineTogglePin<cr>" },
	},
	opts = {
		options = {
			diagnostics = "nvim_lsp",
			hover = {
				enabled = true,
				delay = 0,
				reveal = { "close" },
			},
		},
	},
}

return M
```

### Additional Information

...

**Comment by NavePnow** [comment]
https://github.com/akinsho/bufferline.nvim/blob/cbb798dd2db7841550cd2c6c6dde12dfda055928/lua/bufferline/groups.lua#L204

I take a look at codebase and found that when `remove_from_group` calls `set_manual_group`, the group_id will be `nil`. Thus the unpinned buffer will not be saved into session file.
One possible solution could be remove if condition, which is a bit brute force.

**Comment by NavePnow** [comment]
problem solved! thanks!

**Comment by akinsho** [comment]
Awesome 👍🏿
