### ISSUE TITLE
[Feature Request]: how can remove the white space at both ends

### ISSUE THREAD

**Issue by sunxin18** [akinsho/bufferline.nvim#703]
### What?

one tab takes up too much space
![image](https://user-images.githubusercontent.com/47705437/223610517-9cff1c92-11b5-44b6-bfb9-038dadbfdc56.png)

### Why?

one tab takes up too much space

**Comment by akinsho** [comment]
@sunxin18 please read through the help docs which described what is possible. I don't think removing all the space is possible but you can determine how large each tab should be which will impact the spacing. I've painstakingly added all these docs so please have a read

**Comment by sunxin18** [comment]
![image](https://user-images.githubusercontent.com/47705437/224464338-71e79a47-6179-4780-80f9-5e8292fd707a.png)
i have carefully about the size setttings and tried resizing. 
![image](https://user-images.githubusercontent.com/47705437/224464426-62924fab-028b-4409-94c7-c8a1c97eced8.png)
 There are still lots of white spaces wasted space. Could you please help with how to make the tab layout more compact?

**Comment by akinsho** [comment]
@sunxin18 there is no way to remove all the whitespace this plugin was not designed to have zero whitespace. I explain in the readme that the appearance of things is opinionated
