### ISSUE TITLE
[Feature Request]: Better styling

### ISSUE THREAD

**Issue by pencilcheck** [akinsho/bufferline.nvim#709]
### What?

I really liked airline styling of bufferline, but unfortunately they are not supported, some features are disabled when airline#bufferline related settings are enabled

Wonder if there is a plan to support airline?

<img width="887" alt="Screenshot 2023-03-11 at 4 09 35 PM" src="https://user-images.githubusercontent.com/116532/224517127-27256a5b-8bf3-4f59-80db-72ccd42d0869.png">
This is what it looks like when airline is enabled. A lot of the features that were in bufferline isn't shown here

### Why?

Airline is awesome, want to integrate airline with bufferline

**Comment by akinsho** [comment]
@pencilcheck I think there is probably a lot of confusion in this issue. airline is completely unrelated to bufferline. I'm personally not a fan of that aesthetic at all but if you like it you're better off sticking with that project
