### ISSUE TITLE
[Bug]: Close Icon doesn't work properly, when nvim-tree or neo-tree is visible

### ISSUE THREAD

**Issue by apettel** [akinsho/bufferline.nvim#711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After clicking the close icon when multiple files are open, another file buffer should be visible. But instead of this behaviour, bufferline is invisible and only neo-tree or nvim-tree is visible.

### What did you expect to happen?

Bufferline is visible and the file left of the closed tab is visible.

### Config

I use the default LazyVim-Config:

{
  "akinsho/bufferline.nvim",
  event = "VeryLazy",
  keys = {
    { "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle pin" },
    { "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete non-pinned buffers" },
  },
  opts = {
    options = {
      diagnostics = "nvim_lsp",
      always_show_bufferline = false,
      diagnostics_indicator = function(_, _, diag)
        local icons = require("lazyvim.config").icons.diagnostics
        local ret = (diag.error and icons.Error .. diag.error .. " " or "")
          .. (diag.warning and icons.Warn .. diag.warning or "")
        return vim.trim(ret)
      end,
      offsets = {
        {
          filetype = "neo-tree",
          text = "Neo-tree",
          highlight = "Directory",
          text_align = "left",
        },
      },
    },
  },
}

### Additional Information

...

**Comment by akinsho** [comment]
@apettel this is not a bug but how neovim works by default. The file explorer is not a special window but a normal one so when you run a normal `bdelete` command which is what the close icon does by default it closes the window leaving only neo-tree. If you don't want this to happen you should configure your close command to use a plugin that doesn't mess up your windows, but that is up to you to configure
