### ISSUE TITLE
Please tell me what kind of font it is.

### ISSUE THREAD

**Issue by bad4iz** [akinsho/bufferline.nvim#712]
![image](https://user-images.githubusercontent.com/16918043/224816188-7803ec1f-6665-4491-88ee-ba6298113b3b.png)

**Comment by akinsho** [comment]
I haven't used that font in years but think it's just fira code

**Comment by bad4iz** [comment]
this is not a fire code . I use fire code . and I don't have such an image.

**Comment by bad4iz** [comment]
![image](https://user-images.githubusercontent.com/16918043/224905554-6676ccc1-94d4-4a21-b02a-70445abb39b5.png)

**Comment by akinsho** [comment]
Ah that's operator mono
