### ISSUE TITLE
[Bug]: Tag not found when installing with lazy.nvim

### ISSUE THREAD

**Issue by yangmillstheory** [akinsho/bufferline.nvim#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/akinsho/bufferline.nvim#installation suggests installing based on tag. But the following configuration

```
require("lazy").setup({
  { 'akinsho/bufferline.nvim', tag = "v3.*", requires = 'nvim-tree/nvim-web-devicons' },
})
```

produces

![image](https://user-images.githubusercontent.com/2729079/227761864-b50c442a-9c51-4065-8c1a-00ffd58694ed.png)

### What did you expect to happen?

No errors on installing.

### Config

Already done above.

### Additional Information

Once we figure out the issue, we should produce working documentation for installation via the lazy.nvim package manager.

**Comment by akinsho** [comment]
@yangmillstheory you can just use `version = "*"` tbh I shouldn't have put anything fancy there and just pointed people to `lazy.nvim` docs so they don't rely on me for information on how that package manager works. I'll tweak the example

**Comment by akinsho** [comment]
If there are any issues with that please see lazy's docs since this really is an issue of how that works 🙏🏾

**Comment by akinsho** [comment]
@yangmillstheory actually just realised the documentation doesn't even refer to usage with *lazy.nvim* it only talks about *packer.nvim*? so it wasn't right to follow those instructions anyway.

**Comment by yangmillstheory** [comment]
I'm aware of that, but it's natural that to extrapolate the instructions,
as they have basically the same options.

You should add instructions for installing with lazy.nvim so others don't
make the same mistake.

**Comment by akinsho** [comment]
> I'm aware of that, but it's natural that to extrapolate the instructions,
as they have basically the same options.

This seems like very bad practice to me, natural or not. I think reading the documentation is the right thing here.

> You should add instructions for installing with lazy.nvim so others don't
make the same mistake.

This is **open source**  @yangmillstheory open noticing your error *you* could have contributed this fix. I've already pushed the changes to the dev branch.
