### ISSUE TITLE
[Bug]: Buffer close icon broken in v3.6.0

### ISSUE THREAD

**Issue by lstanard** [akinsho/bufferline.nvim#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that the "x" close icon is broken in v3.6.0:

<img width="448" alt="Screenshot 2023-04-12 at 12 22 21 PM" src="https://user-images.githubusercontent.com/507079/231535358-d6a05ac3-19b0-4889-b5e8-cf0a658568af.png">

The icon displays correctly when specifying tag v3.5.0: 

<img width="352" alt="Screenshot 2023-04-12 at 12 18 33 PM" src="https://user-images.githubusercontent.com/507079/231534676-de695943-47d0-4a00-8daf-e6019c6c8320.png">

### What did you expect to happen?

Expect close icon to appear correctly after upgrading plugin to latest version (3.6.0). 

### Config

  {
    'akinsho/bufferline.nvim',
    tag = "v3.6.0",
    dependencies = 'nvim-tree/nvim-web-devicons',
    config = function()
      require('bufferline').setup({
        options = {
          diagnostics = 'nvim_lsp',
          thin = true,
          offsets = {
            {
              filetype = 'NvimTree',
              text = ' File Explorer',
              text_align = 'left',
              highlight = 'Directory',
              separator = false
            }
          }
        },
        highlights = {
          fill = {
            -- Background fill color that looks best with 'everforest' theme
            bg = '#232A2E',
          },
        },
      })
    end,
  },

### Additional Information

...

### commit

https://github.com/akinsho/bufferline.nvim/commit/83b4d0bd9557759831f5519575363f78b94fbbd6

**Comment by akinsho** [comment]
@lstanard, you probably need to update your font or re-patch, the icon I replaced has been deprecated by Nerdfonts and will be removed in the next major version. I can't keep using it as it will break eventually. I mean you could always override the current font with the old deprecated one but hopefully my explanation has clarified why this is not the best choice.

**Comment by lstanard** [comment]
That makes sense - thank you!
