### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by foersben** [akinsho/bufferline.nvim#729]
### What?

I would like to have the typical triangle `vim-airline` representation for tabs/buffers with the ability to select a separate colorscheme. Especially, a drop-in replacement for the colorscheme would be important to me. I am using a main colorscheme and a different one for stuff like the statusbar etc.

Is something like this possible?

### Why?

Simple adaptation of colours in bufferline. The airline-part is more a how-to request?

**Comment by akinsho** [comment]
@foersben I don't really understand much of this request but the plugin is really as described by the documentation and configurable as described by the documentation. I suggest having a look at what is possible through that and trying to tweak things to get them as close to your preferences as possible (if at all possible)
