### ISSUE TITLE
Error when opening neovim

### ISSUE THREAD

**Issue by ElcomJ** [akinsho/bufferline.nvim#730]
Good evening, after updating the application using `PlugUpdate`, when starting Neovim the following error appears:

![Screenshot from 2023-04-15 22-12-31](https://user-images.githubusercontent.com/37147897/232260996-870cdf19-2f0c-409c-abfd-a028d54d8160.png)

Probably some of the last `4 commits` is making om that this problem occurs, because it only began to appear after them.

**Comment by akinsho** [comment]
@ElcomJ can you please provide some information about what neovim version you are using and exactly how you are loading this plugin. Please paste in the code where possible instead of screenshots 🙏🏾

**Comment by ElcomJ** [comment]
Good morning @akinsho , of course I can, below are screenshots of my `version` of neovim and the plugin, as well as an execution of the error:

**Neovim Version:**

![Screenshot from 2023-04-16 09-22-53](https://user-images.githubusercontent.com/37147897/232309848-7b3ceb4f-f981-4387-93b7-22720dcbb182.png)

**Bufferline nvim in init.vim:**

![Screenshot from 2023-04-16 09-23-45](https://user-images.githubusercontent.com/37147897/232309884-3302c3d7-edd7-4af0-9226-687e6b383f91.png)

**Error reproduction:**

[Screencast from 04-16-2023 09:24:07 AM.webm](https://user-images.githubusercontent.com/37147897/232309922-3dbec32d-72f0-4c79-bc8c-4916ccc2fea2.webm)

**Comment by ElcomJ** [comment]
Hey @akinsho , I found the error.

I was using an old tag,` v2` in this case, reading the readme I saw that you recommend the use of `v3`, so I updated and gave a PlugUpdate the `problem was fixed :)`

Thanks for the support and congratulations for the great plugin :)

I'll be closing this commit now, have a nice day.
