### ISSUE TITLE
[Feature Request]: Split bufferline

### ISSUE THREAD

**Issue by b-sep** [akinsho/bufferline.nvim#732]
### What?

Dont know about complexity but would be nice if when i open a new buffer in a vertical split bufferline appears on the second split instead ordered on the first one (print). Probably kinda complex since splits can be resized and the bufferline would have to follow if the split was resized.. anyway.

![image](https://user-images.githubusercontent.com/65205717/232930078-53350640-ccba-4f11-acdd-ee30791231f0.png)

**Comment by akinsho** [comment]
Hi @b-sep, so there have been conversations about similar sorts of things before e.g. #426. As for trying to add bufferline to the winbar to achieve something like this I've discussed that there and you can see what the discussion was. As for just shifting the contents of the tab bar  this would be quite complicated and incredibly messy. It would also open a lot of questions about how it would handle if there were lots of vertical splits or some horizontal splits etc. All in all not something I'm willing to take on if someone can't dive into the whole functionality and plot out how they think it would work and more importantly why all this work would be *valuable*.
