### ISSUE TITLE
[Bug]: Segments must be a list

### ISSUE THREAD

**Issue by johnf** [akinsho/bufferline.nvim#733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On nvim nightly 0.10.0 I'm getting the following error.
```
E5108: Error executing lua ...k/packer/start/nvim-bufferline.lua/lua/bufferline/ui.lua:144: Segments must be a list
stack traceback:
        [C]: in function 'assert'
        ...k/packer/start/nvim-bufferline.lua/lua/bufferline/ui.lua:144: in function 'get_component_size'
        ...k/packer/start/nvim-bufferline.lua/lua/bufferline/ui.lua:518: in function <...k/packer/start/nvim-bufferline.lua/lua/bufferline/ui.lua:499>
        vim/shared.lua: in function 'get_components'
        ...pack/packer/start/nvim-bufferline.lua/lua/bufferline.lua:93: in function <...pack/packer/start/nvim-bufferline.lua/lua/bufferline.lua:89>
```

### What did you expect to happen?

No error

### Config

I did a sample config with only bufferline added by packer and running nothing but buffferline.setup({})

**Comment by johnf** [comment]
LOL ignore me. My search was not a good one.

**Comment by IsaccBarker** [comment]
Could you share your solution? I've been searching for a while and can't find anything.

**Comment by ashis0013** [comment]
Hey @johnf I am getting the same can you give me any existing issue link or solutions?

**Comment by johnf** [comment]
If you search the issues there is a similar one on GitHub. From memory I was using an older version and needed to update the tag I was referencing in my plugin config

**Comment by johnf** [comment]
This one https://github.com/akinsho/bufferline.nvim/issues/727
