### ISSUE TITLE
[Feature Request]: Not actually a feature request but I want to know how bufferline close click icon can close buffer without closing window

### ISSUE THREAD

**Issue by DRedflag** [akinsho/bufferline.nvim#737]
### What?

Title suggested, maybe with a command or bind it with hot key to delete buffer.

### Why?

Buffer line come with BufferLineCloseLeft, BufferLineCloseRight, BufferLinePickClose, but not something like BufferLineCloseCurrent. I think this would help.

**Comment by akinsho** [comment]
@DRedflag this is a duplicate of many issues that request the same thing. The reason this plugin doesn't include this command is because vim already natively has a `:bdelete` command which deletes the current buffer. There is no need for a special command here
