### ISSUE TITLE
[Feature Request]: Take `autowrite` into account

### ISSUE THREAD

**Issue by cassepipe** [akinsho/bufferline.nvim#746]
### What?

Since `bufferline` seemingly bypasses vim's buffer management, options like `autowrite` (and it's cousin `autowriteall`) have no effect.

### Why?

It allows for having automatic saving behavior at the toggle of a switch and is how it's intended by neovim.

Note: `autowrite` despite the name acts more like `:update` in that only writes if the file that's just been hidden has been modified

Thanks for making that plugin available <3

**Comment by akinsho** [comment]
Hi @cassepipe,

So I think there's some confusion or potential miscommunication, `bufferline` definitely does not bypass vim's buffer management, which is actually something I spend of time ensuring and communicating to people. It takes all of it's state from neovim it represents that in lua as classes but ultimately it all still points at vim.

Regarding `autowrite(all)` I'm familiar with both options and use them  in this plugin without issue. This issue crucially doesn't actually clarify what isn't working?

> options like autowrite (and it's cousin autowriteall) have no effect

I'm not sure what exact effect/behaviour is causing this believe 👆🏾?

**Comment by akinsho** [comment]
Gonna close this out, feel free to comment here with a reproduction + explanation of what you mean and we can pick the conversation back up if there's something to investigate

**Comment by cassepipe** [comment]
For my defence :
Turns out `hidden` is set to true in `nvim` even after I remove the `~/.config/nvim` file entirely so I am not the one setting `hidden.
It is not set in my linux distro's `/etc/vimrc` either. 
The manual on the contrary says it's off by default...
