### ISSUE TITLE
[Feature Request]: highlight groups for the trunc left and right icons and text

### ISSUE THREAD

**Issue by Machine-Maker** [akinsho/bufferline.nvim#751]
### What?

It seems the trunc left and right icons are missing their own highlight groups, currently using the [fill group](https://github.com/akinsho/bufferline.nvim/blob/41660189da6951d14436147dff30ed7f0d12ed01/lua/bufferline/ui.lua#L678-L679).

### Why?

More control over the look of the buffer line.

**Comment by akinsho** [comment]
I'd take a PR/contribution to add this but this is personally super low priority for me as this isn't something I'm particularly interested in, not a bad idea just time I'd rather not spend on something I don't particularly need. If you do want to make the contribution let me know and I can point you to where in the code these changes will be needed. 

Probably
1. adding the new highlight groups in the `config.lua`
2. adding the highlight groups to the truncation elements.
3. updating the documentation

**Comment by akinsho** [comment]
I'll leave this open a week or so to see if there are any takers otherwise will close it and it'll be here for reference if anyone wants to dig in in the future.
