### ISSUE TITLE
[Bug]: Opening Telescope in an empty buffer shows the modified icon

### ISSUE THREAD

**Issue by sstallion** [akinsho/bufferline.nvim#762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've noticed that if I start with an empty buffer (eg. `:new`) and open a Telescope picker (eg. `:Telescope find_files`, the modified icon will be shown for the current tab if `mode = "tabs"`. This does not appear to affect `mode = "buffers"`.

### What did you expect to happen?

There should be no change to the modified icon.

### Config

```
require("bufferline").setup {
  options = {
    mode = "tabs"
  }
}
```

**Comment by akinsho** [comment]
@sstallion I cannot reproduce this using fzf I don't use telescope but the principal should be the same if I go into tabs mode and open the picker the buffer does not show as modified can you confirm that
a) you are using a truly minimal vim config without other plugins than telescope and bufferline to test
b) you have verified that the mechanism you are using to open this doesn't somehow modify the underlying buffer.

I've rechecked the code and there is essentially no way for the icon to show if the buffer is not truly modified. I'd suggest you also check `:echo &modified` in the terminal when this happens

**Comment by sstallion** [comment]
Hi @akinsho,

It seems to have something to do with telescope in particular. I've double checked that the buffer is not being modified before hand, but something that is quite interesting is the floating window's `&modified` option shows up as `1`. Is there some way I could use a custom filter to prevent updating the modified status as well? The only seems to affect Telescope as other plugins I use that make use of floating windows are all marked as readonly.

Here is the minimal init.vim I'm using to reproduce the issue:
```
call plug#begin()
Plug 'akinsho/bufferline.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-tree/nvim-web-devicons'
call plug#end()

lua <<END
require("bufferline").setup {
  options = {
    mode = "tabs"
  }
}
END
```

To reproduce the issue,  run `nvim` with no arguments, then issue `:Telescope find_files`. The tabline will display the modified icon, even though the buffer has not been modified.

**Comment by sstallion** [comment]
It might be worth pointing out this does not affect bufferline when `mode = "buffers"` when a custom_filter is set; this only seems to affect `mode = "tabs"`.

**Comment by sstallion** [comment]
@akinsho I think I might have found a better solution. I added a new feature to conditionally render the modified icon, which works around this issue for my specific use-case (#763). Thanks again for the support!
