### ISSUE TITLE
[Bug]: Close Icon not showing even using nerd font

### ISSUE THREAD

**Issue by magodo** [akinsho/bufferline.nvim#766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using gnome-terminal, which uses the nerd font ubuntu mono. Neovim is showing the file icon correctly, while not for the close icon. E.g.

![image](https://github.com/akinsho/bufferline.nvim/assets/7970698/4a47da0c-335e-4eda-a46f-f52f971458c9)

I've even tried to use other different nerd fonts, with no luck.

### What did you expect to happen?

The close icon is showing correctly

### Config

```
lua << EOF
vim.opt.termguicolors = true
require("bufferline").setup{}
EOF
```

### Additional Information

...

**Comment by akinsho** [comment]
The rendering of nerd fonts is generally outside the scope of this plugin. Please ensure you have updated your font to nerd fonts V3. If you search for info on that you should find a solution.

**Comment by magodo** [comment]
@akinsho As you see the glyph that isn't showing is `F655`, which per https://www.nerdfonts.com/cheat-sheet is `nf-mdi-close`, and is marked as *removed*. Is that by design of this plugin?

**Comment by magodo** [comment]
I just noticed I'm still on the branch `master`, switching to `main` fixes the issue.
