### ISSUE TITLE
[Bug]: repeatedly exiting from insert mode when dapui and cmp plugins are inspalled

### ISSUE THREAD

**Issue by skibon02** [akinsho/bufferline.nvim#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/skibon02/my-nvim/tree/dapui-insert-mode-bug

The problem is the following:
When i open any file that support completions from `nvim-cmp` (in my boiled-down config example any .lua file) I do the following steps:
- Toggle on and then off dapui interface (remapped to **Ctrl-t** in my case - press **Ctrl-t** twice).
- Enter insert mode by pressing "o". It will exit insert mode immediately and only leave a blank line.
- After this single exiting from insert mode everything will work as intended. But in master branch of my nvim config reporitory, I have much more plugins and completion sources installed and it is exiting from insert mode (after I open and close dapui) every time untill I fully close and reopen neovim no matter how i enter insert mode ("i", "o", "a", "s"....). 

### What did you expect to happen?

Do not spontaneously exit from insert mode to normal mode.

### Config

Dapui config:
```lua
local dapui = require("dapui")
dapui.setup{}
vim.keymap.set("n", "<c-t>", dapui.toggle, {desc = "Toggle dapui"})
```

Bufferline config:
```lua
require("bufferline").setup {
}
```

### Additional Information

I am not sure that the problem is with bufferline.nvim, because this bug only shows up when using with some other plugins:
- `Packer` plugin managing system
- `mfussenegger/nvim-dap` and `rcarriga/nvim-dap-ui`
- `hrsh7th/nvim-cmp` and any completion source, for example `hrsh7th/cmp-nvim-lua`
- Default configuration for neovim and plugins

I found this bug when I've added `bufferline` to my configuration. It had a lot of plugins, remaps and configurations in my setup, but, fortunately, I boiled down all my configuration to only few plugins and default config for them: https://github.com/skibon02/my-nvim/tree/dapui-insert-mode-bug

If I switch mode to tabs, the problem is gone, same if I don't call `require("bufferline").setup`.

### commit

main branch, 02d795081e6a24ec1fd506c513491543793d0780

**Comment by akinsho** [comment]
@skibon02 currently this issue is super hard to isolate to just bufferline there are a lot of plugins involved and the actual issue i.e. insert mode behaviour actually doesn't have anything to do with this plugin as it doesn't really do anything that is more dependent. I'm going to close this out as in it's current form it would be impossible to fix/do anything about. Please feel free to whittle things down to a direct few step process to reproduce ideally with no other plugins and maybe something that points to this plugin 🙏🏾

**Comment by skibon02** [comment]
Alright, probably it is dapui plugin problem. I've noticed similar behavior during dapui debug session without bufferline.nvim installed.
