### ISSUE TITLE
[Bug]: Close all buffer when opening NvimTree

### ISSUE THREAD

**Issue by LikeTheWindGone** [akinsho/bufferline.nvim#769]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

when I open nvimtree and some buffer,  I want to close current buffer with 'bdelete', then all buffer are closed.

### What did you expect to happen?

Only the current buffer should be closed.

### Config

	   vim.opt.termguicolors = true
	   require("bufferline").setup({
            options = {
                numbers = "ordinal",
                offsets = {{
                    filetype = "NvimTree",
                    text = "File Explorer",
                    highlight = "Directory",
                    text_align = "left",
                }},
                indicator = {
                    icon = ' ',
                    style = 'underline',
                },
            }
	   })

### Additional Information

...

**Comment by akinsho** [comment]
@LikeTheWindGone this isn't an issue with this plugin, just how neovim works please look into plugins like vim-bbye and sayonara or nvim-bufdel

**Comment by MariaSolOs** [comment]
> @LikeTheWindGone this isn't an issue with this plugin, just how neovim works please look into plugins like vim-bbye and sayonara or nvim-bufdel

@akinsho I'm struggling with this issue too while setting up `mini.files`. Could you please share an example of how to configure a "close buffer" plugin to work with bufferline? I've tried `mini.bufremove`, `nvim-bufdel` and `vim-bbye` and I'm still having the issue described [here](https://github.com/echasnovski/mini.nvim/issues/377#issuecomment-1605814056).

**Comment by MariaSolOs** [comment]
My bufferline configuration is as follows:
```lua
local nmap = require('helpers.keybindings').nmap

-- Bufferline for pretty tabs.
return {
    {
        'akinsho/bufferline.nvim',
        dependencies = { 'nvim-tree/nvim-web-devicons', 'famiu/bufdelete.nvim' },
        event = 'VeryLazy',
        opts = {
            options = {
                diagnostics = 'nvim_lsp',
                diagnostics_update_in_insert = false,
                diagnostics_indicator = function(_, _, diag)
                    local icons = require('helpers.icons').diagnostics
                    local ret = (diag.error and icons.Error .. diag.error .. ' ' or '')
                        .. (diag.warning and icons.Warn .. diag.warning or '')
                    return vim.trim(ret)
                end,
                close_command = function(bufnr)
                    require('bufdelete').bufdelete(bufnr, true)
                end,
                right_mouse_command = function(bufnr)
                    require('bufdelete').bufdelete(bufnr, true)
                end,
            },
        },
        init = function()
            nmap('<leader>bo', ':BufferLinePick<cr>', { desc = 'Select a buffer to open', silent = true })
            nmap('<leader>bc', ':BufferLinePickClose<cr>', { desc = 'Select a buffer to close', silent = true })
            nmap('[b', ':BufferLineCyclePrev<cr>', 'Previous buffer')
            nmap(']b', ':BufferLineCycleNext<cr>', 'Next buffer')
            nmap('<leader>bl', ':BufferLineCloseLeft<cr>', 'Close buffers to the left')
            nmap('<leader>br', ':BufferLineCloseRight<cr>', 'Close buffers to the right')
        end,
    },
}
```

But this is still causing the following behaviour with [`mini.files`](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-files.md):

https://github.com/akinsho/bufferline.nvim/assets/62502207/ca5c3e13-a735-4ab5-a566-38b1e8f54b11

Am I missing something? I really love both plugins and I want to get closing to work :(

**Comment by akinsho** [comment]
Hi @MariaSolOs,

I'm really not sure what I'm seeing to be honest so really don't know what to suggest. In general I try to steer clear of configuration/setup issues especially when they involve other plugins. These issues are always very involved and specific to a users particular nvim setup and so tend to be a nightmare to debug and most importantly they don't really relate to a specific bug in the plugin and are more about figuring out how to piece different nvim plugins together etc.

The example of how use another plugin for the close command that you have generally looks right. I have no idea how `mini.files` works or why you are seeing that behaviour at all 🤷🏾‍♂️. I use neo-tree and generally just using even `:bdelete` works fine without any weirdness. I'd suggest first ensuring that mini.files isn't opening tabs vs buffers or something else or there might not be some other complex logic there. Also how you close files using mini won't really relate to bufferline at all.

Apologies if this isn't very helpful but I don't really know what's going on in your video but ultimately looks like an issue gluing together different plugins some/a lot of which I don't use so don't have suggestions for fixing them.

**Comment by MariaSolOs** [comment]
@akinsho I completely understand and I appreciate your reply! I ended up fixing the issue by using `bwipeout` instead of `bdelete`.

**Comment by echasnovski** [comment]
@akinsho, basically it was the result of 'mini.files' trying to reuse existing buffer when opening file (to avoid redundant `:edit`). In the particular case of default 'bufferline.nvim' buffer is `bdelete`d, which means it still exists but unlisted. When opened from 'mini.files', it is made current without change in 'buflisted'.

**Comment by akinsho** [comment]
Thanks @echasnovski for digging in 🙌🏾 much appreciated.
