### ISSUE TITLE
Loading a colorscheme through a lua function does not trigger the buffer line to reload

### ISSUE THREAD

**Issue by Sleepful** [akinsho/bufferline.nvim#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

for example, if I use a vim command `colorscheme <name>` the buffer line works fine.
but if I do `require(<name>).setup` for my theme, the buffer line does not update

### What did you expect to happen?

Expected for it to work OOTB

### Config

Default configuration

### Additional Information

...

**Comment by Sleepful** [comment]
I am using https://github.com/RRethy/nvim-base16

when I switch colorschemes through `:colorscheme <color>` it works fine. 
But when I switch through `require('base16-colorscheme').setup()` the bufferline does not update.

**Comment by akinsho** [comment]
@Sleepful this is likely not a bug running the commandline command triggers a bunch of autocommands which are expected/required to correctly reload things. A lua function will not do this by default unless the author has written all the accompanying logic for that

**Comment by Sleepful** [comment]
@akinsho yeah I am suspecting as much! BUT can you help me figure out which autocommands to run? I tried looking at the source and using `:audo ColorScheme` but that does not trigger the bufferline recolor.
I also tried looking at bufferline functions that I could call to trigger the recolor but to no avail.

**Comment by Sleepful** [comment]
I just need a way that I can trigger a bufferline recolor from lua, that would be super great. using `require("bufferline").setup{}` did not do the trick

**Comment by Sleepful** [comment]
I think I found a much easier work-around: https://github.com/noahfrederick/vim-noctu

**Comment by akinsho** [comment]
@Sleepful the solution should rest with the colorscheme author. You can also search online for what colorscheme command does exactly. I don't have exact answers and am on holiday for a while so better off searching elsewhere

**Comment by Sleepful** [comment]
well thank you for your help anyway! I found a solution.

Enjoy your holiday :D 

I will leave my conclusions below for future reference, feel free to ignore them.

It seems that there is a large difference between calling a function `foo` that sets up the colors, and _sourcing_ the function from another file.

For colorschemes neovim wants to find the file in `/.config/lua/colors/<name>.lua` and then wants the file to be `source`ed, _not_ `require(path.<name>)`d.

So for this example, my `colors/<name>.lua` file looks more or less like this:

```lua
-- flavours.lua
vim.cmd("highlight clear")
vim.cmd("syntax reset")
vim.g.colors_name = "flavours"
require('base16-colorscheme').setup(colors, { telescope_borders = true })
```
which I am sourcing from my config like this:

```lua
local colors = {
  base00 = "#ebf8ff",
  base01 = "#c1e4f6",
  -- etc with all the colors
  }
  local config = "$XDG_CONFIG_HOME"
  local path = "/nvim/colors/flavours.lua"
  vim.cmd("source " .. config .. path)
```

and this works splendidly fine with `bufferline`! Equivalent to calling `colorscheme <name>`
