### ISSUE TITLE
[Feature Request]: Overriding buffer close icon

### ISSUE THREAD

**Issue by smartinellimarco** [akinsho/bufferline.nvim#776]
### What?

First of all, I love the plugin! 😄 
I was wondering there is any way to override what the close button does?
I would like to remap it to Sayonara, mini.bufremove, vim.bbye, etc.
Thanks in advance!

### Why?

To use the same buffer deletion strategy than the rest of the configuration.

**Comment by akinsho** [comment]
@smartinellimarco there is an option to control how the click function works this is documented on the help docs but as you can imagine I do not remember every option by name but it is there.
