### ISSUE TITLE
[Bug]: diagnostic: "nvim_lsp" covering entire buffername

### ISSUE THREAD

**Issue by hacker-DOM** [akinsho/bufferline.nvim#782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that... With default diagnostic option (I presume the default is `nvim_lsp`, but I am not 100% sure), I get this behavior:

Buffer focused:

<img width="640" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/18601956/8e05e555-4d63-44c6-b338-d38879e425e6">

Buffer unfocused:

<img width="641" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/18601956/68c90021-e22e-48e3-a6aa-5ca46d1c578b">

I am settings options = { diagnostics = false } for now

I am on Kitty 0.28.1, Nerdfonts V3, Bufferline [`2f391fd` (current commit on `main`)](https://github.com/akinsho/bufferline.nvim/commit/2f391fde91b9c3876eee359ee24cc352050e5e48)

### What did you expect to happen?

.

### Config

.

### Additional Information

...

**Comment by akinsho** [comment]
@hacker-DOM this isn't quite a bug but very likely an issue with how your highlighting for diagnostic error is set. From the screenshot it appears that the background and foreground are both being set to red. This shouldn't be the case by default but how your highlights are set, which theme you are using etc. is a complexity outside the scope of a plugin issue. What I suggest doing is temporarily using a different theme with no custom highlighting setup at all and seeing/confirming that that bug does not recur with most themes, then debugging what highlights are being set for your diagnostics and changing that.
