### ISSUE TITLE
[Bug]: (UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value 

### ISSUE THREAD

**Issue by ph04** [akinsho/bufferline.nvim#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When opening neovim on a folder, i get this red error on top of the screen.
![immagine](https://github.com/akinsho/bufferline.nvim/assets/47356461/9b29ba1f-0dfd-4714-8733-9c49ee4ac795)
I'm pretty sure the problem has something to do with bufferline, because when commenting it out from my `init.lua`, the error message disappears.

### What did you expect to happen?

Opening without errors.

### Config

```lua
require("bufferline").setup({
    options = {
        numbers = "ordinal",
        separator_style = "thin",
        buffer_close_icon = ""
    }
})
```

### Additional Information

...

**Comment by akinsho** [comment]
@ph04 this almost certainly is a configuration issue and almost certainly not an issue with the plugin itself. The mechanism for loading this plugin has literally never changed. It's installed on multiple of my machines as well as other people's none of which report this issue. I recommend trying to setup a minimal init.lua start precisely reproduces this issue without external plugins. Ideally loading this plugin without a package manager or if using one then including the specific config to reproduce this exact issue. I'm going to close this out as I'm quite confident that this isn't going to be related to a bug specifically on this plugin but if you get a minimal reproduction please post back here and I'll try it

**Comment by ph04** [comment]
Ok I tried with a clean config and adding plugins one by one, and the problem seems to arise with nvim-tree specifically. When opening a folder by doing `nvim [folder name]`, nvim-tree opens the directory, and (probably?) bufferline shows this error on top of the screen (and i say bufferline because it was litterally the only other plugin active while trying this, and also no other setting was active, no remap, nothing).

**Comment by hotsnow-sean** [comment]
If you use lazy as the plugin loader, setting the `event` of `bufferline` to `BufReadPre` can solve the problem. After setting it, if you open a folder using `nvim xxx`, `bufferline` will not be loaded.
(This may mean that the `nvim-tree` opened in this way is not a regular buffer, I'm not sure, but it does work.)
