### ISSUE TITLE
[Question]: Can I run `setup` function multiple times to reset max length after GUI started and refreshed `&columns`

### ISSUE THREAD

**Issue by linrongbin16** [akinsho/bufferline.nvim#787]
### What?

Hi, I want to use my screen monitor's fullscreen width as my Neovim's width, and thus set `1/3` width as buffer name's max length.

But when running this in neovim GUI client, the `&columns` value will change after GUI start, the value is not fullscreen at first, after GUI launch finished, it will change to the real fullscreen width.

For now I'm trying a solution, that listen to `&columns` value changed event, and re-run `setup` function to update bufferline's configuration. Can I run `setup` function multiple times?

### Why?

To apply dynamic name length by screen monitor device.

**Comment by akinsho** [comment]
@linrongbin16 you should be able to run setup multiple times without side effects but frankly I haven't done this myself often so your mileage may vary.
