### ISSUE TITLE
Highlights, colors problem

### ISSUE THREAD

**Issue by Mekam1** [akinsho/bufferline.nvim#790]
**_I tried to set up colors for the bufferline and failed. I checked the termguicolors (it's on), I turned off the colorscheme, I reinstalled the plugin and it is not working still. Any changes in highlights are not working._**
<img width="948" alt="Screenshot 2023-07-14 at 21 27 29" src="https://github.com/akinsho/bufferline.nvim/assets/139581582/f0d94807-de9d-4338-8cf1-a17fc94cbfec"><img width="510" alt="Screenshot 2023-07-14 at 21 29 10" src="https://github.com/akinsho/bufferline.nvim/assets/139581582/3b8f34d2-f4f8-4b13-bc16-819a2af7d4ef">

**Comment by gonviegas** [comment]
I'm facing the same issue...

**Comment by Mekam1** [comment]
> I'm facing the same issue...

You can try to do it with cmd:
:hi BufferLineFill guifg #000000

it works for me, but i am lack of knowledge, how to make it autoload

**Comment by Mekam1** [comment]
### Sometimes I just need to read more carefully :). Documentation is helpful.
**Solution:** 
>  _1. Instead of using guifg/guibg use fg/bg
>  2. Instead of using gui = bold, use bold = true, italic = false_

**reload nvim and you're good!**

**Comment by gonviegas** [comment]
I've read the documentation and I think im doing everything right and still doesn't work.
I'm using lazy:

```
return {
	"akinsho/bufferline.nvim",
	version = "*",
	dependencies = "nvim-tree/nvim-web-devicons",
	config = function()
		require("bufferline").setup({
			options = {
				indicator = { "none" },
				separator_style = { "▏", "▕" },
				offsets = {
					{
						filetype = "NvimTree",
						text = "",
						highlight = "NvimTreeNormal",
						text_align = "left",
						separator = true, -- use a "true" to enable the default, or set your own character
					},
				},
			},
			highlights = {
				buffer_selected = {
					fg = "#ffffff",
					bg = "#090909",
				},
			},
		})
	end,
}
```
