### ISSUE TITLE
[Bug]: Stale LSP diagnostic status

### ISSUE THREAD

**Issue by MariaSolOs** [akinsho/bufferline.nvim#796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

First of all, thanks for the amazing plugin! <3

But okay, I've noticed that the diagnostic status in my bufferline won't correctly update after I've fixed the error (sometimes I need to save the buffer, move the cursor, or do something else for it to update). What calls my attention in particular is that [`lualine`](https://github.com/nvim-lualine/lualine.nvim/blob/05d78e9fd0cdfb4545974a5aa14b1be95a86e9c9/lua/lualine/components/diagnostics/sources.lua#L7) does update the diagnostic count correctly, and from what I can see both `bufferline` and `lualine` are using the LSP diagnostic status for this, and so I'm confused about the mismatch. 

Here's an example of what I'm experiencing. Below I'm missing a semicolon, and both `lualine` and `bufferline` reflect the error:
<img width="904" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/62502207/145c6586-016b-4ed9-9ab0-fea85fc35df8">

After fixing the error, the diagnostic count is correct in `lualine`, but `bufferline` still shows the error status:
<img width="905" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/62502207/6f302ee7-7a7d-430c-9ceb-5bc500afc179">

### What did you expect to happen?

For `bufferline` to update the LSP diagnostic status when the diagnostic has been fixed.

### Config

My [`bufferline` configuration](https://github.com/MariaSolOs/dotfiles/blob/59a2f05383648345e510808f777744da7e63ef68/.config/nvim/lua/plugins/bufferline.lua):
```lua
-- Bufferline for pretty tabs.
return {
    {
        'akinsho/bufferline.nvim',
        event = 'VeryLazy',
        dependencies = 'echasnovski/mini.bufremove',
        opts = {
            options = {
                close_command = function(bufnr)
                    require('mini.bufremove').delete(bufnr, false)
                end,
                diagnostics = 'nvim_lsp',
                diagnostics_indicator = function(_, _, diag)
                    local icons = require('helpers.icons').diagnostics
                    local indicator = (diag.error and icons.Error .. ' ' or '') .. (diag.warning and icons.Warn or '')
                    return vim.trim(indicator)
                end,
            },
        },
        config = function(_, opts)
            local nmap = function(lhs, rhs, desc)
                vim.keymap.set('n', lhs, rhs, { desc = desc })
            end

            require('bufferline').setup(opts)

            nmap('<leader>bo', '<cmd>BufferLinePick<cr>', 'Select a buffer to open')
            nmap('<leader>bc', '<cmd>BufferLinePickClose<cr>', 'Select a buffer to close')
            nmap('[b', '<cmd>BufferLineCyclePrev<cr>', 'Previous buffer')
            nmap(']b', '<cmd>BufferLineCycleNext<cr>', 'Next buffer')
            nmap('<leader>bd', function()
                require('mini.bufremove').delete(0, true)
            end, 'Delete current buffer')
            nmap('<leader>bl', '<cmd>BufferLineCloseLeft<cr>', 'Close buffers to the left')
            nmap('<leader>br', '<cmd>BufferLineCloseRight<cr>', 'Close buffers to the right')
        end,
    },
}
```

And [my `lualine` configuration](https://github.com/MariaSolOs/dotfiles/blob/59a2f05383648345e510808f777744da7e63ef68/.config/nvim/lua/plugins/lualine.lua):
```lua
-- Statusline.
return {
    {
        'nvim-lualine/lualine.nvim',
        event = 'VeryLazy',
        opts = {
            options = {
                theme = 'dracula-nvim',
                component_separators = '|',
                section_separators = '',
            },
            sections = {
                lualine_b = { 'branch', 'diff' },
                lualine_c = {
                    -- Show LSP progress.
                    {
                        function()
                            return require('noice').api.status.lsp_progress.get_hl()
                        end,
                        cond = function()
                            return package.loaded['noice'] and require('noice').api.status.lsp_progress.has()
                        end,
                    },
                    -- Show macro recording messages.
                    {
                        function()
                            return require('noice').api.status.mode.get()
                        end,
                        cond = function()
                            return package.loaded['noice'] and require('noice').api.status.mode.has()
                        end,
                    },
                },
                lualine_x = {
                    {
                        'diagnostics',
                        sections = { 'error', 'warn', 'info', 'hint' },
                    },
                },
                lualine_y = { 'encoding', 'filetype' },
            },
        },
        config = function(_, opts)
            require('lualine').setup(opts)

            -- Disable this since the mode will be displayed by lualine.
            vim.o.showmode = false

            -- Update the statusline with the latest LSP message.
            vim.api.nvim_create_autocmd('LspProgress', {
                pattern = '*',
                command = 'redrawstatus',
            })
        end,
    },
}
```

### Additional Information

...

**Comment by akinsho** [comment]
Hi @MariaSolOs,

So I wouldn't describe this as a bug since the for both plugins it would depend on when the diagnostic status is checked. I haven't changed this code in quite a while but I believe it doesn't update in insert mode (or at least there is a config for that). Secondly the tabline in general might not be being triggered to update immediately a diagnostic changes. This could be worthwhile or expensive to add more redraws 🤷🏾‍♂️. For my use case I almost always save the buffer after I've fixed an error so have never felt the need to add more frequent updating.

**Comment by MariaSolOs** [comment]
Thanks for the reply @akinsho! I tried setting `diagnostics_update_in_insert = true` and it made no difference :/

I agree that it might not be worth it to add more diagnostic count updates if that would sacrifice perf, I just find the difference between the statusline (which yeah I know that it is a different plugin but still) and the bufferline odd. I wonder if with the new pull diagnostic model it will be easier to keep these consistent in the UI.

Anyway, I'm okay if you decide to close this as low priority.

**Comment by akinsho** [comment]
@MariaSolOs so the pull mechanism won't change anything I think because the issue is just when the bufferline is refreshed since it won't natively refresh due to diagnostics. I imagine in this case the solution and what the statusline is probably doing (maybe) is updating on `DiagnosticChanged` or something which could be quite noisy IMO. In either case happy to take a PR to make this update more frequently but tbh given all the other issues and time I want to be spending on maintenance in general this isn't something I see myself changing anytime soon.

**Comment by MariaSolOs** [comment]
@akinsho very fair. Thanks a lot for the reply nonetheless <3 (and the superb plugins too!)
