### ISSUE TITLE
[BUG] The bufferline sometimes cannot work well with offsets (2)

### ISSUE THREAD

**Issue by nullptr-yxw** [akinsho/bufferline.nvim#799]
Sometimes when I close a buffer, the bufferline will not respect the offset

https://github.com/akinsho/bufferline.nvim/assets/96286337/9ab64616-960e-40c9-a07c-1e547f8fa0da

Part of my settings is
```lua
offsets = {
    {
        filetype = "NvimTree",
        text = "File Explorer",
        highlight = "Directory",
        text_align = "left",
        separator = true,
    },
},
```
Another bufferline plugin barbar.nvim doesn't have such problem

https://github.com/akinsho/bufferline.nvim/assets/96286337/ef967823-81b6-4bed-9c36-50b659524764

**Comment by akinsho** [comment]
As mentioned in the original issue please don't open multiple issue called `(1)` and `(2)` just describe the problem in the main issue *clearly* and we can go from there

**Comment by nullptr-yxw** [comment]
> As mentioned in the original issue please don't open multiple issue called `(1)` and `(2)` just describe the problem in the main issue _clearly_ and we can go from there

They are not the same issue, and I change the title now.
