### ISSUE TITLE
[Bug]: when i close current , the all tab and vim quit.

### ISSUE THREAD

**Issue by matianhe3** [akinsho/bufferline.nvim#801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BufferLinePickClose command or click x icon current, the all tab close , and vim quit.

remove bufferline use bdelete, it works well.

### What did you expect to happen?

only close one current tab

### Config

require("bufferline").setup({})
	vim.api.nvim_set_keymap("n", "<leader>bc", ":BufferLinePickClose<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>bo", ":BufferLineCloseOthers<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>bn", ":BufferLineCycleNext<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>bp", ":BufferLineCyclePrev<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>br", ":BufferLineCloseRight<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>bl", ":BufferLineCloseLeft<CR>", {})
	vim.api.nvim_set_keymap("n", "<leader>bs", ":BufferLinePick<CR>", {})

### Additional Information

...

**Comment by akinsho** [comment]
@matianhe3 not 100% sure I understand but it sounds like you are using the native behaviour of `:bdelete` which is what bufferline uses by default. If you want window preservation please read the README on how to add in a handler to change the behaviour of the close buttons

**Comment by ndom91** [comment]
@akinsho sorry to bump this closed issue, but are you saying that `:bdelete` should close nvim entirely? 

Using a keybind which executes `:bdelete` now quits my entire nvim instance where it used to just close the currently active buffer :thinking:

**Comment by akinsho** [comment]
@ndom91 bdelete will close your nvim instance if there is only one window. This is the native behaviour. FWIW all of this buffer/window management behaviour is considered out of scope of this plugin it truly is something worthy of it's own plugin given all of the edge cases and desired functionality. I personally have no desire to maintain or explain this logic and all it's quirks but nonetheless it seems to constantly come up on this plugin.

Please have a look on reddit, or at the many plugins that do handle this behaviour it's something that really should be dealt with there and isn't related to this plugin 🙏🏾

**Comment by ndom91** [comment]
Yeah so this was happening when I had 2+ buffers open and trying to close just 1, for example. However it turns out setting `neo-tree`'s `close_if_last_window = false` fixed this. 

Looking closely, it seems that all buffers were closed quickly and then all the other buffers (other than the one I wanted to close, reopened). At least thats what the UI in the bufferline looked like :shrug: 

Oh well, working again on my side

**Comment by lesar** [comment]
I have done this key binding and seems work: 
 .config/lvim/config.lua
```
lvim.keys.normal_mode["<leader>bx"] = ":lua lvim.builtin.bufferline.options.close_command()<CR>"
```
best regards
Leonardo
