### ISSUE TITLE
[Feature Request]: does bufferline support switch within recently buffers

### ISSUE THREAD

**Issue by zshnb** [akinsho/bufferline.nvim#805]
### What?

in the past i use jetbrains' IDE, there are all support switch within recently opened tabs, the shortkey is control + e

### Why?

when i open a lot of buffers, i can't quickly find last edit buffer when i switch to next buffer, so it is very helpful if there has some shortkey to switch within all opened buffers.

**Comment by akinsho** [comment]
Hi @zshnb 

This issue isn't within the scope of this plugin. Bufferline is a UI plugin only. It doesn't keep track of which buffers you opened and when. This is something you'll need some other external plugins for
