### ISSUE TITLE
[Feature Request]: How can i create button in right side to use vim.cmd when i click ?

### ISSUE THREAD

**Issue by sownteedev** [akinsho/bufferline.nvim#808]
### What?

I want to create a buton when i click, it use vim.cmd
I use custom_areas = {} but i think it just work to show, cant click to use cmd
Can u have solution ?

### Why?

Toggle my theme

**Comment by akinsho** [comment]
@sownteedev sorry but the issue tracker isn't for questions unfortunately I don't really have the spare time to go into specific usage questions. Maybe you can find some help on Reddit or the discourse.
