### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by gmnz** [akinsho/bufferline.nvim#810]
### What?

Hi, 
Let's say I have buffers: 
1 frog, 2 cat, 3 dog, 4 rhino, 5 fox
Is there any command or combination of commands to reorder them like this:
1 fox, 2 frog, 3 cat, 4 dog, 5 rhino
I don't want frog to become number 5 when fox becomes number 1, I want it to be pushed right and the other buffers too. Is there any way to do this?

### Why?

Well, who wouldn't want this? This way I could move the buffers I'm working with right now to positions 1-9 to be able to switch between them quickly.

**Comment by akinsho** [comment]
The only buffer movement commands are the `BufferLineMoveLeft|Right` commands. So however those work is the only available mechanism for it. I'm not currently looking to change or add yet more commands so unfortunately that's all there is.

**Comment by gmnz** [comment]
OK, thanks anyway. If anybody else is look for something similar, this is my current very imperfect solution for the problem:

```lua
    local moveBy = function (dir)
      if dir == 'left' then
        dir = -1
      else
        dir = 1
      end
      local moveBy = vim.v.count
      if moveBy == 0 then
        moveBy = 1
      end
      local myBufferline = require('bufferline')
      for i = 1, moveBy, 1 do
        myBufferline.move(dir)
      end
    end

    vim.keymap.set('n', "[v", function ()
      moveBy('left')
    end, {})
    vim.keymap.set('n', "]v", function ()
      moveBy('right')
    end, {})
```

So "]v" to move the buffer right, "3]v" to move it right by 3 etc. I used a loop because the bufferline builtin move method reorders buffers when moving by more than 1 and I didn't want that.
