### ISSUE TITLE
how to install buferline.nvim via nvim's native package manager

### ISSUE THREAD

**Issue by lzl19971215** [akinsho/bufferline.nvim#813]
Hi, Can I install bufferline.nvim via nvim's native package manager? Like to clone the repostory to `~/.config/nvim/pack/...`?

**Comment by akinsho** [comment]
@lzl19971215 you should be able to just like any other plugin. This isn't really an issue with this plugin just a general neovim usage question so I'm going to close it out as I'll sure you can find the general answer in the help docs or online
