### ISSUE TITLE
[Bug]: (UNKNOWN PULGIN): Error executing lua: attempt to call a nil value

### ISSUE THREAD

**Issue by fagundesraphael** [akinsho/bufferline.nvim#820]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

I just installed the basic config from this repository: https://github.com/NvChad/basic-config
and the bufferline is having this error. I already tried all plugins and I'm sure the problem is with this one.
![Captura de tela de 2023-09-24 03-38-48](https://github.com/akinsho/bufferline.nvim/assets/87456612/3c2d499a-573d-471b-8490-40648c6f2fba)

### What did you expect to happen?

Expected behaviour: not show that error.

### Config

require("bufferline").setup {
  options = {
    themable = true,
    offsets = {
      {
        filetype = "NvimTree",
        highlight = "NvimTreeNormal",
      },
    },
  },
}

### Additional Information

...

**Comment by akinsho** [comment]
@fagundesraphael this issue has been reported *several times* so far it has turned out to be a result of some config issue relating to `NvimTree`. Please have a look at previous issues particularly searching for ones that mention the exact error message. I do not remember the numbers of hand
