### ISSUE TITLE
[Question] Incorrect separator when using transparent theme

### ISSUE THREAD

**Issue by wojciech-kulik** [akinsho/bufferline.nvim#826]
I'm using neovim on macOS and catpuccin theme. Unfortunately, I get white background between tabs when using the transparent theme. How can I fix it?
<img width="480" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/3128467/882c9e21-5a4b-4b0c-8bc9-79ac2d951b5e">

My config:
```lua
return {
	"akinsho/bufferline.nvim",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	version = "*",
	config = function()
		require("bufferline").setup({
			options = {
				buffer_close_icon = "",
				show_close_icon = false,
				show_buffer_close_icons = false,
				mode = "tabs",
				separator_style = "slant",
				numbers = "ordinal",
				offsets = {
					{
						filetype = "NvimTree",
						text = "File Explorer",
						text_align = "center",
						separator = false,
					},
				},
			},
		})
	end,
}
```

I'm not sure if its theme issue or bufferline issue :(.

**Comment by maxigor** [comment]
change your separator_style = "slant" to `separator_style = "thin"`

**Comment by wojciech-kulik** [comment]
I want to keep slant if possible :)

**Comment by akinsho** [comment]
Slant style doesn't work with transparency, it works by essentially shading the part shoes up as white for you to match the background but in the case of transparency there is no way for this to work. In general using transparency with this plugin is limited aesthetically because a lot of what this plugin does is using colours to create an appearance and taking colours away reduces it's ability to do this

**Comment by Schiz0idCat** [comment]
I'm two years late, but take a look to this:
    highlights = {
        fill = {
            fg = colors.dark_gray,
            bg = colors.dark_gray,
        },
        separator_selected = {
            fg = colors.dark_gray,
        },
        separator_visible = {
            fg = colors.dark_gray,
        },
        separator = {
            fg = colors.dark_gray,
        },
    },
Basically, what I'm doing here is change all of the colors that are not related with the open buffers. I'm make them a little bit darker than the buffer's colors. This only affects to the background buffers, this doesn't resolve the problem for the tabs (I don't use them)

![Image](https://github.com/user-attachments/assets/5f07784d-a15d-4412-9d1b-d25cd2a15d07)

(The difference in color tones is not very noticeable, I don't usually use the style you use, so I haven't felt the need to make it even darker).

You can learn more about it in the documentation (bufferline-highlights)
