### ISSUE TITLE
Making hover also work on current buffer.

### ISSUE THREAD

**Issue by aabbccddeeffggj** [akinsho/bufferline.nvim#828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, the hover option is working, except for the current buffer; the close_icon stays unhidden there; I saw in the gif preview it hiding through all buffers, I don't know whether it is a specific customization that was made there or I'm doing something wrong (I looked all the configuration documentation).
Thanks.

### What did you expect to happen?

Expected behaviour
Main buffer's close_icon get hidden when mouse not hovering it.

### Config

local bufferline = require('bufferline')
bufferline.setup {
    options = {
        style_preset = {
            bufferline.style_preset.no_italic,
            bufferline.style_preset.no_bold
        },
        indicator = { style = 'none' },
        buffer_close_icon = '󰅖',
        modified_icon = '',
        close_icon = '󱎘',
        left_trunc_marker = '󰁍',
        right_trunc_marker = '󰁔',
        separator_style = { ' ', ' '},
        always_show_bufferline = false,
        show_buffer_icons = false,
        show_buffer_close_icons = true,
        hover = {
            enabled = true,
            delay = 0,
            reveal = {'close'}
        },
    }
}

### Additional Information

...

**Comment by akinsho** [comment]
Hi @aabbccddeeffggj the close icon is intentionally always visible regardless of however, this is by design not a bug. Not something I'm looking to change tbh
