### ISSUE TITLE
[Feature Request]: is there a api to toggle on/off the whole bufferline

### ISSUE THREAD

**Issue by qlibp** [akinsho/bufferline.nvim#829]
### What?

Hide the whole bufferline by default, and can toggle it on/off manually.

### Why?

- When cycling buffers/tabs, i would like to see the tab list & buffer list.
- When editing, hide it again so that i won't get distracted

**Comment by akinsho** [comment]
You should look into using the `:help showtabline` option. You can then create an autocommand to show it when you want and hide it when you want. The specifics of what that autocommand will do or what it events is up to you and your use case.
