### ISSUE TITLE
[Feature Request]:  Add possibility to keep pick-close open after closing a picked buffer

### ISSUE THREAD

**Issue by ttytm** [akinsho/bufferline.nvim#830]
### What?

Would not need to be default but providing the api would be great.

### Why?

Not re-triggering the pick-close "dialog".

**Comment by akinsho** [comment]
Hi @ttytm, I'm open to a PR to contribute this but not going to do this myself 👍🏾. I'm focusing most of my time on other side projects/work so mainly prioritising bugs or super crucial additions (not to say this would be a bad option)

**Comment by ttytm** [comment]
Thanks for the response @akinsho 

Would love to, but unfortunately zero time to integrate it. Maybe leaving it open - as a help wanted?

**Comment by akinsho** [comment]
@ttytm tbh I've never had an open help wanted ticket ever fulfilled kind of don't believe that works anymore
