### ISSUE TITLE
[Bug]: Lips LSP complain about config

### ISSUE THREAD

**Issue by stephane-archer** [akinsho/bufferline.nvim#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that...
<img width="995" alt="Screenshot 2023-11-11 at 20 18 24" src="https://github.com/akinsho/bufferline.nvim/assets/2981437/f475b0ff-96ba-4f19-9fc0-03fc11219c60">

### What did you expect to happen?

Expected behaviour: no complain by the LSP

### Config

see image

### Additional Information

...

**Comment by claudiofreitas** [comment]
This will probably be fixed once #812 is merged.
