### ISSUE TITLE
Question: how to auto-close the `[No Name]` buffer after open another buffer?

### ISSUE THREAD

**Issue by linrongbin16** [akinsho/bufferline.nvim#834]
I'm using bufferline.nvim with neo-tree.nvim, after open nvim without opening any file, the nvim looks like:

<img width="1920" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/6496887/d6f0816e-27ec-4eba-972d-1747503811cb">

The left side is neo-tree, and there will be a `[No Name]` buffer. I use fzf to find a file and open it with `edit {filename}` command (for example `config.lua` file in my nvim config repo):

<img width="1920" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/6496887/8195ade3-2915-4eba-91e6-d5e31b519336">

Now I want to auto-close the `[No Name]` buffer after I open another file/buffer.

Is there a way to do that?

**Comment by akinsho** [comment]
@linrongbin16 this isn't really a bufferline issue, neovim is the one that opens this no name buffer and deciding to close it is something you'd do completely separate to this plugin all this plugin is doing in this case is highlighting that that buffer exists. You can probably use an autocommand to loop through your open buffers and close any without a name but that's really up to you in your config

**Comment by linrongbin16** [comment]
thanks for suggestions
