### ISSUE TITLE
[Bug]: Lua-language-server annotations mismatch

### ISSUE THREAD

**Issue by hinell** [akinsho/bufferline.nvim#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi. Thanks for the great project. Came across a subtle annotations issue.

https://github.com/akinsho/bufferline.nvim/blob/1a3397556d194bb1f2cc530b07124ccc512c5501/lua/bufferline/types.lua#L19

https://github.com/akinsho/bufferline.nvim/blob/1a3397556d194bb1f2cc530b07124ccc512c5501/doc/bufferline.txt#L305-L308

The above two signatures mismatch. `level` should be string, not a `number`.

### What did you expect to happen?

Correct LLS annotations

### Config

n/a

### commit

1a3397556d194bb1f2cc530b07124ccc512c5501

**Comment by akinsho** [comment]
@hinell thanks for reporting please feel free to raise a PR to tweak it 🙏🏾
