### ISSUE TITLE
[Feature Request]: MoveTab

### ISSUE THREAD

**Issue by talentix-ch** [akinsho/bufferline.nvim#847]
### What?

It would be a great improvement if it would be possible to move tabs in the bufferline as in barbar.vim. The functions BufferMoveNext, BufferMovePrev, BufferMoveStart and BufferMoveEnd of barbar.nvim can be mapped to keys to easily move buffers. 

### Why?

Very often I do open configuration files (Neovim, Docker, Kubernetes, Saltstack, Linux) of two or more different configurations to compare them and to copy configuration parts from one file to another. 

Example: find ~/.config/nvim.{1,2} -name *.lua | xargs vim
This opens all lua files from the neovim configurations nvim.1 and nvim.2. Then I want to compare the files of the same type. So I want to move the tabs for all init.lua together and the same for all options.lua and keyaps.lua. Of course I can open a split and compare the files of the same type side by side. But sometimes it is better to switch between files of the same type w/o using window splits and w/o cycling through may open buffers / tabs.
This is the reason why I am using barbar.nvim and not bufferline.nvim

Thank you for sharing your plugin and for sharing your great work!

Kind regards,
Uri

**Comment by akinsho** [comment]
This plugin already includes move commands i.e. `BufferLineMoveNext`, `BufferLineMovePrev` not looking to expand the range to include start and end but that should solve most of the issue.
