### ISSUE TITLE
[Feature Request]: Rename tabpages (not the buffer 'tabs')

### ISSUE THREAD

**Issue by Gremious** [akinsho/bufferline.nvim#849]
### What?

Bufferline, in the default `buffer` mode, moves your actual vim tabpages to the side and labels them 1, 2, 3 etc.

I would like something like `:BufferLineRenamePage foo` and/or an api endpoint for that so I can auto name my tabpages to differentiate what is where.

### Why?

bufferline + scope allows me to use vim tab pages as "workspaces" when working on multiple projects at the same time.
I `:tabnew` and move to a different project in the same vim instance. This works great with vim allowing to change the current working directory per tab.

Normally the tab pages have names of the current dir/file or so, but bufferline just shows them as 1, 2, 3. I'd like to make a little auto-command to name my tab-pages based on the project they're in, so I can differentiate them a bit better.

I like to think that this is also generally helpful for anyone who actually uses the vim tab-pages.

**Comment by distek** [comment]
Hi!

See: https://github.com/akinsho/bufferline.nvim/pull/848

I think this does will do what you want if/when it's merged.
