### ISSUE TITLE
[Feature Request]: Customize duplicate prefix text

### ISSUE THREAD

**Issue by diegoulloao** [akinsho/bufferline.nvim#851]
### What?

I was searching in the docs how to customize the `duplicate` prefix text but there's no option for it.

### Why?

It would be great to have this option, sometimes the text `(duplicated)` is large, it would be great to have the ability to change it to `(dup)` for just saying something.

**Comment by akinsho** [comment]
Tbh I'm not particularly keen on this, I think over time the requests to tweak X are essentially endless and I think it makes this plugin more and more convoluted with a zillion options. I think it's better to draw a line at some point

**Comment by ybian** [comment]
I'm also looking for this. The indicator of a "duplicated" tab is very useful for us to manage the windows. But the hard coded "(duplicated) " prefix is too long. It is a necessary enhancement to allow customization of this.

**Comment by samuelabreu** [comment]
In my case would be nice to remove the text completely, when on tab mode i usually have multiple tabs on same file.

I can create a pull request if you are interested.

**Comment by EricDriussi** [comment]
Same here: when on tab mode files are often opened in different tabs. I don't gain much by knowing they are duplicated.
I understand the point that "requests to tweak X are essentially endless" but this seems to be a bit intrusive when working in tab mode tbh.
