### ISSUE TITLE
[Feature Request]: Expose buffer index

### ISSUE THREAD

**Issue by EdgarAlenPoe** [akinsho/bufferline.nvim#861]
### What?

expose the get_current_element_index function
add index to get_elements

### Why?

I imagine there are many potential usages, but I'm trying to setup a custom buffer close keybind.
I can submit a pull request if you'd like, but it's an easy enough feature.

**Comment by akinsho** [comment]
Tbh my preference is generally to avoid exposing things where possible since people then depend on the API working a certain way which ends up tying my hands for future changes or deprecations. This isn't one that I'm particularly keen on but if you raise the PR 🤷🏾‍♂️
