### ISSUE TITLE
[Bug]: Icon bg colour not correct

### ISSUE THREAD

**Issue by IvanVZabrodin** [akinsho/bufferline.nvim#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm using Neovim with bufferline and the Kanagawa theme. However, the bg colour of the language icons are incorrect, not matching the bg of the rest of the tab. See below:
![image](https://github.com/akinsho/bufferline.nvim/assets/46194901/02e8dfcd-ddc8-436a-9c64-ca44130187a7)

OS: Windows
Terminal: Windows Terminal

### What did you expect to happen?

The background colours to be the same.

### Config

```lua

vim.opt.termguicolors = true

require('lazy').setup {
  {
    "akinsho/bufferline.nvim",
    opts = {
      seperator_style = 'slant',
    },
  },
  {
    "rebelot/kanagawa.nvim",
    priority = 1000,
    config = true,
  },
}

vim.cmd([[colorscheme kanagawa]])
```

### Additional Information

...

**Comment by akinsho** [comment]
@IvanVZabrodin this is in all likelihood related to your theme +/- how and when it is loaded vs. this plugin. There have been quite a lot of issues along these lines in the past which tend to boil down to checking the ordering of loading. Unfortunately I'm not able to dig into this myself but if you check historical issue someone else will likely have commented on this. Also play around with the `themable` option
