### ISSUE TITLE
[Bug]: (UNKNOWN PLUGIN): Error executing lua: attempt to call a number value

### ISSUE THREAD

**Issue by pwnalone** [akinsho/bufferline.nvim#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/akinsho/bufferline.nvim/assets/3609458/646f80f5-9b09-4e06-b633-9a8419a0cf72)

### Related Issues

This issue has been reported before three other times that I am aware of, typically in relation to the `nvim-tree` plugin; however, the previous issue authors failed to provide a minimal configuration to help troubleshoot the issue. Furthermore, I have determined that this issue does **not** relate to `nvim-tree` or any other file explorer. Please see below for a minimal configuration.

- #786
- #811
- #820

### Steps to Reproduce

1. Place the minimal configuration at `~/.config/nvim/init.lua`.
2. Start `nvim` to install the 3 relevant plugins.
3. Close and reopen `nvim`.
4. Execute `:h g` and then `:h h` (or anything else that opens up a different help document).
5. Repeat steps 3-4 until you observe the error, above.

##### Dockerfile

Here is a `Dockerfile` to easily setup a clean environment with the latest stable release of Neovim installed.

```dockerfile
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y build-essential curl git tar
RUN curl -sL https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz \
    | tar -zxf - -C /usr/local --strip-components=1

CMD /bin/bash
```

##### Build

```bash
docker build -t neovim .
```

##### Start

```bash
docker run --rm -it -v $PWD:/root/.config/nvim -w /root/.config/nvim neovim
```

### What did you expect to happen?

There should not be an error.

### Config

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'akinsho/bufferline.nvim',
    version = '*',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    event = { 'VimEnter' },
    init = function()
      vim.o.termguicolors = true
    end,
    opts = {},
  },
  {
    'folke/tokyonight.nvim',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('tokyonight-night')
    end,
  },
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    event = { 'VimEnter' },
    config = function(_, opts)
      require('nvim-treesitter.configs').setup(opts)
    end,
    opts = {
      ensure_installed = { 'lua', 'vim', 'vimdoc' },
      highlight = { enable = true },
    },
  },
})
```

### Additional Information

So far, I've only been able to narrow down the source of the issue to the interaction between 3 different plugins &ndash; [bufferline](https://github.com/akinsho/bufferline.nvim) (i.e. this plugin), [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), and [tokyonight](https://github.com/folke/tokyonight.nvim).

I'm opening this issue here because I believe that it is most likely that the problem is in this plugin and not the others. My reasoning for this is that the error, shown in the above screenshot, has only reported here and not in the other 2 plugins, causing me to assume that others have not experienced this issue without bufferline.

Because the issue does not always result in an error, it seems that it is likely to be a race condition.

Interestingly, I have only observed this issue with the _Tokyonight_ colorscheme, so maybe its related to some new/unique features that this colorscheme is using that the others are not, and which bufferline does not properly account for (just a wild guess).

I have tested the minimal config with these additional colorschemes and have observed no issues.

- [kanagawa](https://github.com/rebelot/kanagawa.nvim)

```lua
  {
    'rebelot/kanagawa.nvim',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('kanagawa-wave')
    end,
  },
```

- [catppuccin](https://github.com/catppuccin/nvim)

```lua
  {
    'catppuccin/nvim',
    name = 'catppuccin',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('catppuccin-mocha')
    end,
  },
```

- [gruvbox](https://github.com/morhetz/gruvbox)

```lua
  {
    'morhetz/gruvbox',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('gruvbox')
    end,
  },
```

- [nightfly](https://github.com/bluz71/vim-nightfly-colors)

```lua
  {
    'bluz71/vim-nightfly-colors',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('nightfly')
    end,
  },
```

- [dracula](https://github.com/dracula/vim)

```lua
  {
    'dracula/vim',
    name = 'dracula',
    priority = 1000,
    config = function()
      vim.cmd.colorscheme('dracula')
    end,
  },
```

**Comment by pwnalone** [comment]
**UPDATE:**

It seems that this plugin works with _Tokyonight_'s `v2.9.0` version, but not `v3.0.0` or `v3.1.0`. According to the change log for [this release](https://github.com/folke/tokyonight.nvim/releases/tag/v3.0.0), there were some breaking changes that were made.

> ⚠ BREAKING CHANGES
>
> - added support for treesitter 0.9.2. Eearlier TS versions are no longer supported.
> - add treesitter default groups to theme
> - remove compat with old treesitter group names from over a year ago

At this point, I'm not sure if this is an issue with bufferline or tokyonight, but I will try to investigate further.

**Comment by akinsho** [comment]
@pwnalone thanks for digging in and taking the time to document this issue. As you say I've never encountered this as I don't use Tokyo night and never have so it's not immediately clear what this interaction is. One possible cause could be how that plugin interacts with this. I think there might be some module of this plugin's that that theme is using that this plugin might not be expecting or it's interacting in some way.

Tbh I'm not likely to be able to dig into this anytime soon, anyone else who wants to take a stab should please do or just document more stuff in here. As always community contributions re a fix would be massively appreciated as I'm definitely not in a place where I can dedicate much free time to these issue.

**Comment by pwnalone** [comment]
@akinsho Thanks for getting back to me so quickly on this. I have switched to a different colorscheme as a temporary fix, but will try to troubleshoot this issue some more if I find the time. If I discover the source of the issue, I'll open a PR. In any case, I'll keep documenting any relevant information here.

**Comment by Airor4** [comment]
I am also experiencing this issue. I am using `sainnhe/sonokai` if that's helpful but I was able to produce it with nvim's default colorscheme. I am running
- nvim-tree/nvim-tree.lua
- akinsho/bufferline.nvim
- neovim/nvim-lspconfig
- williamboman/mason.nvim
- williamboman/mason-lspconfig.nvim
- WhoIsSethDaniel/mason-tool-installer.nvim
- hrsh7th/nvim-cmp
- hrsh7th/cmp-nvim-lsp

**Comment by MrAshirak** [comment]
The problem only occurs when you open nvim using the directory reference in question Ex: `nvim . ` 

The bug did not occur when calling only `nvim` in the directory in question.

### My config 
![image](https://github.com/akinsho/bufferline.nvim/assets/121437937/4fed3d64-d0eb-45a7-9981-0abee09b9920)

**Comment by prettymuchbryce** [comment]
Hello. I have just opened a PR at #928 which I believe should address this issue. Because this error is so generic, it's possible that there could be more than one cause. The PR fixes the error for my configs.

Would it be possible for someone to test out my branch in order to determine whether it resolves the issue?

**Comment by prettymuchbryce** [comment]
The fix for this issue was just merged. I'm curious if anyone could update to the latest version of the plugin and report back on whether it has resolved their issue.

**Comment by akinsho** [comment]
I'm going to pre-emptively close this out. If anyone in the thread experiences this later please comment back on here and we can re-open this
