### ISSUE TITLE
[Bug]: offset doesn't work with neo-tree

### ISSUE THREAD

**Issue by sinelnikov-web** [akinsho/bufferline.nvim#871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried to set offset like in docs, but it doesn't work.

<img width="1728" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/67955139/021b4623-0c9d-4c95-91f0-5da99a950e03">
 

### What did you expect to happen?

Offset will work with neo-tree

### Config

```lua
return {
  'akinsho/bufferline.nvim',
  version = "*",
  dependencies = 'nvim-tree/nvim-web-devicons',
  config = function ()
    vim.opt.termguicolors = true
    require("bufferline").setup{
      options = {
        offsets = {
          {
            filetype = "NvimTree",
            text = "File Explorer",
            text_align = "center",
            separator = true
          }
        }
      }
    }
  end
}
```

**Comment by sinelnikov-web** [comment]
filetype = "NvimTree" must be filetype = "neo-tree",

**Comment by ortonomy** [comment]
This still doesn't work for me:

![Image](https://github.com/user-attachments/assets/c3ac6cce-319f-4ead-837a-25a37a1ab998)

Any idea?
