### ISSUE TITLE
Is it possible to ignore certain buffers in the bufferline, like terminal buffers for example?

### ISSUE THREAD

**Issue by MCodes96** [akinsho/bufferline.nvim#880]
### What?

I often use terminal windows inside neovim, that I toggle on or off when I need to quickly do something inside a terminal but dont want to switch tmux windows. Is it possible to filter out terminal buffers showing up in the bufferline?

**Comment by akinsho** [comment]
You should do this in vim itself using the `nobuflisted` option. See `:h nobuflisted` bufferline by default respects the settings of bufferlist so the user is in control at a neovim level of what buffers show up

**Comment by jimafisk** [comment]
Adding `set nobuflisted` to my `TermToggle()` function in `~/.config/nvim/init.vim` worked :tada: 

Just wanted to note that I also needed to add `set nohidden` to avoid blank `[No Name]` buffers from opening any time I toggled the terminal after the first time (see details: https://github.com/neovim/neovim/issues/17841#issuecomment-1077619495)

Here's the terminal toggle function I'm using in case it's helpful to anyone:
<details>
<summary>Example Terminal toggle function</summary>
<br>

To use: 
- Toggle small terminal with <kbd>Alt</kbd>-<kbd>t</kbd>
- Toggle full terminal with <kbd>Alt</kbd>-<kbd>z</kbd>

Vimscript:
```vim
let g:term_buf = 0
let g:term_win = 0
let g:prev_height = 0
function! TermToggle(height)
   if win_gotoid(g:term_win) && a:height == g:prev_height
      let g:prev_height = 0
      hide
   elseif g:prev_height == 0
      let g:prev_height = a:height
      botright new
      exec "resize " . a:height
      try
         exec "buffer " . g:term_buf
      catch
         call termopen($SHELL, {"detach": 0})
         let g:term_buf = bufnr("")
         set nobuflisted
         set nohidden
         set nonumber
         set norelativenumber
         set signcolumn=no
      endtry
      startinsert!
      let g:term_win = win_getid()
   else
      let g:prev_height = a:height
      exec "resize " . a:height
      startinsert!
   endif
endfunction
nnoremap <A-t> :call TermToggle(10)<CR>
tnoremap <A-t> <C-\><C-n>:call TermToggle(10)<CR>
nnoremap <A-z> :call TermToggle(50)<CR>
tnoremap <A-z> <C-\><C-n>:call TermToggle(50)<CR>
```
