### ISSUE TITLE
[Feature Request]: A way to retrieve a buffer's `current_index`

### ISSUE THREAD

**Issue by thenbe** [akinsho/bufferline.nvim#881]
### What?

I wanted to create a keymap to move buffers. Bufferline has a function that allows us to do this:

```lua
require('bufferline').move_to(new_index, current_index)
```

However, I don't know what the buffer's `current_index` is. I know everything about the buffer I want to act on, except it's `current_index`. How can I get a buffer's `current_index` for the purposes of the function above?

Is there some way one can exchange a `bufnr` for a bufferline `current_index`?

### Why?

I'm trying to attach mappings to a telescope buffer picker.

**Comment by thenbe** [comment]
I'm not sure this is a dupe of https://github.com/akinsho/bufferline.nvim/issues/861 because https://github.com/akinsho/bufferline.nvim/issues/861 still assumes we're still *in* the buffer we want to act on AFAICT. Whereas this issue assumes we want to act on "non-current" buffers (i.e. buffers other than the current one).

**Comment by akinsho** [comment]
@thenbe can you please move this discussion either to #861 despite the perceived differences I have too many open issues to keep track of this sort of distinction alternatively please look at #868 to see if that might cover what you want if not maybe comment there
