### ISSUE TITLE
[Bug]: Styling filetype icon for all filetypes not working/possible

### ISSUE THREAD

**Issue by gitaarik** [akinsho/bufferline.nvim#884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that I can't set a default style for filetype icons.

These don't seem to do anything:

```vim
:hi BufferLineDevIcon guibg=#00FF00
:hi BufferLineDevIconSelected guibg=#00FF00
:hi BufferLineDevIconInactive guibg=#00FF00
```

These ones only styles empty buffers on which no filetype is set:

```vim
:hi BufferLineDevIconDefault guibg=#00FF00
:hi BufferLineDevIconDefaultSelected guibg=#00FF00
:hi BufferLineDevIconDefaultInactive guibg=#00FF00
```

I can set styles for specific filetypes, like:

```vim
:hi BufferLineDevIconlua guibg=#00FF00
:hi BufferLineDevIconluaSelected guibg=#00FF00
:hi BufferLineDevIconluaInactive guibg=#00FF00
```

But I can't set a default icon style for all filetypes.

### What did you expect to happen?

That I can set a default style for all filetypes.

### Config

I'm using the default config.

### commit

64e2c5d

**Comment by akinsho** [comment]
To be honest this is the first time anyone has tried to style icons through this plugin directly. I don't think this is the right approach. From my own perspective I won't have bufferline deviate from the dev icon plugin. Whatever they say the colour is, then thats the colour. I'm pretty sure that plugin includes it's own config so you can change whatever colour it sets so I would look there.

**Comment by gitaarik** [comment]
@akinsho it's about the background color of the icons

**Comment by gitaarik** [comment]
See here, the background color of the inactive tabs are incorrect. I can set them with the `BufferLineDevIconlua` and `BufferLineDevIconluaInactive` highlight groups. But those groups are specific to the `lua` filetype. So if I open another file of a different filetype, the background color is incorrect again. And I have to add another highlight group for that file type etc. It would be nice if there is a highlight group for any filetype.

<img width="750" alt="image" src="https://github.com/akinsho/bufferline.nvim/assets/2470302/e00be7cd-8212-413b-82e4-d6471af8e6e3">

**Comment by cyaconi** [comment]
Maybe adding a highlight group for the filetype icon can help. In my case, I would like to force a fg color for the icons on the inactive tabs, something like this:
![image](https://github.com/akinsho/bufferline.nvim/assets/91154/793f5992-1e16-4237-a998-a68e57697a32)

**Comment by uloco** [comment]
@akinsho Is there a way to style icon backgrounds? This prevents integrating bufferline in my theme completely. Whatever I do with the highlights, the devicons bg is only specific to filetype BufferlineDevIcon<filetype>Visible etc.

**Comment by gitaarik** [comment]
Yes, this issue should be re-opened.

**Comment by akinsho** [comment]
So I should preface this comment to just say that currently I have 0 free time to investigate bufferline issues. It's just not something I can currently focus on.
That being said locally for me I do not and frankly haven't ever had with multiple different colour schemes had issues with the background colours of icons. A huge part of this all depends very heavily on how and when colours/highlights are set on your side. Over the course of the time I've maintained this plugin I've essentially discovered that the general behaviour is kind of a nightmare that causes a bunch of issues especially when you factor in another plugin and it's highlights.

First thing to clarify, this plugin doesn't and won't support customising icon highlights here at all. It's just too much faff. The highlights are calculated when this plugin is loaded based on what they are set to in nvim devicons and what your normal bg is at the time. I think this works for most scenarios but I'm sure there's some where for some reason it won't , there always is in nvim.

I think the thing to do here is to narrow down exactly why background highlights aren't working in a simple situation of loading a theme, what theme and what config, how do I reproduce?

if this is an issue of how can I tweak x then tbh I think it's better closed unless someone in this thread is willing to dig in and figure out the bug and raise a PR. As I mentioned at the top I don't have the bandwidth currently for the mountain of issues on this and my other repos.

**Comment by drgfunk** [comment]
This has been vexing me as well and I'm using the code below to color both the selected/unselected devicon. I put this code in my `lua/plugins/bufferline.lua` config block and then created the following hl groups:

BufferLineDevIcon
BufferLineDevIconSelected

The code below (with the help of gen AI) creates hl groups dynamically and links them to the hl groups above. Also works with sessions.

```lua
-- Cache the devicons module
local devicons = require("nvim-web-devicons")

local function setup_bufferline_devicon_highlights(bufnr)
	-- Get buffer path (use provided bufnr or current buffer)
	local buf = bufnr or 0
	local bufpath = vim.api.nvim_buf_get_name(buf)
	if bufpath == "" then
		return
	end

	-- Use get_icon which is what bufferline uses
	local icon, icon_hl_group = devicons.get_icon(vim.fn.fnamemodify(bufpath, ":t"), nil, { default = true })

	if icon and icon_hl_group then
		local icon_name = icon_hl_group:gsub("^DevIcon", "")
		if icon_name and icon_name ~= "" then
			vim.api.nvim_set_hl(
				0,
				"BufferLine" .. icon_hl_group .. "Selected",
				{ link = "BufferLineDevIconSelected" }
			)
			vim.api.nvim_set_hl(0, "BufferLine" .. icon_hl_group, { link = "BufferLineDevIcon" })
		end
	end
end

-- Function to set up highlights for all existing buffers
local function setup_all_buffer_highlights()
	for _, bufnr in ipairs(vim.api.nvim_list_bufs()) do
		setup_bufferline_devicon_highlights(bufnr)
	end
end

-- Create the augroup in Lua
local bufferline_highlight_group =
	vim.api.nvim_create_augroup("BufferlineAllFileTypeHighlight", { clear = true })

-- Set up autocmds for individual buffer events
vim.api.nvim_create_autocmd({ "FileType", "BufEnter" }, {
	group = bufferline_highlight_group,
	callback = function()
		setup_bufferline_devicon_highlights()
	end,
})

-- Set up autocmd for session loading
vim.api.nvim_create_autocmd("SessionLoadPost", {
	group = bufferline_highlight_group,
	callback = setup_all_buffer_highlights,
})

setup_all_buffer_highlights()

```

<img width="1099" alt="Image" src="https://github.com/user-attachments/assets/b60652c1-bb67-4ec9-b7fd-511ef9efc2fb" />
