### ISSUE TITLE
[Bug]: (UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value

### ISSUE THREAD

**Issue by AsymptoticLine** [akinsho/bufferline.nvim#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When utilizing the `nvim .` command to open a directory, I encounter an error message that states: `(UNKNOWN PLUGIN): Error executing lua: attempt to call a nil value.` This error does not occur when I open a file directly using `nvim .\a.txt`.
I have noticed that if I remove the line `require("bufferline").setup({})` from my configuration, the error message is resolved. However, this also disables the activation of the bufferline.nvim plugin.

### What did you expect to happen?

Just no errors

### Config

Lazy:
``` lua
require("lazy").setup({
	{
		"akinsho/bufferline.nvim",
		version = "*",
		dependencies = "nvim-tree/nvim-web-devicons",
	},
})
```

plugin-config:
``` lua
vim.opt.termguicolors = true
require("bufferline").setup({})
```

**Comment by akinsho** [comment]
@AsymptoticLine I believe this is a duplicate and there are already issues open which reference this please thumbs up one of those issues instead 🙏🏾 #869 for example
