### ISSUE TITLE
[Feature Request]:  Ability to pin all open buffers

### ISSUE THREAD

**Issue by jacobrreed** [akinsho/bufferline.nvim#886]
### What?

Would like a command similar to BufferLineTogglePin that pins all current open buffers

### Why?

Often I open a bunch of files I want to keep open, would like to pin them all at once

**Comment by akinsho** [comment]
Hi @jacobrreed, command seems way too specific to your use case and in general I'm very very reluctant to add new commands unless they are essentially.

**Comment by jacobrreed** [comment]
Ok
![image](https://github.com/akinsho/bufferline.nvim/assets/25580051/a8fafddf-1fca-4bdd-a779-649c28de8cf4)
