### ISSUE TITLE
[Bug]: vim.tbl_isarray is deprecated, use vim.isarray instead 

### ISSUE THREAD

**Issue by anoopd** [akinsho/bufferline.nvim#898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that...im.tbl_isarray is deprecated, use vim.isarray instead . Feature was removed in Nvim 0.10-dev

### What did you expect to happen?

Expected behaviour Nvim 0.10 dev is showing error on startup

### Config

return {
  "akinsho/bufferline.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  version = "*",
  opts = {
    options = {
      mode = "tabs",
      separator_style = "slant",
    },
  },
}

### Additional Information

...

**Comment by leet0rz** [comment]
Same issue here. @akinsho 

Any fix on this?

**Comment by kjuq** [comment]
The issue was already fixed at a6ad228f77c276a4324924a6899cbfad70541547 at main branch. Try removing `version = "*"`.

**Comment by lonkous** [comment]
@kjuq thanks a ton. works for me
