### ISSUE TITLE
[Bug]: deprecation check with is_list does not cover new nightly v0.11

### ISSUE THREAD

**Issue by axelhj** [akinsho/bufferline.nvim#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A fix for a deprecation warning for is_list only checks whether the vim version matches v.0.10 but on nighly/nvim master this is bumped to v-0.11-dev. The depreciation warning appears again (but it does not crash any more). I had to unpin version (remove `version = '*'`) in my config to meet this issue.

### What did you expect to happen?

bufferline.nvim to load without warnings in nighly/build from master

### Config

Similar to
`{'akinsho/bufferline.nvim', version = "*", dependencies = 'nvim-tree/nvim-web-devicons'}`
or
`{'akinsho/bufferline.nvim', dependencies = 'nvim-tree/nvim-web-devicons'}`

### Additional Information

Very much related to this PR https://github.com/akinsho/bufferline.nvim/pull/892/files

### commit

73540cb95f8d95aa1af3ed57713c6720c78af915

**Comment by bellini666** [comment]
Also for `tbl_add_reverse_lookup`

**Comment by axelhj** [comment]
I saw that too. Seems fixed by https://github.com/akinsho/bufferline.nvim/pull/904.
I did some more investigation. `vim.fn.has("nvim-0.11")` returns 1 and I no longer see the issue. Somehow running `:Lazy update` must've failed since I no longer see this issue after purging and reinstalling the plugin.
