### ISSUE TITLE
[Feature Request]: Restore Tab Names

### ISSUE THREAD

**Issue by amitlevy21** [akinsho/bufferline.nvim#916]
### What?

Hi,
Just like [tabby.nvim](https://github.com/nanozuki/tabby.nvim) does, I wish i could restore and persist tab names between sessions when using bufferline.nvim by adding `globals` to `vim.opt.sessionoptions`

### Why?

I use tab pages a lot in my workflow, and I name them a lot. It's annoying to keep renaming them every time i exit Neovim

Thank you for your consideration!

**Comment by akinsho** [comment]
@amitlevy21 happy to take a PR for this but personally definitely don't have time to take this on. Going to close this out side otherwise I'll just forget but please feel free to contribute either yourself or any readers

**Comment by n-crespo** [comment]
If anyone still wants this functionality, this is how I do it:

- `:BufferLineRename my new tab name` or
- a keymap that takes user input (`<leader>r`)

Doing either of the above without specifying a new tab name resets the tab name. Tab names will also persist through sessions with 

```lua
vim.opt.sessionoptions = vim.opt.sessionoptions .. ",globals"
```


```lua
-- setup :BufferLineRename
vim.api.nvim_create_user_command("BufferLineRename", function(opts)
  local current_tab = vim.api.nvim_get_current_tabpage()
  if opts.args == "" then
    vim.g["BufferLineCustomName" .. current_tab] = nil
  else
    vim.g["BufferLineCustomName" .. current_tab] = opts.args
  end
end, {
  nargs = "?",
  desc = "Rename the current tab",
})

-- in your config...
return {
  "akinsho/bufferline.nvim",
  opts = {
    options = {
      -- .... 
      name_formatter = function(buf) -- use custom name if set
        local custom_name = vim.g["BufferLineCustomName" .. buf.tabnr]
        if custom_name and custom_name ~= "" then
          return custom_name
        else
          return buf.name
        end
      end,
    }
  },
  keys = {
    {
      "<leader>r",
      function()
        vim.ui.input({ prompt = "New Tab Name: " }, function(input)
          if input then
            vim.cmd("BufferLineRename " .. input)
          end
        end)
      end,
      desc = "Rename Tab",
    },
  }
}
```
