### ISSUE TITLE
[Bug]: Plugin broken in neovim 0.10

### ISSUE THREAD

**Issue by razziel89** [akinsho/bufferline.nvim#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that the plugin no longer works with neovim >= 0.10 because it appears to use a deprecated API call.

### What did you expect to happen?

The plugin was supposed to work with neovim >= 0.10.

### Config

I will skip this section because I will open a PR suggesting a fix soon. I can add it if still required, though.

### Additional Information

[The deprecated API call.](https://neovim.io/doc/user/deprecated.html#vim.tbl_islist())

### commit

5aa803aaa9d8bbbca77d0c8df8ddc0b62c19ff6a

**Comment by akinsho** [comment]
I've responded on the PR itself but I don't think this is still an issue on the most recent version of the plugin. Although tbh I don't think I'm going to try to support nightly anymore anyway. There are way too many changes on there to deal with on a weekly basis

**Comment by lTriNiTyl** [comment]
I think it's also a way to make sure that the files in the .local/share/nvim/site/packer/start/nvim-bufferline.lua/ path are up to date.

**Comment by akinsho** [comment]
@lTriNiTyl that's not how that should work. Your local cached Packer files should not influence how code is written here. You just need to make sure that when you update that properly gets updated and you recompile the Packer file

**Comment by razziel89** [comment]
Hi @akinsho, thanks a lot for your replies, both here and in the PR, and my apologies for causing effort. You are right, the referenced commit is really very old. This appears to be a problem with my package manager, which does not appear to be updating some plugins correctly. I'll close this issue and the PR I've opened.
