### ISSUE TITLE
[Bug]: Highlight group for unselected buffers

### ISSUE THREAD

**Issue by SimonHoSprung** [akinsho/bufferline.nvim#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm trying to understand which highlight group is being used to control the bg color of visible but unselected buffers:
![image](https://github.com/akinsho/bufferline.nvim/assets/161376117/7cfb65ec-be82-46f1-bb6c-3c32a212be1a)

As you can see from the image I'm trying to set the bg to a red just for testing, but none of BufferlineBuffer, BufferlineDuplicate, BufferlineBackground or BufferlineVisible seem to be correct. None of the highlight groups in the help refer to this either

### What did you expect to happen?

Unless I'm overlooking a group, I'm expecting one of the highlight groups above to be setting the unselected buffer backgrounds to red

### Config

```
      options = {
        mode = "buffers",
        numbers = "none",
        themable = true,
        indicator = {
          style = "icon",
          icon = "▎",
        },
        hover = {
          enabled = false,
        },
        truncate_names = true,
        color_icons = true,
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = true,
        show_tab_indicators = true,
        show_duplicate_prefix = true,
        persist_buffer_sort = true,
        separator_style = "thick",
        enforce_regular_tabs = false,
        always_show_bufferline = true,
        sort_by = "extension",
      },
```

### Additional Information

...

**Comment by akinsho** [comment]
Hi @SimonHoSprung,

So I get requests like this very often. There are quite a few highlights and figuring out which is which can be time consuming. Unfortunately it is just a question of digging around. I don't have the list in mind and can't often just tell so it would just be me doing what you're doing which is checking. Unfortunately after this had come a dozen times before I had to remove myself from the equation as it's just too time consuming helping people pick out highlight groups. If you stick with it you'll identify it if it exists. Sorry I don't have the exact same
