### ISSUE TITLE
[Bug]: when cursor in toggleterm window, clicking bufferline tab cause text rendered inside toggleterm window

### ISSUE THREAD

**Issue by erlangparasu** [akinsho/bufferline.nvim#935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when cursor in toggleterm window, clicking bufferline tab cause text rendered inside toggleterm window

### What did you expect to happen?

text rendered in buffer window, not inside toggleterm window

### Config

lazyvim

`"LazyVim": { "branch": "main", "commit": "00f53315b59fd35ef05ea74e66423944a2012974" },`

### Additional Information

...

### commit

`"bufferline.nvim": { "branch": "main", "commit": "81820cac7c85e51e4cf179f8a66d13dbf7b032d9" },`

`"toggleterm.nvim": { "branch": "main", "commit": "cd55bf6aab3f88c259fa29ea86bbdcb1a325687d" },`

**Comment by akinsho** [comment]
This is unfortunately nowhere near enough information or and certainly not minimal enough if you are using lazyvim. You need to try to reproduce this bug with a minimal configuration to confirm it's definitely as a result of this plugin. I can confirm locally that I can't reproduce this by just tapping a buffer whilst in the terminal

**Comment by erlangparasu** [comment]
> This is unfortunately nowhere near enough information or and certainly not minimal enough if you are using lazyvim. You need to try to reproduce this bug with a minimal configuration to confirm it's definitely as a result of this plugin. I can confirm locally that I can't reproduce this by just tapping a buffer whilst in the terminal

Here is my config: https://github.com/erlangparasu/dot-config-nvim/tree/e70268f543a931f0554a8d1320b60bac2af70904

**Comment by erlangparasu** [comment]
like excluding nvim-tree window, terminal window, neo-tree window, etc

**Comment by jimafisk** [comment]
It seems like this is being explained here https://github.com/akinsho/bufferline.nvim/issues/267#issuecomment-978090356:

> you are doing some clicking of the buffer tabs, but I'm guessing you imagined that the buffers would open in the bigger window instead of the smaller window. This is a fundamental difference with nvim versus GUIs like vscode. All windows are essentially the same, all that happens when you click a buffer is we run `:edit <bufname>` if you are inside the small window, then that is where it will open.
