### ISSUE TITLE
[Feature Request]: show buffers only for specific tab

### ISSUE THREAD

**Issue by erlangparasu** [akinsho/bufferline.nvim#936]
### What?

for example:
tab 1: contains buffer1, buffer2, buffer3
tab 2: contains buffer4, buffer5 (hides buffer1-3)

**Comment by akinsho** [comment]
This has been discussed before and the conclusion is essentially that that won't be added here. Please take a look at something like scope.nvim

**Comment by erlangparasu** [comment]
> This has been discussed before and the conclusion is essentially that that won't be added here. Please take a look at something like scope.nvim

ow thanks for suggestion
