### ISSUE TITLE
[Feature Request]: absolute hidden indicator without any padding space

### ISSUE THREAD

**Issue by flczcy** [akinsho/bufferline.nvim#937]
### What?

Support config for hidden indicator without any padding space

### Why?

1. when set `indicator.style = "none"`, indicator still with a space padding

```
indicator = {
    icon = "", -- this should be omitted if indicator style is not 'icon'
    style = "none",
},
```

<img width="825" alt="Snipaste_2024-07-13_19-17-11" src="https://github.com/user-attachments/assets/7bc5d23a-173f-43a9-a669-96e368e36489">

2. when set `indicator.style = icon` and `indicator.icon = ""`, then buffer_visible get a space padding. when open a float window, current buffer lose focus.

```
indicator = {
    icon = "", -- this should be omitted if indicator style is not 'icon'
    style = "icon",
},
```

<img width="1164" alt="image" src="https://github.com/user-attachments/assets/7a0b3850-0018-4424-a7d8-67ac393fee0e">

**Comment by akinsho** [comment]
Tbh I'm not looking to add yet more configuration to this plugin. I think that it's fine to want more granular control but at a certain point it's easier and better to just use one of the alternative bufferline plugins that's built around maximum customisability. This one isn't built for that. In general the idea with this plugin is that you like the way it looks out of box or with very minimal tweaks or you use something else which is perfectly fine. I'm not really looking to build something which is intended for maximum configuration
