### ISSUE TITLE
[Feature Request]: Hide bufferline when there is less than 1 buffer

### ISSUE THREAD

**Issue by zackychann** [akinsho/bufferline.nvim#951]
### What?

hide bufferline when there is less than 1 buffer
so far this is what i have:
```lua
vim.api.nvim_create_autocmd({"BufNew", "BufNewFile", "BufRead"}, {
	callback = function()
	 if #vim.fn.getbufinfo { buflisted = 1 } >= 2 then
		 require("bufferline").setup{}
		 return true
	 end
	end
})

### Why?

it looks ugly fr

**Comment by akinsho** [comment]
There is never less than one buffer open in neovim and already support for hiding it for 1 buffer

**Comment by zackychann** [comment]
https://suckless.clippy.gg/guevaru/pictures/ns16bu80.png

**Comment by zackychann** [comment]
![image](https://suckless.clippy.gg/guevaru/pictures/ns16bu80.png)

**Comment by akinsho** [comment]
@zackychann you are using a starter screen (alpha) that is definitely a buffer i.e. you definitely have a buffer open. You likely have not set it to `nobuflisted` or set the bufferline to not show if there is only one buffer. I also used this plugin in the past and there's lots of ways to solve this without a change here i.e. you should just set `noshowtabline` in the setup of alpha or configure it or show no bufferline in nobuflisted.

**Comment by sck1ss** [comment]
I fixed it using an autocommand but your suggestion also worked, thanks
