### ISSUE TITLE
[Feature Request]: Can we make the color of the indicator and filetype-icon same?

### ISSUE THREAD

**Issue by iamhrigved** [akinsho/bufferline.nvim#953]
### What?

I want same color for the `nvim-web-devicons` icon and the indicator (specially the underline).

I think if it will look cool!

I believe the feature isn't difficult to implement, but I'm having trouble doing it on my own. I need some basic guidance to help me build it.

### Why?

It will enhance the look and feel of the plugin, making it more appealing to users.

**Comment by akinsho** [comment]
Hi @iamhrigved you could possibly do this but honestly it'll be a pain but I'll leave that to you to work through I don't have enough time to work through that. As to making that a feature I'm not really in favour sorry seems kind of messy aesthetically IMO having it change depending on the file you're in. Ultimately people should be able to focus on their work and not get distracted by this plugin
