### ISSUE TITLE
[Bug]: Weird display of the current buffer

### ISSUE THREAD

**Issue by MartinDelille** [akinsho/bufferline.nvim#954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that the color of the current buffer seems to be inverted in the buffer line:

<img width="262" alt="Screenshot 2024-08-07 at 17 33 11" src="https://github.com/user-attachments/assets/b001d79b-7905-49a2-b5eb-4e68e6f46b59">

### What did you expect to happen?

According to my theme, I would expected that the background would be dark and the foreground would be bright.

### Config

```
return {
	"akinsho/bufferline.nvim",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	version = "*",
	opts = {
		options = {
			mode = "tabs",
		},
	},
}
```

### Additional Information

I tried to invert the hightlight.buffer_selected: 

```
			highlights = {
				buffer_selected = {
					bg = "#e0e2ea",
					fg = "#3a3a3a",
				},
			},
```

Unfortunately, I still have an issue with the tab icon:

<img width="241" alt="Screenshot 2024-08-07 at 17 51 46" src="https://github.com/user-attachments/assets/5513cbb6-e800-4b31-86d1-7a2c93641d8b">

**Comment by akinsho** [comment]
@MartinDelille I apologise but I can only really deal with critical functionality bugs and issues. This is almost certainly an issue with colorschemes and configuration (as I've seen dozens of this sort of config related issues in the past) and can't help debug them unfortunately as it's waay too time consuming. I would start by trying different colorschemes and going from there.

**Comment by MartinDelille** [comment]
Of course I can understand. As I started to look into it would you mind to just to point me some little tips to debug this myself ?

Two questions: 
- could you tell me which colorscheme you are using ? (I'm using catppuccin_frappe)
- Is there a way to dump how are rendered element of neovim interface to troubleshoot this ?

I would understand if you don't answer so no worries! 😄

**Comment by tzinadah** [comment]
I found what's wrong refer to #1027
