### ISSUE TITLE
[Feature Request]: popup window to reorder/delete buffers

### ISSUE THREAD

**Issue by linusboehm** [akinsho/bufferline.nvim#955]
### What?

add support for a popup window that displays all currently open buffers (one filename per line) to reorder buffers and delete buffers. Reordering can be achieved by simply changing the order of the filenames in the popup, deleting by deleting the respective filename/line. The buffers are updated according to the state of the popup window when the popup is closed.

### Why?

When I explore new projects I usually use the LSP to jump from file to file to explore the code. This means that after a while I have a ton of tabs open. Some of them might not be super useful to be open, but are distributed across the bufferline (so I need to cycle through them and close each individual one).

Some other tabs might be far apart from each other, but should ideally be next to each other (e.g. a hpp file and the corresponding cpp file). Moving them over with `BufferLineMove<Prev/Next>` can be quite tedious for a larger amount of buffers.

Inspired by: https://github.com/j-morano/buffer_manager.nvim/tree/main

**Comment by akinsho** [comment]
@linusboehm this really seems like it opens up the scope of this plugin in a very worrying way for me. So for context I have desperately tried and failed to keep this plugin minimal. I think that overwhelmingly users are looking for places to "put" functionality they want and so are looking to their various plugins to see if they can widen the scope of x to add some feature they want. This often leads to many many requests to essentially make bufferline the plugin that manages their buffers and tabs both visually and actually.

This is **not what I built this plugin for** this plugin is *just* for visualising your buffers, not controllling them. Nvim itself has functionality for this, various tree plugins have functionality for this, various search plugins like telescope and fzf have this also. I unfortunately barely have the time to maintain this plugin as is, am getting issues about it not being lightweight enough as well as requesting more and more features. 

If I add menus to this popup I really think the game will be lost and the dam will burst, with questions like can the menu also do x? can we add another sub menu etc. Hopefull this is understandable.

**Comment by linusboehm** [comment]
completely understand. Thanks for the great plugin and thanks for taking the time to answer and explain!

**Comment by linusboehm** [comment]
completely understand. Thanks for the great plugin and thanks for taking the time to answer and explain!
