### ISSUE TITLE
[Bug]: Zip files (zip.vim) slightly break the plugin

### ISSUE THREAD

**Issue by ArijanJ** [akinsho/bufferline.nvim#960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When navigating to a zip file in the bufferline (my use case: `nvim *` in a directory with a few text + zip files), the file disappears from the bufferline and you can't use BufferLineCycleNext/Prev to get out of there.

### What did you expect to happen?

The zip.vim view should be kept as a regular tab and it shouldn't break the tabline

### Config

Default

### Additional Information

For future reference of anyone finding this, the workaround I found was hitting `ctrl+o -> ctrl+i` which still leaves the plugin in a slightly broken state, but at least it's usable.

**Comment by akinsho** [comment]
@ArijanJ this needs more information, what does "breaks the plugin mean" what errors do you see precisely what fails to happen that you expect to happen. `zip.vim` is likely opening inside a `nobuflisted` buffer which are filtered out by default

**Comment by ArijanJ** [comment]
You are right, it seems that it's the default behavior or vim and nvim to hide the zip.vim buffer when it opens.
