### ISSUE TITLE
[Bug]: Why is my icon not displayed and the buffer on the left tree is not aligned?

### ISSUE THREAD

**Issue by 13days** [akinsho/bufferline.nvim#964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Why is my icon not displayed and the buffer on the left tree is not aligned?
OS：Linux
![image](https://github.com/user-attachments/assets/e536a9a1-16d2-4711-a20e-ab706e8ca0b2)

### What did you expect to happen?

Expected behaviour

### Config

 require('nvim-web-devicons').setup()

### Additional Information

...

**Comment by akinsho** [comment]
I'm sorry but in general I can't answer informational/usage questions like this please look through the docs/search places like reddit or previous issues. It takes too much time to provide issue by issue advice to all users
