### ISSUE TITLE
[Feature Request]: Shuffling tabs

### ISSUE THREAD

**Issue by Eloquencere** [akinsho/bufferline.nvim#966]
### What?

I was interested to know or to propose the implementation of free moving, and swapping of tabs on the tabline.

### Why?

Since `barbar.nvim` has that feature and I really like the ability to `:q` out of a tab with `bufferline`, which barbar doesn't currently support.

**Comment by akinsho** [comment]
Tabs can already be moved this is described in the help docs, please have a look there
