### ISSUE TITLE
[Bug]: nvim-data/lazy/bufferline.nvim/lua/bufferline/ui.lua:132: Segments must be a list

### ISSUE THREAD

**Issue by Bowarc** [akinsho/bufferline.nvim#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When i open a file, i get an error message saying "Segments must be a list"

I've seen other issues about this bug, but updating did not fix the issue for me.

It might be my bad, but i don't really understand :c

I tried clearing ../nvim-data and reinstalling but it did not change anything

### What did you expect to happen?

To be able to see the bufferline bar when i open a file

(instead i get an error message)

### Config

Here is my config: ([full](https://github.com/bowarc/bwrc.nvim))

```lua
-- (/lua/plugins/bufferline.lua)
return {
  { 'akinsho/bufferline.nvim', version = "4.7.0", dependencies = 'nvim-tree/nvim-web-devicons' }
}
``` 

```lua
-- (/lua/config/bufferline.lua)
vim.opt.termguicolors = true
require("bufferline").setup{}
```

### Additional Information

❯_: nvim --version
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by akinsho** [comment]
@Bowarc this is almost certainly a neovim version issue/ plugin version issue. please make sure your neovim is the latest stable and your version of this plugin is on the latest

**Comment by Bowarc** [comment]
Yes, i know, but from what i see, i have no idea how to fix it.

As listed above, the version numbers seem fine.

**Comment by Bowarc** [comment]
I think i found a problem

After a fresh install w/ the version settings above, 

using `git status` and `git log` in `/nvim-data/lazy/bufferline.nvim` shows: 
```console
C:\Users\<user>\AppData\Local\nvim-data\lazy\bufferline.nvim>git status
HEAD detached at 243893b
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        doc/tags

nothing added to commit but untracked files present (use "git add" to track)

C:\Users\<user>\AppData\Local\nvim-data\lazy\bufferline.nvim>git lgr
6ac7e4f - <Bryce Neal 3 months ago> fix: UNKNOWN PLUGIN error resulting from unloaded buffers (#928)
46192e7 - <Akin 3 months ago> revert: remove fix for referencing unloaded buffers (#930)
1662fed - <Bryce Neal 3 months ago> fix: UNKNOWN PLUGIN error resulting from unloaded buffers (#931)
81820ca - <Luco Bellic 3 months ago> fix(tabs): use custom separator_style in tabpages (#852)
aa16daf - <Gutyina Gergő 3 months ago> feat(diag): add `diagnostics_update_on_event` option (#932)
2e3c8cc - <github-actions[bot] 2 months ago> chore(main): release 4.7.0 (#929)
28e347d - <Yi Ming 2 months ago> feat(tabpages): pass the bufnr to the `name_formatter` (#941)
6e535bf - <github-actions[bot] 2 months ago> chore(main): release 4.8.0
f98ede0 - <Gutyina Gergő 2 months ago> docs: fix broken/buggy lua examples (#943)
0b2fd86 - <Gutyina Gergő 2 months ago> docs: nerdfonts symbols improvements (#945)
```

I then found something that seems to update everything correctly:
```console
C:\Users\<user>\AppData\Local\nvim-data\lazy\bufferline.nvim>git switch main
Previous HEAD position was 243893b chore(main): release 3.7.0 (#721)
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

C:\Users\<user>\AppData\Local\nvim-data\lazy\bufferline.nvim>git pull
Already up to date.
```

It seems to be working fine now, but it annoys me a bit that the git seems fcked up at install


Do you have any idea how to fix this ? (I don't know nvim a lot)

**Comment by akinsho** [comment]
@Bowarc this isn't really within the scope of this plugin, so not really a good question for this issue, really a plugin manager/git issue, sorry can't really spare the time to get into it

**Comment by Bowarc** [comment]
Yea, that makes sense, no problem.

**Comment by erodactyl** [comment]
@Bowarc I had the same issue. What worked for me is deleting the ~/.local/share/nvim/lazy/bufferline.nvim directory and removing the plugin setup code from my nvim. Then I added it back. Note that I use the Lazy package manager. That fixed the problem!
