### ISSUE TITLE
[Bug]: bufferline colors

### ISSUE THREAD

**Issue by gGameDevelop** [akinsho/bufferline.nvim#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Some times the bufferline colors need restart many times for setup correctly
![Capture](https://github.com/user-attachments/assets/d8a58cc5-bdce-4f31-aa11-648b391a6d34)

### What did you expect to happen?

.

### Config

``` lua
require("bufferline").setup({
    options = {
        separator_style = "slant"
    }
})


### Additional Information

...

### commit

*

**Comment by Numb-0** [comment]
i have the same bug re-opening nvim sometimes solve the problem
![2024-10-21-212121_hyprshot](https://github.com/user-attachments/assets/1a65904b-e8c1-4cbd-bad4-61bc2e9e66ca)

**Comment by gGameDevelop** [comment]
> I modified get_color like so:
> 
> ```lua
> ---@alias GetColorOpts { name: string, attribute: "fg" | "bg" | "sp", fallback: GetColorOpts?, not_match: string?, cterm: boolean? }
> --- parses the GUI hex color code (or cterm color number) from the given hl_name
> --- color number (0-255) is returned if cterm is set to true in opts
> --- if unable to parse, uses the fallback value
> ---@param opts GetColorOpts
> ---@return string? | number?
> function M.get_color(opts)
>   local name, attribute, fallback, not_match, cterm =
>     opts.name, opts.attribute, opts.fallback, opts.not_match, opts.cterm
>   -- TODO: remove when 0.9 is stable
>   if not new_hl_api then attribute = hl_color_attrs[attribute] end
> 
>   -- try and get hl from name
>   local success, hl = pcall(get_hl, name, cterm)
>   if success and hl and hl[attribute] then
>     if cterm then return hl[attribute] end
>     -- convert from decimal color value to hex (e.g. 14257292 => "#D98C8C")
>     local hex = ("#%06x"):format(hl[attribute])
>     if not not_match or not_match ~= hex then return hex end
>   end
>   --- NOTE: in case of cterm, nvim_get_hl_by_name may return incorrect color
>   ---  numbers (but still < 256) for some highlight groups like TabLine,
>   ---  but return correct numbers for groups like DevIconPl. this problem
>   ---  does not happen for gui colors.
> 
>   if cterm then print("cterm") return end -- no fallback for cterm colors
>   if fallback and type(fallback) == "string" then print("string") return fallback end -- basic fallback
>   if fallback and type(fallback) == "table" then print("table") return M.get_color(fallback) end -- bit of recursive fallback logic, which allows chaining
> 
>   return "NONE" -- we couldn't resolve the color
> end
> ```
## wher you write that??

**Comment by Numb-0** [comment]
> > I modified get_color like so:
> > ```lua
> > ---@alias GetColorOpts { name: string, attribute: "fg" | "bg" | "sp", fallback: GetColorOpts?, not_match: string?, cterm: boolean? }
> > --- parses the GUI hex color code (or cterm color number) from the given hl_name
> > --- color number (0-255) is returned if cterm is set to true in opts
> > --- if unable to parse, uses the fallback value
> > ---@param opts GetColorOpts
> > ---@return string? | number?
> > function M.get_color(opts)
> >   local name, attribute, fallback, not_match, cterm =
> >     opts.name, opts.attribute, opts.fallback, opts.not_match, opts.cterm
> >   -- TODO: remove when 0.9 is stable
> >   if not new_hl_api then attribute = hl_color_attrs[attribute] end
> > 
> >   -- try and get hl from name
> >   local success, hl = pcall(get_hl, name, cterm)
> >   if success and hl and hl[attribute] then
> >     if cterm then return hl[attribute] end
> >     -- convert from decimal color value to hex (e.g. 14257292 => "#D98C8C")
> >     local hex = ("#%06x"):format(hl[attribute])
> >     if not not_match or not_match ~= hex then return hex end
> >   end
> >   --- NOTE: in case of cterm, nvim_get_hl_by_name may return incorrect color
> >   ---  numbers (but still < 256) for some highlight groups like TabLine,
> >   ---  but return correct numbers for groups like DevIconPl. this problem
> >   ---  does not happen for gui colors.
> > 
> >   if cterm then print("cterm") return end -- no fallback for cterm colors
> >   if fallback and type(fallback) == "string" then print("string") return fallback end -- basic fallback
> >   if fallback and type(fallback) == "table" then print("table") return M.get_color(fallback) end -- bit of recursive fallback logic, which allows chaining
> > 
> >   return "NONE" -- we couldn't resolve the color
> > end
> > ```
> 
> ## wher you write that??

I created a fork of the repo then updated my nvim config to use the local repo as the plugin you can find the get_color(opts) method in lua/bufferline/colors.lua

**Comment by akinsho** [comment]
A big part of how colors work will depend on how you have set up neovim and your plugins and specifically when this plugin is being setup is it before or after your colorscheme etc. This sort of issue is more dependent on a user's config because it's quite hard for this plugin to account for all the ways that people tend to set things up

**Comment by Numb-0** [comment]
yeah the colorscheme was not loaded before getting the colors you just need to prioritize the loading like this:
```lua
return {
  "catppuccin/nvim",
  lazy = false,
  priority=1000,
  name = "catppuccin",
  config = function()
    require("catppuccin").setup({flavour = "macchiato"})
    vim.cmd.colorscheme "catppuccin"
  end
}
```

**Comment by akinsho** [comment]
Thanks @Numb-0 it's usually stuff like that that causes these sorts of issues which is out of my hands, please try something like the above 🙏🏿

**Comment by gGameDevelop** [comment]
> A big part of how colors work will depend on how you have set up neovim and your plugins and specifically when this plugin is being setup is it before or after your colorscheme etc. This sort of issue is more dependent on a user's config because it's quite hard for this plugin to account for all the ways that people tend to set things up

but maybe the issues is from the bufferline on some configs or workspaces like lazyvim or NvChad, me I'm using my custom conf but steel the bufferline have this issue

**Comment by gGameDevelop** [comment]
and lazy use the lua/plugins dir so how i can now the sorts of exec of plugins
