### ISSUE TITLE
[Bug]: Severe performance degradation when vimtex is compiling

### ISSUE THREAD

**Issue by moetayuko** [akinsho/bufferline.nvim#983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When using `bufferline.nvim` and compiling tex (particularly large ones) in the background, neovim becomes unresponsive, and its CPU usage spikes to 100%. This issue resolves once the compilation process is complete. I profiled with `snacks.profiler`, and this function is identified to be the most time-consuming one (it's invoked with an unusually high frequency) https://github.com/akinsho/bufferline.nvim/blob/261a72b90d6db4ed8014f7bda976bcdc9dd7ce76/lua/bufferline/buffers.lua#L54

The maintainer of vimtex has no clue and suspects it's bufferline.nvim's issue.

### What did you expect to happen?

normal cpu usage when vimtex is compiling

### Config

https://github.com/LazyVim/LazyVim/blob/d0c366e4d861b848bdc710696d5311dca2c6d540/lua/lazyvim/plugins/ui.lua#L4-L58

### Additional Information

...

**Comment by moetayuko** [comment]
This is due to the diagnostics being too frequent, not a bug of bufferline.nvim

**Comment by bgw** [comment]
I've experienced similar after saving a file (runs `cargo check` on save) with rust-analyzer (via rustaceanvim).

**Comment by Daydreamer-riri** [comment]
Hi @bgw, how did you end up resolving this? I’m running into the same issue. It definitely needs to be addressed, but I’m not sure whether the root cause lies with Neovim, bufferline, or rust-analyzer.

**Comment by Daydreamer-riri** [comment]
https://github.com/rust-lang/rust-analyzer/discussions/20856#discussioncomment-14708471

@moetayuko @akinsho Should this issue be reopened?

**Comment by bgw** [comment]
Sorry, only seeing this a ~year later, but in case anyone else runs into this, I worked around it by disabling diagnostics:

```lua
return {
  {
    "akinsho/bufferline.nvim",
    opts = function(_, opts)
      opts.options.diagnostics = false
    end,
  },
}
```

I don't know if this is still an issue or not.
